### ISSUE TITLE
Roadmap - Features list

### ISSUE THREAD

**Issue by stef-k** [holger1411/understrap#102]
I am opening this as a place for discussion about project's roadmap - goals - features list.

@holger1411 do you have any features in mind? if not we could compile a feature list somewhere or here or as intepented issues so anyone interested can pickup a feature to develop.

Some examples could be
- templates - for the theme and/or WooCommerce
- additional functionality found elsewhere or in plugins
-  ...

**Comment by holger1411** [comment]
@stef-k Good idea! There are a lot of new features from open issues or in my mind. A place to collect and priorize ´em would be helpful. Will start an official "Feature Request" in a separated thread.

**Comment by holger1411** [comment]
Add a initial list here: https://github.com/holger1411/understrap/issues/103
Closing this issue
