### ISSUE TITLE
Undefined var in custom-comments.php

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [holger1411/understrap#11]
Notice: Undefined variable: req in F:\xampp\htdocs\wordpress\wp-content\themes\material-world\inc\custom-comments.php on line 25

```php
<label for="comment" class="control-label">' . _x( 'Comment', 'noun', 'understrap' ) . ( $req ? ' <span class="required">*</span>' : '' ) . '</label>
```

**Comment by holger1411** [comment]
Thx again, fix it. 
While doing this I also add Bootstrap classes for submit button.

**Comment by Thomas-A-Reinert** [comment]
Yup, läuft. Danke!

**Comment by holger1411** [comment]
Schöne Grüße zurück!
