### ISSUE TITLE
Typo in package.json

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [holger1411/understrap#110]
_undescores-for-npm_ should read _underscores-for-npm_ , I assume? This problem exists in 0.4.8

**Comment by Thomas-A-Reinert** [comment]
fixed in my branch.

**Comment by radscheit** [comment]
Now with this fix, it throws an error on install, that the underscores-for-npm is not known in the npm registry.

**Comment by kesicmilan** [comment]
"underscores-for-npm" should be "underscores"

**Comment by radscheit** [comment]
In that case the version number has to be 0.0.1 instead of 1.0.0 according to https://www.npmjs.com/package/underscores

**Comment by kesicmilan** [comment]
> In that case the version number has to be 0.0.1 instead of 1.0.0
true

**Comment by bryanbergman** [comment]
Can confirm that `"underscores": "^0.0.1"` works.

**Comment by holger1411** [comment]
Sadly I named and published the npm pack  "undescores-for-npm"...without the "r" ...if you just change the name in your package.json npm will find nothing.

And the "underscores 0.0.1" package is NOT the underscores starter theme:
https://www.npmjs.com/package/underscores
Its a generator to create underscores via command line...so it will work but it is the wrong resource...
Found it out by this bug report: https://github.com/holger1411/understrap/issues/121

I change the name back to the one with the wrong spelling (but the right package...).

And now I have to find out how I could rename an already published npm pack...
