### ISSUE TITLE
Strange display-width in submenus

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [holger1411/understrap#111]
![image](https://cloud.githubusercontent.com/assets/5886977/19990772/92854aec-a230-11e6-85b4-a6d357d65c9f.png)

This shows the problem. Submenu ul´s have a fixed with, which makes them expand beyond the parents box. Code to be removed is in line 137 of understrap.scss . Will be fixed in my next commit. This is just a quick info on how to solve it.

**Comment by Thomas-A-Reinert** [comment]
Sidenote: It shouldn´t show level 04/05 anyway. Those should only be shown when the parent menu is opened. Will work on that and commit somewhen later. Needs a rewrite of the navwalker, I guess.

**Comment by typeplus** [comment]
How does that work on mobile (xs) out of interest?

**Comment by Thomas-A-Reinert** [comment]
Didn´t test yet, will do later.

**Comment by Thomas-A-Reinert** [comment]
Update: Works like a charm. As I guessed already. Overflow will break into the next line too.

**Comment by Thomas-A-Reinert** [comment]
Commited and pull requested.
