### ISSUE TITLE
Various page templates

### ISSUE THREAD

**Issue by holger1411** [holger1411/understrap#116]
UnderStrap comes with a "no-sidebar" and "sidebar-right" base page template.
There is no "sidebar-left" or "sidebar-left-and-right" template.
And an option to set a global default in the cusotmizer is needed.

So the user can set a global default (for example "sidebar-right") for all pages EXCEPT the pages where she/he selects a specific template.

**Comment by stef-k** [comment]
@holger1411 I think this should be closed now as it has been implemented in #117

**Comment by holger1411** [comment]
Yep, you are right. Thx!
