### ISSUE TITLE
Coding guidelines

### ISSUE THREAD

**Issue by stef-k** [holger1411/understrap#118]
@holger1411  @maxdmyers I know I'm late about b8a5f0c but [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/html/#indentation) advice on using tabs and same code structure as with the PHP files.

I use PHPStorm w/WordPress coding standards check on and the IDE reports this contantly, additionally any auto formatting will result to different code structure.

What would be the best approach for this?

**Comment by VesterDe** [comment]
Perhaps an [editorconfig](http://editorconfig.org/) file?

**Comment by stef-k** [comment]
Im sorry, perhaps i did not described the issue correctly.

The problem is not the IDE, the IDE is set to check if the source complies with WordPress' coding standards. In our case the source complies with MDO's standards which they are completely different from WordPress ones.

Of course the IDE can be set to ignore the guidelines.

So the actual case is which standards should we follow.

**Comment by Thomas-A-Reinert** [comment]
I´d vote for sticking to Wordpress guidelines even if they seem illogical sometimes and differ from other coding-standards. Reason: The theme should be submitted to WP´s repository and therefore _must_ stick to WP´s rules, I guess.

**Comment by maxdmyers** [comment]
If the plan is to submit to the wp.org repository, then I absolutely agree with @Thomas-A-Reinert on this. Otherwise, I like mdo's style.

**Comment by stef-k** [comment]
yes, otherwise the project will not appeal to a big portion of developers as a framework for many use cases. 

anyway I think this should be ressolved at some point before going forward

**Comment by holger1411** [comment]
UnderStrap is already available on wordpress.org: https://wordpress.org/themes/understrap/
So we are free from this restiction.
As a frontend developer I love clean and clean rules like the @mdo guidelines...but basically understrap is a WordPress theme framework, so it should comply to the WordPress ruleset...

**Comment by holger1411** [comment]
Does anyone know a good Sublime package for checking this?

**Comment by stef-k** [comment]
There is [PHP code sniffer](https://github.com/squizlabs/PHP_CodeSniffer)  with the [WordPress coding standards  ](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) ruleset.

In the WordPress coding standards readme you will find info on how to integrate with some editors (PHPStorm, Atom & Sublime Text)

**Comment by Thomas-A-Reinert** [comment]
@holger: I´m sorry, but I totally gotta disgagree with you. You got managed the Q&A once - but they´re able to take understrap offa that once you do not comply to the rules anymore. Its not a once you comply you always comply thingie!!..

So IF you want to want understrap to be in the WP-repo once and forever you just gotta stick to their rules. You may take an outage here and there and they will tell you to apply to it again. This may be handled diffently anyway though. But normally they will still have you in the repo once you passed the Q&A tests. But thats not a thing that can be confirmed in the long run. (Personal experience: They WONT!)

@stef-k thanks for all your input. pretty helpful, still being a downer on the personal side though sometimes ;)

**Comment by holger1411** [comment]
@Thomas-A-Reinert : You may be right, it my first theme in WP.org repo.
Another reason to stick with the WP ruleset.

@stef-k & @Thomas-A-Reinert: Is there any chance to automate this IDE independendly? For example within the "gulp dist" task. Found something like: https://github.com/JustBlackBird/gulp-phpcs

**Comment by VesterDe** [comment]
@holger1411 As far as I know phpcs would only generate a report. I use (without gulp) phpcbf to actually alter source. I see a gulp package also exists.

https://www.npmjs.com/package/gulp-phpcbf

P.S. Before we have it as a gulp package, you can just install phpcbf and use this alias on folders:
alias purewp="phpcbf *.php --extensions=php --standard=WordPress"
And this one for recursive deep checking (don't run it in wp root :)
alias purewp-deep="phpcbf ./ --extensions=php --standard=WordPress"

**Comment by stef-k** [comment]
a solution like the one mentioned @VesterDe would be a good choice because its neutral and does not mess with the various editors people using; needs further investigation though.

**Comment by Thomas-A-Reinert** [comment]
@holger: there are quite some wp-plugs for sublime available that allow code-completion for wp-functions etc. Anyway, I don´t know in how far they stick to the coding standards according to tab-indentation etc. If you get to know anything, please keep me informed!

**Comment by stef-k** [comment]
what is the status of this? how do we proceed?

**Comment by stef-k** [comment]
should I proceed to format code as per WP standards? Has anyone other ideas - objections?

**Comment by holger1411** [comment]
Yes, we will follow the WP standards. So if you have time to start with you are welcome!

**Comment by stef-k** [comment]
ok, will start right away.

**Comment by stef-k** [comment]
After c4e5d495d435f1fa35fc123d1f770ffaa7af665c push, here is the output of [theme check dev plugin](https://wordpress.org/plugins/theme-check/):

![selection_001](https://cloud.githubusercontent.com/assets/5731388/20496070/5924f20c-b02c-11e6-8925-a9664826af98.jpg)

No major issues reported.

not directly related to format style but its good to know where we stand .

If anyone is interested or looking to use various tools for WP development, I've found the following very helpful:

- https://wordpress.org/plugins/debug-bar/
- https://wordpress.org/plugins/developer/
- https://wordpress.org/plugins/monster-widget/
- https://wordpress.org/plugins/regenerate-thumbnails/
- https://wordpress.org/plugins/show-current-template/
- https://wordpress.org/plugins/theme-check/
- https://wordpress.org/plugins/wordpress-importer/
- https://wordpress.org/plugins/wordpress-database-reset/
- https://github.com/squizlabs/PHP_CodeSniffer
- https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

**Comment by holger1411** [comment]
Close this becasue of:
https://github.com/holger1411/understrap/issues/231
