### ISSUE TITLE
Right way to float menu to right or left?

### ISSUE THREAD

**Issue by MrShakeel** [holger1411/understrap#124]
First of all great job @holger1411 integrating bootstrap with underscores. 👍 

Let's come to the problem:
I think WordPress menu is not fully integrated with bootstrap because using `navbar-right` in `menu_class` under wp_nav_menu() is not working.

See this code below:

                              `<?php wp_nav_menu(
                                    array(
                                        'theme_location' => 'primary',
                                        'container_class' => 'collapse navbar-toggleable-xs exCollapsingNavbar',
                                        'menu_class' => 'nav navbar-nav navbar-right',
                                        'fallback_cb' => '',
                                        'menu_id' => 'main-menu',
                                        'walker' => new wp_bootstrap_navwalker()
                                    )
                            ); ?>`

I have used `navbar-right` in `menu_class` and it didn't worked, I think that is the way BootStrap work, so please check this issue.

**Comment by typeplus** [comment]
What exactly are you trying to do? Float the menu to the right? or the menu items?
The official docs ([Here](https://v4-alpha.getbootstrap.com/components/navbar/))

They say to use `.float-*-left `and `.float-*-right` to quickly align sub-components.

**Comment by MrShakeel** [comment]
@typeplus Yes, i would like to float menu to the right.

in bootstrap 3, adding `class="navbar-right"` in `<ul>` float the menu to right. Like this:

`<ul class="nav navbar-nav navbar-right">`

is it deprecated in bootstrap 4 ?

**Comment by typeplus** [comment]
I looked **quickly** and couldn't find it but this will do what you want;

`<ul id="main-menu" class="nav navbar-nav float-md-right">`

Depends what breakpoint you have your mobile nav on but if you want it all aligned right then replace with float-xs-right

**Comment by MrShakeel** [comment]
Thank you, i also tried that when you mentioned `.float-*-right` above.

So i added it like that in Understrap:

`<ul class="nav navbar-nav float-xs-right">` and it worked perfectly, btw what does `xs` stands for ?

**Comment by typeplus** [comment]
xs is the **extra small** breakpoint for tiny screens. sm, md, lg and xl are the others. You can make your own easily with media queries or use the cool `@include media-breakpoint-down(*) { } or @include media-breakpoint-up(*) {}` to keep things in check for all screen sizes.

**Comment by MrShakeel** [comment]
i see, so xs (extra small) will make menu float to right for all screen sizes ?

or there should be a class like float-right to align menu to right for all screen sizes.?

btw, thanks a lot for your help.

**Comment by Thomas-A-Reinert** [comment]
I´d take a look @ the documentation: http://v4-alpha.getbootstrap.com/utilities/responsive-helpers/#responsive-floats

**Comment by MrShakeel** [comment]
Thank you @Thomas-A-Reinert so **xs** is actually for all viewport sizes. 👍

**Comment by MrShakeel** [comment]
Thank you everyone for you help on this.

**Comment by nuthinbutajthang** [comment]
Hi, I was looking for the same solution. But it seems that it isn't working. The menu stays on the left side.

I'm using UnderStrap Child 0.3.2. (with UnderStrap 0.6.2).

`
<?php wp_nav_menu(
	array(
		'theme_location'  => 'primary',
		'container_class' => 'collapse navbar-collapse',
		'container_id'    => 'navbarNavDropdown',
		'menu_class'      => 'nav navbar-nav float-md-right',
		'fallback_cb'     => '',
		'menu_id'         => 'main-menu',
		'walker'          => new WP_Bootstrap_Navwalker(),
	)
); ?>
`

**Comment by davefaloon** [comment]
@nuthinbutajthang - I'm in the same boat. Let me know if you determine a work-around. thx!

**Comment by davigarcas** [comment]
You can use a flexbox  class like this one

```
<?php wp_nav_menu(
	             array(
	'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse justify-content-end',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>






````

**Comment by davefaloon** [comment]
TOUCHDOWN! Thx @davigarcas!

**Comment by nuthinbutajthang** [comment]
Worked for me too! Thanks @davigarcas !!!

**Comment by zalkowitz** [comment]
Amazing! Thanks!

**Comment by RyanHartje** [comment]
What version are you all using that this works?

**Comment by leqnam** [comment]
@RyanHartje: Boostrap v4.0.0-beta.3

**Comment by dandyxu** [comment]
@davigarcas Saved my day! Thank you.
