### ISSUE TITLE
owl carousel not working on custom page

### ISSUE THREAD

**Issue by dawidniepsuj** [holger1411/understrap#125]
Hi how i can use owl carousel on custom page? on front page it's working fine, but when i try to use it on custom page it's not work.

**Comment by holger1411** [comment]
Yes, its just part of the frontpage so far and it will not work on subpages.

**Comment by dawidniepsuj** [comment]
ok, thx

**Comment by holger1411** [comment]
You can create your own specific page template which loads the owl.carousel hero area, too.
If it is easy dependes on your WP/PHP knowledge ;-)

But its on the featuere request list right now:
https://github.com/holger1411/understrap/issues/103
You may wait till its finished

**Comment by Thomas-A-Reinert** [comment]
Custom page will be added in a pull request later today.
