### ISSUE TITLE
Fixed width - full width container variable is breaking things in some templates

### ISSUE THREAD

**Issue by stef-k** [holger1411/understrap#131]
@holger1411 the latest changes made in c9787c436a6cb37525f1ef4cd0a8f4d98ae6c673 and more specifically those for fixed-full width container in all pages cause WP to complain about undefined variable (`$container`).

Somehow the `$container` variable referenced in `header.php` and `footer.php` is out of scope. Perhaps we could solve this by declaring it as global or by checking customizer's settings in those files too.

This is the output I'm getting from the WP debug:

```
NOTICE: wp-content/themes/understrap/header.php:36 - Undefined variable: container
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/understrap/page.php'), get_header, locate_template, load_template, require_once('/themes/understrap/header.php')

NOTICE: wp-content/themes/understrap/footer.php:17 - Undefined variable: container
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/understrap/page.php'), get_footer, locate_template, load_template, require_once('/themes/understrap/footer.php')```

**Comment by holger1411** [comment]
Yes, you are right.
It should be a gloabl variable because it is used in any files which include the "conatiner" class.
I´am not a real PHP developer. Do you know how i declare the both variables (`container_type` and `understrap_sidebar_position` ) as global values?

**Comment by holger1411** [comment]
Thats the file:
https://github.com/holger1411/understrap/blob/master/inc/customizer.php

**Comment by stef-k** [comment]
You can declare and assign a global variable like this:

```php
// declaration
global $container;
// assignment
$container = get_theme_mod('understrap_container_type');
```

but I think it should be better if we didn't use globals and simply use a local variable as the rest of the templates like this `$container = get_theme_mod('understrap_container_type');`

Here is some info about how to use and why not to use...
http://wordpress.stackexchange.com/questions/89263/how-to-set-and-use-global-variables-or-why-not-to-use-them-at-all

**Comment by stef-k** [comment]
I'll create a PR to fix this, feel free to assign it to me.

**Comment by stef-k** [comment]
@holger1411 you can close this now, thanks
