### ISSUE TITLE
Make 'gulp watch' watch scripts and run 'gulp scripts' as well?

### ISSUE THREAD

**Issue by televators** [holger1411/understrap#134]
I can't wait for the docs to be made because I keep running into so many small weird things regarding where things are supposed to go since the directory hierarchy is a bit confusing.
Figured out, thanks to older closed issues, where to put my custom js files and ran gulp scripts but if I'm bouncing back and forth between scss and js during theme development, having to pull up my CLI and stop 'gulp watch', run 'gulp scripts', then run 'gulp watch' again is a bit tedious.
Is there a way to make 'gulp watch' monitor js and run the scripts uglify/concat/minify processes as well? This is my first real experience with gulp and I'm just not sure. Thanks!

**Comment by stef-k** [comment]
@televators I use `concurrently`  with npm to run 2 tools (webpack & gulp) in parallel, here is the relevant part of the `package.json` file

```json
  "scripts": {
    "alldev": "concurrently --kill-others 'webpack --colors --watch' 'gulp watch'"
  },
```

I run it with `npm run alldev`. By using the same technique you should be able to run both tools.

https://github.com/kimmobrunfeldt/concurrently

**Comment by televators** [comment]
Thanks for the tip! I"ll try that out.

**Comment by stef-k** [comment]
@holger1411 maybe it would be a good idea to [integrate](https://github.com/kimmobrunfeldt/concurrently) concurrently in understrap's workflow so we can watch-build-develop both SCSS and JS files...

This way a developer would need to run only one-global process from terminal.

**Comment by stef-k** [comment]
@televators have you managed to make it work?

**Comment by holger1411** [comment]
See: https://github.com/holger1411/understrap/commit/a8ec9c10a451086eae286213ff7749250eaa33e2

`gulp-scripts` runs if there are changes in `/src/js/` , too
