### ISSUE TITLE
Unable to compile sass? Missing bootstrap files?

### ISSUE THREAD

**Issue by wkdcode-josh** [holger1411/understrap#145]
Is there anything else I need to do to use this theme? i am unable to compile the sass as it is?

**Comment by saknopper** [comment]
https://github.com/holger1411/understrap#developing-with-npm-gulp-and-sass-and-browser-sync1

Did you perform `npm install` and `gulp copy-assets` ?

**Comment by wkdcode-josh** [comment]
I only ran npm install?

**Comment by saknopper** [comment]
Then you know what to do... ;)
