### ISSUE TITLE
BrowserSynce proxy

### ISSUE THREAD

**Issue by danawren** [holger1411/understrap#151]
I am trying to set up BrowserSync but I can't get understrap to show in it. I know I have it installed because the BrowserSync ui shows up.

var browserSyncOptions = {
    proxy: "localhost/theme_test/", // <----- CHANGE HERE
    notify: false
};

What am I supposed to put on the "<---- Change Here" line? I've tried a bunch of options and so far no luck.

**Comment by holger1411** [comment]
It depends on your local test enviroment. What do you have to type in to your browser to see your local WP install?
For example I run MAMP and installed WP in a subfolder called /understrap
MAMP uses this: localhost:8888
so I put in /localhost:8888/understrap

**Comment by stef-k** [comment]
Maybe this example should be better included in readme

**Comment by holger1411** [comment]
I add it to the docs here:
https://understrap.github.io/

**Comment by stef-k** [comment]
@danawren did you manage to make it work?
