### ISSUE TITLE
Gallery code and hidden class

### ISSUE THREAD

**Issue by stef-k** [holger1411/understrap#153]
As I' was testing integration with Magnific Popup - lightbox library today ([details](https://github.com/holger1411/understrap/issues/103#issuecomment-262174707)), i've found that the gallery code generates a CSS class named `hidden`, a Bootstrap 3 class which does not hides anything in B4.

code lines 118-120 of `bootstrap-wp-gallery.php` file : 
```php
if ( trim( $attachment->post_excerpt ) ) {
    $output .= '<div class="caption hidden">' . wptexturize( $attachment->post_excerpt ) . '</div>';
}
```

If this is not placed on purpose, then it should be removed or replaced with one the new classes (B4) most probably the `.hidden-xs-up` class...

**Comment by holger1411** [comment]
done that: https://github.com/holger1411/understrap/commit/bbbfbae63bd8ae320db48b749ed57ffe51be2d6e
