### ISSUE TITLE
understrap/sass/theme/_theme.scss updates are not live

### ISSUE THREAD

**Issue by mvuk** [holger1411/understrap#156]
I added my css to the file:  understrap/sass/theme/_theme.scss

I updated it in the wordpress theme editor, but when I check the live site I see no update to the changes.

Am I missing a step? Am I supposed to be compiling something?

staging site I'm trying this on at:
http://hrvat.wpengine.com/

**Comment by Thomas-A-Reinert** [comment]
Exactly. The theme ain't doing this on it's own.  Please read the instructions,  it's all explained there.

**Comment by mvuk** [comment]
Which instructions are you referring to? I had some trouble finding the right part of the documentation can you please refer to me what I'm doing wrong?

 I apologize I am new to sass and the workflows in modern web dev, I am just leaving recently from working just within the WordPress paradigm

**Comment by Thomas-A-Reinert** [comment]
No problem and most of all no need to apologize.
Feel free to edit .css files as you´re probably used to. If you want to get a little deeper into a little more intelligent workflow, use SCSS, Gulp, Node.js . The setup instructions on how to use understrap with those are on the main page (Scroll down, it´s right under the file listing) => https://github.com/holger1411/understrap .

**Comment by holger1411** [comment]
Or this one:
https://understrap.github.io/#developing
Same description, but better to read;-)

**Comment by sumaximize** [comment]
I'm not able to see result of editing `$primary` color in `_theme_variables.scss` in my understrap-child theme, where am I going wrong ?
👉️ [Full question details here](https://stackoverflow.com/questions/72825027/understrap-child-theme-edit-not-visible-sass-color-variable-not-applied)

- Understrap v1.1
- Undersrap-child
