### ISSUE TITLE
HTML validation fails for a lot of pages by default

### ISSUE THREAD

**Issue by thomasmoors** [holger1411/understrap#159]
The blank / unaltered version of understrap contains html validation errors, which result in unexpected behaviour. I don't have the time to make a list now, but it's easy to make a list with a chrome plugin like [Validity](https://chrome.google.com/webstore/detail/validity/bbicmjjbohdfglopkidebfccilipgeif).

**Comment by Thomas-A-Reinert** [comment]
Yeah,  you're absolutely correct. Had most of them solved already but they got lost due to some merge problems. Will probably correct them again this weekend. No promises though. Nevertheless expect a valid version soon.

**Comment by stef-k** [comment]
most of them are duplicate ids like id="content" on nav, main and footer containers...

currently working on a Laravel project I don't if i have time for this.

**Comment by holger1411** [comment]
I´am on it...

**Comment by holger1411** [comment]
Fixed here: https://github.com/holger1411/understrap/commit/96090bdaf52afcff1ebf1716ba1cf493f5859d02
and here:
https://github.com/holger1411/understrap/commit/366a6e689b376f690a235bb25ff467d59fb8b8a2

**Comment by holger1411** [comment]
now the demo site get a clean record:
https://validator.w3.org/nu/?doc=https%3A%2F%2Funderstrap.com%2Funderstrap%2F

**Comment by holger1411** [comment]
thx @thomasmoors for reporting in
