### ISSUE TITLE
Grid theme layout Understrap 0.5.0 Do you have the same problem?

### ISSUE THREAD

**Issue by TomKisielewski** [holger1411/understrap#163]
1) in admin theme layout settings should be grid post rows instead of columns, at the moment when I select 6 columns it gives me 2 columns

![gridadmincolumns](https://cloud.githubusercontent.com/assets/8680052/20642047/4e050ee6-b3fd-11e6-8476-83b36717188c.png)

If I select two columns it gives me two rows with 6 columns in row

![grid2columns](https://cloud.githubusercontent.com/assets/8680052/20642056/98eb709e-b3fd-11e6-864a-cd5acde6b412.png)

2) Post navigation doesn't look right as it is covered by .card-title which is white color

![gridpostnavigation](https://cloud.githubusercontent.com/assets/8680052/20642083/1ce344b2-b3fe-11e6-98c8-cc87f240570f.png)

change background-color or card-title to other color than white,  i changed it to red in firebug

![grid_card-title](https://cloud.githubusercontent.com/assets/8680052/20642098/4c183bb6-b3fe-11e6-90b9-bd77a19da5c0.png)

Also it displays only images, nothing else. I tried on firefox/mint, chrome/mint and google chrome/win 10, I also have problem with masonry on firefox/mint, but it works fine on chrome/mint and chrome/win10
I have very basic wordpress install with only additional plugin - wordpress importer and I use sample data, so there is really nothing to interfere. Could you please check if this is common issue or just me.

**Comment by stef-k** [comment]
Regarding posts/columns, when selecting 6 columns the you will have two elements shown per row, that is each element will span 6 columns. If you want a grid with 6 posts you will have to set it to 1 column. Think it as you declaring Bootstrap divs `<div col-*-*>`.

As for your second issue, yes the grid displays only the featured image the title and meta posted on... This is on purpose assuming the featured images have same heights in order to keep it like a grid. Otherwise either a flexbox setup is needed or a JavaScript plugin something like http://www.cssnewbie.com/equalheights-jquery-plugin/#.WDnM6HV95hE to force them to equal height.

**Comment by TomKisielewski** [comment]
Ok, thanks stef-k so it works as it should. Regarding posts/columns, you are right from the perspective of the developer ,but if you look at this from the point of view of "normal" user, in the admin panel you have "Choose how many columns to use in grid posts " and if you select 2 ( col-md-2 what developer knows based on 12 col grid) you obtain 6 columns ( what actually "normal user sees" ). GUI doesn't make any sense for "normal" user. IMO it should be changed to "Choose how many columns to use" which refers to "physical" visible number of columns, 6 columns -> col-md-2, 2 visible columns ->col-md-6 and so on. WP admin panel is for the end user, so it may be seen as a bug as at the moment it doesn't make any sense

**Comment by stef-k** [comment]
Hi again, regarding the User Experience issue of the UI, please open a new issue. 

Unfortunately currently I don't have enough time to work on this, maybe someone could grab it, else I'll try to fix it at the first chance.

**Comment by TomKisielewski** [comment]
Hi Stef, I don't want to open another issue as it may not be seen as an issue. I have to tidy up my github and do some reading priory to start my contribution.  Quick fix: /inc/customizer.php  
line 189:

>  'description' => __( 'Choose how many columns to use', 'understrap' ),

line:193-199: 

> 'choices'     => array(
						'6' => '2',
						'4' => '3',
						'3' => '4',
						'2' => '6',
						'12' => '1',
					),

line:200

> 'default'     => 2,

It works fine (what you see is what you get),so if there is somebody willing to use it and make quick change its fine. I think Holger may close it as it is not really the framework issue
Cheers

**Comment by holger1411** [comment]
@TomKisielewski : Add your fix here: https://github.com/holger1411/understrap/commit/c6e0d19cb3f886117280d17706f7b40bcb49c365
Thx for reporting!
