### ISSUE TITLE
Does this theme have built in glyphicon support?

### ISSUE THREAD

**Issue by hmartens** [holger1411/understrap#166]
Glyphicons comes with Bootstrap but it doesn't seem to be available on Understrap?

Thank you for a great theme, love it!

**Comment by holger1411** [comment]
No, UnderStrap based on Bootstrap 4. Bootstrap 4 dropped Glyphicon support.

**Comment by holger1411** [comment]
Sorry!

**Comment by hmartens** [comment]
Thank you. I see Bootstrap is using fontawesome now ;) Thanks for your quick help! Much appreciated.
