### ISSUE TITLE
Bootstrap navbar-right class is not working

### ISSUE THREAD

**Issue by NayeemNipun** [holger1411/understrap#167]
Hello,

For the first time I am using this starter theme on my new WordPress Development. I was so excited. But after installing this theme I tried to show navbar menu to the right side and that's why I added `navbar-right` class on `'menu_class'      => 'nav navbar-nav navbar-right',` . But unfortunately this didn't work. 

One more thing I added two or three widgets under "Hero Slider" widget area and make a page "Homepage" with "Full-Width Page Template". But nothing is showing on that page under "navbar".

I don't know why this is not working. Can you please help me on this? 

Thanks.

**Comment by holger1411** [comment]
Hi!
To your second question first: The slider is only available on the default frontpage.

To your first question: UnderStrap based on Bootstrap 4, the right class to float something to the right is:
`float-xs-right`

While "xs" defines the screensize when the element is floated to the right. "xs" means it will be floatet on all screens.

Other example: 
`float-md-right`
will float the element to the right on medium screens and above, but not on small or extrasmall screen resoultions.
