### ISSUE TITLE
Primary colour is purple

### ISSUE THREAD

**Issue by robertandrews** [holger1411/understrap#168]
Ironic. I had been spending some time coding a plain Bootstrap 4 theme for my WordPress, rewriting Underscores markup as the basis.

Now I'm looking at this.

However, first thing's first...
Have the Bootstrap people changed the "primary" colour from blue to purple with alpha 5?
Or is this something you have done for Understrap?
I have only ever seen it blue until this point, in buttons and hrefs. It makes me wonder what may have been changed with Understrap.

Also, so I can understand - your file contents in css/ ARE Bootstrap 4, is that right? Is theme.css a renamed version of the Bootstrap unminified CSS?
If so, where are all the other files that come with Bootstrap 4, compiled version? Namely, ..

> ./css:
> total 2144
> drwxr-xr-x@ 18 Robert  staff   612B 19 Oct 16:34 ./
> drwxr-xr-x@  5 Robert  staff   170B  3 Dec 13:38 ../
> -rw-r--r--@  1 Robert  staff   143K 19 Oct 16:34 bootstrap-flex.css
> -rw-r--r--@  1 Robert  staff   192K 19 Oct 16:34 bootstrap-flex.css.map
> -rw-r--r--@  1 Robert  staff   116K 19 Oct 16:34 bootstrap-flex.min.css
> -rw-r--r--@  1 Robert  staff    53K 19 Oct 16:34 bootstrap-flex.min.css.map
> -rw-r--r--@  1 Robert  staff    16K 19 Oct 16:34 bootstrap-grid.css
> -rw-r--r--@  1 Robert  staff    25K 19 Oct 16:34 bootstrap-grid.css.map
> -rw-r--r--@  1 Robert  staff    12K 19 Oct 16:34 bootstrap-grid.min.css
> -rw-r--r--@  1 Robert  staff   7.2K 19 Oct 16:34 bootstrap-grid.min.css.map
> -rw-r--r--@  1 Robert  staff   5.7K 19 Oct 16:34 bootstrap-reboot.css
> -rw-r--r--@  1 Robert  staff   9.0K 19 Oct 16:34 bootstrap-reboot.css.map
> -rw-r--r--@  1 Robert  staff   4.6K 19 Oct 16:34 bootstrap-reboot.min.css
> -rw-r--r--@  1 Robert  staff   2.6K 19 Oct 16:34 bootstrap-reboot.min.css.map
> -rw-r--r--@  1 Robert  staff   125K 19 Oct 16:34 bootstrap.css
> -rw-r--r--@  1 Robert  staff   180K 19 Oct 16:34 bootstrap.css.map
> -rw-r--r--@  1 Robert  staff   103K 19 Oct 16:34 bootstrap.min.css
> -rw-r--r--@  1 Robert  staff    45K 19 Oct 16:34 bootstrap.min.css.map
> 
> ./js:
> total 280
> drwxr-xr-x@ 4 Robert  staff   136B 19 Oct 16:34 ./
> drwxr-xr-x@ 5 Robert  staff   170B  3 Dec 13:38 ../
> -rw-r--r--@ 1 Robert  staff    94K 19 Oct 16:34 bootstrap.js
> -rw-r--r--@ 1 Robert  staff    44K 19 Oct 16:34 bootstrap.min.js

Thanks.

**Comment by holger1411** [comment]
Hi!
Thanks for your request.

You´ve got me;-)
Purple is the ONLY change I made in UnderStrap to the Bootstrap defaults. Just to outline where you have to add your own SASS variables to overwrite the Bootstrap values.

Here:
https://github.com/holger1411/understrap/blob/master/sass/theme/_theme_variables.scss
The `$brand-primary `variable is changed. So if you recompile the SASS files every element using the "$brand-primary" varaiable will be purple isntead of the BS blue.

To your second question:
The theme.min.css and theme.css is not justBootstrap 4. It is the compiled CSS file from all CSS used for UnderStrap:
https://github.com/holger1411/understrap/blob/master/sass/theme.scss

Inclusive Font Awesome, the nice purple variable from UnderStrap ,-), some Underscores defaults, the Slider script styles etc.

It takes the variables from UnderStrap and use em to generate your own and unique Bootstrap 4 version, plus anything else you need into one handy css file (one minified for your live version, one unminified for easier  development)

The theme.SCSS source file loads, for example, the Bootstrap 4 base scss file from assets/bootsrap4.scss, which than graps all BS4 scss files from the /src directory:
https://github.com/holger1411/understrap/blob/master/sass/assets/bootstrap4.scss

So you can enable/disable certain scss components without touching the original files.

**Comment by robertandrews** [comment]
Thanks for the reply.

I'm excited about seeing a highly structured, minimal Underscores-type framework that uses Bootstrap 4 markup, but I feel I would have a better idea of what's going on if I could just take the Bootstrap folder I've downloaded, but it in the theme folder and have UnderstStrap use all those Bootstrap originals only.

Having said that, this may be partly down to my relative level of understanding. I have never used SASS/LESS at all and don't plan to dive in at this point.

**Comment by holger1411** [comment]
UnderStrap use all the original files from BS4, but the scss files not the css files.

If you just place a BS4 css copy into the folder structure you can´t work with all these handy variables and functions and calculations and you have to overwrite em manually, by hand.
Every time something changes, everytime there is a Bootstrap4 update, everytime there is an UnderStrap update, if you change one color in your design etc.

Sass is some kind of magic, something every CSS nerd ever whants. So its worth spending some time with it...

**Comment by robertandrews** [comment]
File under: "Why do things have to be so complicated?"
I think we're talking about a few issues: 1. any modifications, 2. storing all Bootstrap components in a "bootstrap" folder vs around the theme directory, regardless of SASS etc, 3. me not speaking SASS.

So, anyway, if I build a child theme off UnderStrap, what's the file I need to use for my own custom overrides? My child's styles.css?
And in plain CSS, or something fancier?

Thanks.

**Comment by stef-k** [comment]
@robertandrews maybe this could help a bit https://understrap.github.io/#gulp-npm-scss-example, the instructions are for the main theme but its showcasing how to use the current infrastructure to change the color of navbar's links.

@holger1411 maybe we should put documentation's link in readme even at this stage

**Comment by holger1411** [comment]
"Why do things have to be so complicated?" - Because its much easier.
 
But working without SASS is possible: Enqueue an additional css file via functions.php in your Child theme or modify the css/child-theme.min.css and add your styles at the end of it.

@stef-k Yep!

**Comment by robertandrews** [comment]
@stef-k SCSS/NPM/Gulp... compiling CSS... these are things I'm just not going to get my head around for a while. I'll have to fix that.

@holger1411 "Enqueue an additional css file via functions.php in your Child theme or modify the css/child-theme.min.css and add your styles at the end of it." So, I would make an "understraps-child" theme (with a "styles.css, obviously"), put a "css" directory in that, and then "somefile.(mid.)css" in that, enqueued?

Wonder what I'd really be missing by enqueuing `https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css` **instead** of `'get_stylesheet_directory_uri() . '/css/theme.min.css''`, or otherwise just using your HTML markup. Nothing about the markup that is SASS-dependent?

Thanks for trying.

**Comment by holger1411** [comment]
@robertandrews: The UnderStrap Child Theme (here: https://github.com/holger1411/understrap-child) comes already with an /css folder and a theme.min.css in it.
You can add a separate file into it and enqueue it in your functions.php (cleaner way but need some work) or add you changes right at the end of the exisitng theme.min.css (quick and dirty way because you are not separating the UnderStrap/Bootstrap etc. styles from your changes, but you don´t need to do any extra stuff. Just add your CSS.).

The theme.min.css file includes already Bootstrap 4 Alpha 5, plus Font Awesome, some styles from Underscores and some basic UnderStrap styling.
Adding bootstrap.min.css a second time is unnecessary.
