### ISSUE TITLE
Insert gulp-autoprefixer to gulpfile.js

### ISSUE THREAD

**Issue by conlaccento** [holger1411/understrap#169]
Hello everyone! Anyone can help me to add autoprefixer to my project?
I just installed gulp-autoprefixer via npm and it appears in package.json as a dependencies, but if I try to add a pipe in gulpfile.js to autoprefix the css nothing change. I try to insert it in different place, no results.
Sorry, I'm not an expert! Thanks a lot!

**Comment by stef-k** [comment]
Hi, i'll post the procedure here so you can check what you are missing.

1. install gulp autoprefixer for development `npm install --save-dev gulp-autoprefixer`
1. open `gulpfile.js`  and add `var autoprefixer = require('gulp-autoprefixer');` 
1. find the `sass` task and and the following (after the `.pipe(sass()):

```js
        // auto prefix and keep last two browser versions
        .pipe(autoprefixer('last 2 version'))
```

To test it:

1. run `gulp copy-assets` and `gulp watch`
1. open `sass/theme/_theme.scss` and add:

```scss
a {
  display: flex;
}
```

open `css/theme.css` , you must see:

```css
a {
  display: -ms-flexbox;
  display: flex; }
```

using the setup above, you support the last 2 browser versions as documented at [can i use](http://caniuse.com/)

@holger1411 perhaps we should add autoprefixer support with 2 browser versions (current + current -1).

waiting for feedback, cheers.

**Comment by holger1411** [comment]
@stef-k & @conlaccento : How does the autoprefixer reacts if there are already prefixes in your SASS in use? For example what happends if you run it, with the .scss Bootstrap files?

**Comment by stef-k** [comment]
I am not sure, you could test it if you have time or we could state in gulpfile which sources to ignore I guess...

**Comment by holger1411** [comment]
I don´t think we should add it in general/global.
If you start the watch task and you don´t know that there is a prefixer plugin in use it can cause a lot of trouble. And if you don´ needed you need to add your own files to the ignore list.

So the basic UnderStrap gulpfile should include basic tasks for a general workflow only. But don´t know where we should draw the line...

**Comment by stef-k** [comment]
it propably does not have any issues with already prefixed rules but to be sure it needs some testing. If this is the case then I do not see any integration problems.

I'll try to run in again (when the time permits...) in a new branch and check the results.

**Comment by conlaccento** [comment]
Thanks a lot for your help! I will test it and try to help about your doubt.

**Comment by crdil** [comment]
Cssnano supports autoprefixing, I use it in the following way in the gulpfile.

```
...
var supported = [
  'last 2 versions',
  'safari >= 8',
  'ie >= 10',
  'ff >= 20',
  'ios 6',
  'android 4'
];
...
gulp.task('cssnano', ['cleancss'], function() {
  return gulp.src('./css/*.css')
    .pipe(sourcemaps.init({
      loadMaps: true
    }))
    .pipe(plumber())
    .pipe(rename({
      suffix: '.min'
    }))
    .pipe(cssnano({
      autoprefixer: {browsers: supported, add: true},
      discardComments: {
        removeAll: true
      }
    }))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./css/'))
    .pipe(reload({
      stream: true
    }));
});
...
```

**Comment by drewpyd85** [comment]
@stef-k This method works perfectly, might I add you need to add the ".pipe(autoprefixer('last 2 version'))" 3 separate times following each instance of .pipe(sass()).

Also removed the last 2 versions to include webkit auto-prefix.

As for scss files that are already auto-prefixed, it does not affect them from what I've seen so far. Thank you!

**Comment by stef-k** [comment]
hi, the **last 2 version** parameter is optional stating how many versions you want to support using prefixes.

I am glad this have worked out for you.

regards...

**Comment by stef-k** [comment]
perhaps this issue needs to close as resolved

**Comment by holger1411** [comment]
okay;-)
