### ISSUE TITLE
Can't compile theme.scss to the CSS file (Using Codekit)

### ISSUE THREAD

**Issue by justinmarkfarrugia** [holger1411/understrap#170]
Hey!
Apologies if this may seem like a beginner-type question but I've been trying to use CodeKit with your project (props btw, really appreciate the commenting) and once I try to import external scss files that weren't in the install there seems to be a problem with /sass/bootstrap/custom as shown in the screenshot.
![screen shot 2016-12-04 at 10 45 48 pm](https://cloud.githubusercontent.com/assets/13674072/20869505/d3c2eebe-ba73-11e6-8e0a-6baae3a8acd7.png)

Now I noticed that you have a gulpfile and looked through it a bit and noticed that I probably don't even need CodeKit. So the problem might have been some conflict with CodeKit itself. I was wondering as to what gulp task should I be running on iTerm to be able to compile my SASS and have browsersync up and running at the same time. 

Cheers!

**Comment by holger1411** [comment]
Hi @justinmarkfarrugia!
 
You need to run
`npm install`
followed by
`gulp copy-assets`
in your terminal to download all dependencies and move them to the /src folder.
See docs here: https://understrap.github.io/#developing

Than CodeKit should find anything needed.
But you can stay in your terminal and run:
`gulp watch`
Every scss change will start the css compiling task in the background than and you can work on without CodeKit.

**Comment by justinmarkfarrugia** [comment]
Thanks so much @holger1411 , appreciate the effort you're putting into Understrap 👍

**Comment by kick-point** [comment]
Hi @holger1411 — Are you aware of any compatibility breakdowns with npm? (v. 6.11.3) [also node 12.11.0] on a MacBook running Catalina. 🙄

npm seems not to install correctly — lots of install errors related to gyp and gulp-sass which isn't installed as it should be.
