### ISSUE TITLE
vertical-one-page.js conflicts with bootstrap's collapse, carousels, and dropdowns

### ISSUE THREAD

**Issue by s3613032** [holger1411/understrap#171]
If this feature is enabled the above mentioned bootstrap features will stop working

**Comment by holger1411** [comment]
Thx for reporting.
I pass this to @stef-k , the developer of this feature.
@stef-k:  Seems there is a problem with: https://github.com/holger1411/understrap/blob/master/js/vertical-one-page.js in some way conflicting the bs js files.

**Comment by stef-k** [comment]
will check it

**Comment by stef-k** [comment]
I am leaving this open for a while to get a confirmation from @s3613032 

I've tested though with collapse, dropdown and carousel and all worked fine after the fix.

**Comment by s3613032** [comment]
splendid, thanks for that @stef-k & @holger1411 It works now
