### ISSUE TITLE
vertical-one-page.js breaks anchor links on custom page template, redirects to homepage

### ISSUE THREAD

**Issue by willgorham** [holger1411/understrap#175]
I haven't done quite enough testing to figure out why this is happening, but here's what I'm noticing:

I have created a custom page template in my 'understrap-child' theme (page_products.php). The URL of a page using this template looks like, for example: https://example.com/products/. When I add an anchor to another part of the page ```<a href="#plans">Plans</a>``` to link to ```<p id="plans">```, the page scrolls to this paragraph, and then redirects to https://example.com/#plans

**Comment by stef-k** [comment]
Hi, please checkout the latest code and try again.

**Comment by willgorham** [comment]
This solves the problem if the anchor link in in the page content, but only because your selector doesn't select those links anymore. If the link is in the main menu (where your new selector is focused) the same issue occurs

**Comment by willgorham** [comment]
```
if ( currentPage === blogPage || vars.isSingle ) {
  target = $(this);
  target = vars.homeUrl + '/' + target[0].hash;
  location = target;
}
```

Why are we setting the target to $(this) and then immediately resetting it to something different? Should it not be just setting the target to the current URL plus the hash (not homeUrl)?

**Comment by stef-k** [comment]
Yes, the code listens for click events in menu so it can scroll down to each section.

Currently there is not a way to separate  the behavior for the one page navigation vs external/another page nagivation.

I can think one or two methods, such as:

1.  add a custom CSS class to menu links and track it from JS
1. pass to JS which links you want to track for scrolling and handle the behavior accordingly

**Comment by willgorham** [comment]
I'll submit a patch for this when I get the chance (unless someone beats me to it)

**Comment by willgorham** [comment]
Is there any consideration of having a theme options panel? That way someone could opt in to one-page navigation (along with other things). I think having this enabled by default loads up an unnecessary JS file that most people won't be using.

**Comment by stef-k** [comment]
The script loads when the vertical page template is used or in single posts or if blog is the front page, in order to handle the primary site (vertical template) with an additional blog in a different template. 

Yes it adds some overhead but saves the end user from having to select the vertical template and enable script's inclusion from the customizer. It is possible though but needs time which unfortunately I don't have much these days.

Additionally all JS sources should be concatenated to one file which unfortunately are not for the time being.

You could submit a PR though.
Thanks for your input!

**Comment by holger1411** [comment]
Hi!
I removed the vertical-one-page template and its function /JS from the master branch and add it to an extra feature branch:
https://github.com/holger1411/understrap/tree/vertical-one-page

It is a cool feature but it breaks some default browser behavior for everyone, even if the functions isn´t used. 
There are a lot of support request (including mail / wordpress.org forums etc.) regarding scrolling, Tabs, sliders etc. which arent working properly. And it seems that most of them are related to this script.

@stef-k:  I put it in "quarantine" into this feature branch as long as no one have time to fix it. So your cool work isnt lost and we can merge it back.
