### ISSUE TITLE
Hero Slider - Featured Posts

### ISSUE THREAD

**Issue by patchpony** [holger1411/understrap#178]
Is there a tutorial somewhere that could tell me how to make a featured post carousel with the owl slider provided by the understrap theme?
I tried using the custom group post widget in the slider however it lists the custom posts vertically rather than showing them horizontally on slide.

thanks

**Comment by holger1411** [comment]
Hi!
Thats the link to the slider description: https://github.com/holger1411/understrap#how-to-use-the-build-in-widget-slider
Just place more than one widget on the widget position "Hero Slider"

**Comment by patchpony** [comment]
is there not a cleaner way to just show posts I want to show than adding Xamount of widgets with slightly different selection?  For instance, right now if I put two widgets of posts from certain category it always brings the same post on each slide.  
Id like to slide through 3 different posts as featured posts.

**Comment by holger1411** [comment]
No, sorry.  Its a widget slider, not a post´s slider.

**Comment by Thomas-A-Reinert** [comment]
Suggestion : use the static hero and any plugin/widget that does what you want to achieve. There are lots of these available.
