### ISSUE TITLE
Content templates using <h2> tags instead of <h1>

### ISSUE THREAD

**Issue by coldfusion411** [holger1411/understrap#179]
On-page SEO typically calls for their to be at least one `<h1>` tag present within `<article>`

**Comment by holger1411** [comment]
Yes, you are right.
It makes sense in single content item´s without looped articles (like page, single etc.)
Changed it here:
https://github.com/holger1411/understrap/commit/9112bc49dfde0468f9e1e80095c7c13dfc7235cb

**Comment by holger1411** [comment]
Thx @coldfusion411  for your help, by the way!
