### ISSUE TITLE
Purpose for /inc/scripts.php

### ISSUE THREAD

**Issue by robwilde** [holger1411/understrap#18]
found /inc/scripts.php which appears to be similar to /inc/enqueue.php but not included in the calls in the functions.php. Is there a purpose for this file or is it an orphaned file?

Thanks for an awesome template. Would love to see addition of  autoprefixer to gulp tasks. I have added to my recent project, can offer pull request of my gulpfile and package.json if it helps.

**Comment by holger1411** [comment]
Hi!
Jup, its an relic from the _s theme and was replaces by the enqueue.php filr (but not removed from the repo...)
Thanks for the hint!
Will remove it

**Comment by robwilde** [comment]
Awesome glad I could help and thank you for and Awesome theme template.

Is there any plan, or is a good idea, to use JShint or JSlint  to uglify the JS to one file?

Thanks
Robert Wilde
[RobertWilde_120]
Technology Consultant
www.WildeTech.com.au<http://t.signauxdeux.com/link?url=http%3a%2f%2fwww.wildetech.com.au%2f&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAgJv82NQJDA&k=815ed919eadc4981871a4e4a62b0a8e4>

skype :  mrwilde<skype:mrwilde?chat>
phone:  07 3102 3809
mobie:  04 3886 3809

**Comment by holger1411** [comment]
Depends. Some JS files are used just in certain cases. For example the Slider script is just called if the slider is active. If you add it into one minified script you have to change this in enqueue.php line 29...

But it was developed with "less bytes possible" in mind while "less requests as possible" is the way to go...so yes: It is a good idea.

Another user posts a new gulpfile (according to this issue:; https://github.com/holger1411/understrap/issues/16#issuecomment-197886700)

I´am checking it out, currently

It will also concat all js files into one minified theme.min.js file

**Comment by holger1411** [comment]
I add a "gulp scripts" task to gulpfile.js. It concats and uglifies all JS files (Including jQuery & Bootstrap) into one file called theme.min.js.
And:
The theme unloads the WP default jQuery in the enqueue.php, and loads the minifed "all-in-one" JS file in the footer. 
So the theme itself (besides the WP Core stuff) just do two requests now: theme.min.css and theme.min.js

**Comment by robwilde** [comment]
Awesome, thanks for the update.

Thanks
Robert Wilde
[RobertWilde_120]
Technology Consultant
www.WildeTech.com.au<http://t.signauxdeux.com/link?url=http%3a%2f%2fwww.wildetech.com.au%2f&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAgJv82NQJDA&k=815ed919eadc4981871a4e4a62b0a8e4>

skype :  mrwilde<skype:mrwilde?chat>
phone:  07 3102 3809
mobie:  04 3886 3809
