### ISSUE TITLE
Bootstrap formatting lost on country change in checkout.

### ISSUE THREAD

**Issue by Jalpo** [holger1411/understrap#187]
/inc/woocommerce.php
`case 'state' :`
Does not work if no states for country, or if 'country' changed.

On country change replaced by https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/country-select.js

override country-select.js?

**Comment by stef-k** [comment]
Hi, yes

this override must be done in JS. It is the 137 line number in `country-select.js` source file.

```js
$statebox.replaceWith( '<input type="text" class="input-text" name="' + input_name + '" id="' + input_id + '" placeholder="' + placeholder + '" />' );
```

**Comment by Jalpo** [comment]
```
add_action('wp_enqueue_scripts', 'override_wc_country_select');
function override_wc_country_select() {
	wp_deregister_script('wc-country-select');
	wp_enqueue_script('wc-country-select', get_template_directory_uri() . '/woocommerce/js/country-select.js', array('jquery'), null, true);
}
```
to override country-select.js. 
137, & I think line 123 for when change back to a country with states.
but still issue on page load if default country has no states. will take another look when I get a mo.

**Comment by Jalpo** [comment]
what about something like this?
`				case 'state' :			
					/* Get Country */
					$country_key = 'billing_state' === $key ? 'billing_country' : 'shipping_country';
					$current_cc  = WC()->checkout->get_value( $country_key );
					$states      = WC()->countries->get_states( $current_cc );
					if ( is_array( $states ) ) {
						//select classes - isn't this overwritten anyway?
						$args['class'][] = 'form-group';
						$args['input_class']       = array( '', 'input-lg' );
						$args['label_class']       = array( 'control-label' );
						$args['custom_attributes'] = array(
								'data-plugin'      => 'select2',
								'data-allow-clear' => 'true',
								'aria-hidden'      => 'true',
						);
						break;			
					} else {
						//style text input if no states
						$args['class'][]     = 'form-group';
						$args['input_class'] = array( 'form-control', 'input-lg' );
						$args['label_class'] = array( 'control-label' );
						$args['custom_attributes'] = array(
								'data-plugin'      => 'select2',
								'data-allow-clear' => 'true',
								'aria-hidden'      => 'true',
						);
						break;
					}`

adds style to text input if no states for default/customer country.

**Comment by stef-k** [comment]
The problem is not in PHP and select2. 

If there is no state, select2 is being hidden and an input text field is being shown. This control needs to have Bootstrap styling.

**Comment by Jalpo** [comment]
OK. I can see how country-select.js controls this on change, but if it starts with no states can't see how that is working, must be missing something.

**Comment by holger1411** [comment]
Cloe this. Seems to work now, right?
