### ISSUE TITLE
Dockerize theme's development

### ISSUE THREAD

**Issue by andres99x** [holger1411/understrap#189]
I have been experimenting with Understrap for a while now, and i have setup a docker environment for development.

Basically this loads a clean Wordpress and a MySQL instance and installs the theme so that you can start developing the theme right away without any special setup, just [Docker](http://www.docker.com). It's really makes it easy for development since there are no needs for environment setup, and we avoid any dependencies issues, since we would all be using the same version of PHP, Wordpress, etc...

Would you be interested in this setup?

**Comment by saknopper** [comment]
I would be...

I've been thinking about setting this up using docker, but never really had the time to actually do it. Do you use the official wordpress docker image as a starting point?

**Comment by andres99x** [comment]
Great! 
Yes, i'm currently using the [Official Wordpress Image](https://hub.docker.com/_/wordpress/).
I'll prepare it and create the PR for you to review it.

**Comment by saknopper** [comment]
Thanks!

I can review it, but I can't accept it since I'm not the maintainer of this project :)

**Comment by holger1411** [comment]
Hi!
Can´t add it to the UnderStrap repo itself because not everyone needs it and it is not part of the theme itself. 
But feel free to create your own repo and I will link to it / credit it.

**Comment by lonix1** [comment]
Is there a link to the dockerized setup?

**Comment by pattonwebz** [comment]
@lonix1 I don't think anyone ever made one for this project specifically however there are a good number of general purpose WP docker setups available and lots of articles about them to help you out. A tool called `docker-compose` is really useful for holding individual setups or configs so when you search keep an eye out for the compose files in the articles. Those are mostly copy/paste :)

**Comment by lonix1** [comment]
@pattonwebz Thanks for the feedback. I use docker heavily which is why I asked about this :)

But there aren't dockerized themes readily available which are as up to date as this one. It's a pity as my entire infrastructure is dockerized, except for the theme which requires lots of manual effort.

**Comment by pattonwebz** [comment]
Well it sounds like you and I have a few things in common. I also am trying to dockerize everything :)

Right now I mount in my themes from the host with volume mounts and it's not ideal. I don't know of a better method though. If a theme were to include dockerized setup in their repo how do you think that might work? Would it just be a compose file with suggested volume mounts and base images? Is there other things you think it would need?

I guess a custom WP image (or separate images) for build tooling would be useful. Currently I tend to run things like `gulp`/`webpack` on the host directly, maybe a container specifically for those tools would be useful?

**Comment by lonix1** [comment]
I mount the theme as `.../wp-content/themes/foo`. But there's lots of fiddling after that because of permissions.

I'm not sure what would be a better way. The only alternative would be to hard bake the theme into a `Dockerfile` but I think that allows for less flexibility, so I use the bind mount instead.

An "official" solution may well be just the above, but auto-generated for every release.

**Comment by lonix1** [comment]
@pattonwebz BTW how do you deal with permissions? I discovered that the wordpress image uses uid/gid 82 for `www-data`. So I set that for the theme files on the host.

But that doesn't translate to similar permissions in the container (even though it should), and just sets root for all those files. So I created a bootstrapping script that does that manually on every container start.

Did you find a simpler way by any chance?
