### ISSUE TITLE
missing definition in custom-comments

### ISSUE THREAD

**Issue by robwilde** [holger1411/understrap#19]
Bottom of the file in the below function.
$req not defined. Was defined in previous function but not this one, getting PHP Notice.

`     function bootstrap3_comment_form( $args ) {
    $args['comment_field'] = '<div class="form-group comment-form-comment">
    <label for="comment">' . _x( 'Comment', 'noun', 'dford' ) . ( $req ? ' <span class="required">*</span>' : '' ) . '</label>
    <textarea class="form-control" id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea>
    </div>';
    return $args;
    }`

Hope that helps

**Comment by holger1411** [comment]
Hi! Thx for reporting.
Was already fixed, maybe you use an older version? The bootstrap3_comment_form function just don´t utilize the $req anymore

Or do you still have this issue with UnderStrap 0.3.8?
