### ISSUE TITLE
Error css child theme

### ISSUE THREAD

**Issue by ztvMark** [holger1411/understrap#192]
Cuando creo un theme hijo no carga el css por esta funcion get_stylesheet_directory_uri() deberia ser 
get_template_directory_uri()

Ejemplo de theme hijo
`add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array('parent-style')
    );

}`

Recomiendo cambiar en enqueue.php

`$the_theme = wp_get_theme();
		if ($the_theme == 'Understrap') {
			wp_enqueue_style( 'understrap-styles', get_stylesheet_directory_uri() . '/css/theme.min.css', array(), $the_theme->get( 'Version' ) );
		}
		else{
			wp_enqueue_style( 'understrap-styles', get_template_directory_uri() . '/css/theme.min.css', array(), $the_theme->get( 'Version' ) );
		}`

o solo remplazar
`wp_enqueue_style( 'understrap-styles', get_template_directory_uri() . '/css/theme.min.css', array(), $the_theme->get( 'Version' ) );`

**Comment by holger1411** [comment]
Hi!
No, the Child theme did not load any styles from the parent theme. And that´s how it should be
It pulls the parent themes dependencies via npm and regenerate it´s styles by its own into its own css file as soon as you compile the SASS files.
