### ISSUE TITLE
Translation issue on woocomerce cart.php

### ISSUE THREAD

**Issue by Parcye** [holger1411/understrap#193]
I have been puzzled on why my cart was still in English; after searching around I noticed the followinglines in cart.php:
```
36				<th class="product-name"><?php _e( 'Product', 'understrap' ); ?></th>
37				<th class="product-price"><?php _e( 'Price', 'understrap' ); ?></th>
38				<th class="product-quantity"><?php _e( 'Quantity', 'understrap' ); ?></th>
```
Product, Price and Quantity are not in the .pot file, nor in the .po / .mo file from understrap. This is causing the default string to be outputted.

**Comment by holger1411** [comment]
Hi @Parcye 
Thx for your feedback!
I generate a new understrap.pot file now with all (new) text strings in it (including the WooCommerce stuff):
https://github.com/holger1411/understrap/commit/fa4f10e586118781a210281698b2bdc2dfddfc65

**Comment by stef-k** [comment]
@holger1411 maybe we should open a new issue regarding translations updates

**Comment by holger1411** [comment]
Opened this one:
https://github.com/holger1411/understrap/issues/194
