### ISSUE TITLE
How to add javascript ?

### ISSUE THREAD

**Issue by ryanrahman26** [holger1411/understrap#198]
I want to add custom.js and jquery.easing.min.js but it not loaded.
i have been inspect it with firefox developer tools but nothing.

![3](https://cloud.githubusercontent.com/assets/20228877/21415585/d705e19e-c83d-11e6-8d30-8a87457d9202.png)

**Comment by holger1411** [comment]
Hi!
Please make sure you use a unique handle for each scripts.
Replace "understrap-scripts", for example, with "understrap-scripts-easing" for the jquery.easing.min.js and so on.

And make sure your clear your browser cache.

**Comment by ryanrahman26** [comment]
Hello.
It's already solved here [https://github.com/holger1411/understrap/issues/47](https://github.com/holger1411/understrap/issues/47)

I'm using gulp scripts, and it's loaded :)
