### ISSUE TITLE
Hero and static hero widgets not working

### ISSUE THREAD

**Issue by karlparton** [holger1411/understrap#2]
Installed theme locally. Am unable to display static or hero widgets.

**Comment by holger1411** [comment]
Thx for your feedback! 
It is important that you place at least two widgets on position "hero" to create that slider function. The script needs something to "slide to".

Another reason could be: The widget arears are just working on your blog frontpage. If you assign another (for example static page) as frontpage with another template the widget area will not appear.

If nothing works could you send me the markup of your website from the page where you expect the widget to appear? (just copy&past the HTML code after using the "view source" function of your browser...)

Thy in advanced!
Holger

**Comment by karlparton** [comment]
No problem. Thanks for the reply. I've managed to get static hero widget displaying. I was using a static page for my homepage.

Could you share how you structured the understrap.com homepage? (not the demo page) Is it one big post - for example? I'm assuming you used the Understrap theme.

Thanks again.

**Comment by holger1411** [comment]
Yes, I used the understrap theme. I just add a extra template file. Add the header.php, hero and footer.php to it. The rest, between of it, is hardcoded static HTML markup. I name it "frontpage.php" and select it as static frontpage. Thats it. Not very elegant but good for a "quick&dirty" onepager.
Maybe I will add such a template file in the future to the UnderStrap theme itself... Maybe with a content and/or widget area instead of hardcoded HTML...

**Comment by karlparton** [comment]
That makes sense. Yes - in the future a simple one pager template would be a good addition. I was looking for a simple one pager solution when I found UnderStrap. I'm beginning to understand the framework but struggling to make changes to the css or sass files. I can find the files and change them. For example I am changing the $brand-primary variable but the change is not reflected on my theme. I'm guessing I have to run something locally using the terminal to generate / out the css file? Am I missing something really obvious?

**Comment by holger1411** [comment]
Hi!
Yes, you need to compile the .scss files into .css locally.
I use Gulp (http://gulpjs.com/) to do that. A gulp file is part of this repository.
If you installed GULP and SASS (along with node) on your local machin you can simply run the command:
gulp sass
in your terminal in the themes directory and it will compile everything

But if you aren´t a terminal guy there are some GUI tools out there:
Check the list on the bottom left here:
http://sass-lang.com/install

A good free tool is Scout:
http://mhs.github.io/scout-app/
Available for Mac and PC

**Comment by sdscomputer** [comment]
can you please the front page setting of your demo pages
