### ISSUE TITLE
src Directory is missing

### ISSUE THREAD

**Issue by IamJoshing** [holger1411/understrap#200]
I just tried to setup a new theme with understrap and notice /src/ is missing.

**Comment by holger1411** [comment]
Pls run "npm install" first. Read more in readme

**Comment by IamJoshing** [comment]
I have tried that and installing everything each of the three ways.  I never get the /src/ files.  I feel like I am missing something simple.

**Comment by michelmany** [comment]
Try:
npm install
gulp copy-assets
gulp scripts

**Comment by IamJoshing** [comment]
That did it.

**Comment by holger1411** [comment]
Sorry, yes. With version 0.5.0 or older you need to run the "gulp copy-assets" task, too.
Since 0.5.1 (pre release) you just need to run "npm install"
