### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by TomKisielewski** [holger1411/understrap#202]
Hi Guys, Happy New Year!
I have some problems with installing understrap using npm. 

![understrapinstallfailure](https://cloud.githubusercontent.com/assets/8680052/21580691/614c3764-d003-11e6-8e0c-2336476d5158.png)

I have recently switched to linux mint and set up all from scratch. Everything is installed properly (npm and node ) ,I thinks so... .Any advise would be helpful. I attach npm-debug.
Many Thanks
Tomasz
[npm-debug.pdf](https://github.com/holger1411/understrap/files/679953/npm-debug.pdf)

**Comment by holger1411** [comment]
Hi!

You need to install gulp cli globally, too. 
Especially on a new computer its not there by default.

The package.json runs the gulp task "gulp copy-assets" at the end of the install process to move any needed files into the right folders.
While "npm install" installs gulp itself to the understrap folder to run from there you need to install the gulp command line interface systemwide on your computer, too.

Just run:
`npm install --global gulp-cli`
once.

than the "gulp" command is available systemwide.

**Comment by TomKisielewski** [comment]
Thanks, it works now
