### ISSUE TITLE
Owl Carousel FadeOut transition not working

### ISSUE THREAD

**Issue by flyingchorse** [holger1411/understrap#204]
I have been pulling my hair out trying to get the Owl carousel to work with FadeOut animation instead of sliding.

When I was trying to figure where was going, you could see that the script was not adding the .animation class to the slide items, but I could not figure why it was not doing so. 

Anyway after much googling, I found a few people had some issues with other features of Owl when certain Options were set / not set. So I started to play about with the option. 

It turns out that when I went into [slider_settings.js](https://github.com/holger1411/understrap/blob/master/js/slider_settings.js) and replaced `understrap_slider_variables.items` with the number 1, the FadeOut started to work. So I dont know why that was affecting the function of the slider as when debugging the JS you could see that the `understrap_slider_variables.items` was evaluating to 1.

Hopefully someone who  knows what they are doing will make sense of all this :-)

**Comment by holger1411** [comment]
Hi!
Strange thing, I can reproduce it on the demo site.
For some reason it did not store the value (properly). 
But changing the value from 1 to 2 works, so the script is able to grap the number...

I will remove the dynamic value and replace it with 1.
