### ISSUE TITLE
Menu not showing? Please Help

### ISSUE THREAD

**Issue by Yoshuwa** [holger1411/understrap#207]
Hi there,
I'm excited to be using understrap but after installing it no menu is showing? 
I have 

`<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-toggleable-xs exCollapsingNavbar',
						'container_id'    => 'exCollapsingNavbar',
						'menu_class'      => 'nav navbar-nav',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>`

in header but still nothing is showing?
many thanks

**Comment by holger1411** [comment]
Hi!
Do you have published a menu on position "primary"?
Could you post a screenshot from your WP backend menu settings? (Appearance -> Menus)

**Comment by Yoshuwa** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/13898469/21740897/27f6838a-d4d0-11e6-8278-9746f25e0093.gif)

Hi yes i have set "menu primary" many thanks for your quick response

**Comment by holger1411** [comment]
Hm, it seems your theme provides a secondary and footer menu, too. UnderStrap just provides just one main menu. 
Which UnderStrap version do you use? And did you edit the parent theme or do you use a child theme?

If so make sure that your header.php looks like the one from the corresponding parent theme:
https://github.com/holger1411/understrap/blob/master/header.php

For example if you use UnderStrap 0.5.2 (the latest version from yesterday) make sure this portion is in your header.php of your custom child theme:
```
<!-- The WordPress Menu goes here -->
				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>
```

**Comment by Yoshuwa** [comment]
Well I paid for the latest UnderStarp 0.5.2  yesterday, Just saw UnderStarp update and I have updated it now everything is working well! Many thanks!!

**Comment by nuthinbutajthang** [comment]
Hi, I'm not sure if this is related, but when I installed the Understrap-Child 0.3.2 with the parent theme 0.6.5, the primary menu didn't show up. Then I realized that the child theme was not the latest, so I tried with 0.3.5 and it worked. Which makes me wonder if I had already customized the child theme, what could I have done?

**Comment by jauhari** [comment]
@holger1411  @Yoshuwa how to get extra Menu? I try to find out on **UnderStrap Parent Them**e but still no luck :(
