### ISSUE TITLE
Bootstrap Panel not working

### ISSUE THREAD

**Issue by hottehead** [holger1411/understrap#209]
The panel element is not properly styled. I copied the example from http://getbootstrap.com/components/#panels-heading

```
<div class="panel panel-default">
<div class="panel-heading">Panel heading without title</div>
<div class="panel-body">Panel content</div>
</div>
```

But the resulting panel has neither background color nor border. The same goes for wells and label components. Buttons (btn-default) do work correctly on the other hand. Anyone else experiencing this?

**Comment by Confectrician** [comment]
Hi,

Understrap is based on Bootstrap 4.

As you can see here -> https://v4-alpha.getbootstrap.com/migration/
the Bootstrap 3 Panels have been dropped in the Version 4 and were replaced by a new component called "Cards".

Maybe you will find a similar solution while working with the new cards element.

**Comment by stef-k** [comment]
The elements you reference are for Bootstrap 3.

You can find the new documentation at https://v4-alpha.getbootstrap.com/getting-started/introduction/

[Here](https://v4-alpha.getbootstrap.com/migration/) you can check the differences between v3 and v4.

**Comment by hottehead** [comment]
Thanks a lot for clarification and the helpful links! I should get my way around now.
