### ISSUE TITLE
Grid Column not getting set when using no sidebar

### ISSUE THREAD

**Issue by flyingchorse** [holger1411/understrap#210]
In the page.php file the call to [`get_template_part( 'global-templates/left-sidebar-check', 'none' );`](https://github.com/holger1411/understrap/blob/master/global-templates/left-sidebar-check.php) is not returning `<div class="col-md-12 content-area" id="primary">` so not setting the grid column and then skewing the padding. Im getting blog post text butting right up against the side of the viewport on mobile. I was going to start fudging about with the padding adding custom css, but thought this cant be right !

Should I attempt to fix this and if so how do I then get that back into this repository ? Using Git is all new to me.

**Comment by flyingchorse** [comment]
Looks like there needs to be another `elseif` statement to check if `get_theme_mod( 'understrap_sidebar_position' );` is set to `none`

**Comment by holger1411** [comment]
Can you post an URL?
Or a screenshot from the website + markup ?
That would help to recreate and fix the problem.

It works so far on normal pages like here:
https://understrap.com/understrap/?page_id=733

And: Do you run WooCommerce on your site?
We had a similar problem here:
https://github.com/holger1411/understrap/issues/177

**Comment by holger1411** [comment]
Ah, ok. It happens if you don´t use any sidebar...?

**Comment by holger1411** [comment]
Okay, I add this:
https://github.com/holger1411/understrap/commit/61948a6d15713301b3cc537c4b09f129155de99e

A else statment at the end that adds a col-md-12 sized container even if no sidebar nor WooCommerce is active

**Comment by holger1411** [comment]
Download this file:
https://github.com/holger1411/understrap/blob/master/global-templates/left-sidebar-check.php
and replace the corresponding file of your tehme with it.

**Comment by flyingchorse** [comment]
Yes that's it if you don't use any sidebar.

**Comment by flyingchorse** [comment]
If you have added it in  I can just Pull down from repository yes ? Say for example the fix I made I wanted to contribute back, how do I do that? Do I just push it back and then you have the ability to accept / reject ?

**Comment by holger1411** [comment]
You can fork this project, than edit/add your stuff and than start a pull request to merge your changes back into this project.

**Comment by VesterDe** [comment]
This link may help with that:

https://yangsu.github.io/pull-request-tutorial/
ᐧ

------------------------------------------------------------------------
Demjan Vester: LINKED-IN <http://si.linkedin.com/in/vesterde/>
Phone: +386 (0)40 193 536

**Comment by holger1411** [comment]
Close this because of: https://github.com/holger1411/understrap/commit/61948a6d15713301b3cc537c4b09f129155de99e
