### ISSUE TITLE
Grid system not working on loop/content-grid.php

### ISSUE THREAD

**Issue by mherrera1987** [holger1411/understrap#211]
Grid system is not working on my website ->http://i.imgur.com/0fyxtPy.jpg

I tried by selecting grid of 2, 3 or 4 columns

**Comment by holger1411** [comment]
Can confirm this. Might be a problem by switching to "flex-box: on" mode sinde Bootstrap 4 Alpha 6?
Do you have time to look at this @stef-k ?

**Comment by stef-k** [comment]
I'll give it  a try.

**Comment by stef-k** [comment]
Well unfortunately this is related to the recent update and move to only flexbox layout system.

For the moment, I cannot think any solution to support this situation. Same but B4 is still in alpha...

From the issue tracker I've read that they are preparing the first beta release (https://github.com/twbs/bootstrap/issues/21568). 

We could wait for things to stabilize more before deciding on how to proceed. Additionaly I would wait for this issue https://github.com/twbs/bootstrap/issues/20321 to be resolved.

**Comment by typeplus** [comment]
I bet you holger just loves you posting a warez site   on his git project 😠

**Comment by holger1411** [comment]
@typeplus 👍 

I removed that feature into a feature branch:
https://github.com/holger1411/understrap/tree/posts_index_style
till we have a solution.
