### ISSUE TITLE
How to install and use previous version (0.5.1)

### ISSUE THREAD

**Issue by typeplus** [holger1411/understrap#212]
Sorry I don't think this is a bug but I am unable to install a previous version (0.5.1) without having bootstrap alpha .6 remnants remain.

I have to revert to alpha .5 and hence 0.5.1 as the major changes to the nav and the flexbox just borks my current project. (for laughs have a look at the woocommerce checkout page flex col-1 for 8.3% width ... weird!).

When I go back and install 0.5.1 via;

`npm install understrap@0.5.1`
or via the github download and manual extract to my themes folder

I get the message;

`Error: File to import not found or unreadable: ../../src/sass/bootstrap4/animation.` as far as I am aware from reading a previous ticket this is due to alpha .6 no longer having the animation or tags scss files.

The package.json shows `"dependencies": { "bootstrap": "^4.0.0-alpha.5",` and the `src/sass/bootstrap4/bootstrap.scss` shows alpha.6 Is this an npm issue? 

Thanks for reading and sorry for any trouble as it's likely my fault here.

T+

**Comment by holger1411** [comment]
with npm install you just install the dependencies.
So in your case you use UnderStrap 0.5.2 but installed the dependencies for 0.5.1.
Because 0.5.2 used Bootstrap 4 Alpha 6 and 0.5.1 used Alpha 5 both are incompatible.

Just donwload the 0.5.1 release from here:
https://github.com/holger1411/understrap/releases

extract it to your local HDD and then run:
`npm install`
inside this folder via your terminal and you should be good to go

**Comment by typeplus** [comment]
Thats what I tried as well Holger! (download from github `npm install` from the understrap folder then `gulp copy-assets`. For whatever reason it is still installing bootstrap alpha.6 even for version 0.5.1. 

I tried globally removing the bootstrap4 npm package via `npm uninstall -g bootstrap@4.0.0-alpha.6 ` and then doing an npm install from a newly extracted 0.5.1 git release but the same thing. The package.json shows alpha .5 but the actual src folder is defintely alpha .6

**Comment by typeplus** [comment]
`npm uninstall bootstrap@4.0.0-alpha.6`  from the understrap directory then npm install `npm install bootstrap@4.0.0-alpha.5` and finally `gulp copy-assets` seems to add the proper bootstrap alpha.5 src files for the 0.5.1 release.... i think : )

**Comment by Parcye** [comment]
This was spot on for me, thank you!

**Comment by typeplus** [comment]
Just going to close so Holger doesnt have to.
