### ISSUE TITLE
Question: Integration with WooCommerce

### ISSUE THREAD

**Issue by ChrisChiera** [holger1411/understrap#215]
See there is WooCommerce integration, however wondering if that is simply adding the required add_theme_support( 'woocommerce' ); or if to the extent of a theme such as Storefront?

Understrap looks like a great alternative to customizing underscores to use the Bootstrap framework for typical WordPress custom themes. But for building a custom WordPress WooCommerce theme for projects (that will not be resold), would it be better to start with understrap and add any necessary WooCommerce specific functionality, or start with Storefront and add Bootstrap framework functionality? Thanks for creating this project.

**Comment by stef-k** [comment]
Hi, Understrap currently provides advanced WooCommerce support.

There are two ways for themes to provide support for WooCommerce:

1. by adding a `woocommerce.php` file
2. by adding various woocommerce template files and overriding them

Understrap does this by using the second method which is more fine grained. You can check which parts of WooCommerce currently are modified by browsing the woocommerce directory here: https://github.com/holger1411/understrap/tree/master/woocommerce

Hope that this answers your question.

**Comment by typeplus** [comment]
@stef-k stef-k is way more advanced than me but I find the easiest way is to check woocommerce directly via the dash;

`Woocommerce > System Status > Templates` and this will list all overrides and their paths. You will likely need to override all sorts of things for Woo and its as easy as copying them over from the Woocommerce plugin directory into the same hierarchy created under your /woocommerce dir. 

I was going to do the same as I was fond of the drop-down cart integration in storefront but I was able to get the same functionality myself. Hit me up if you want a copy.

**Comment by stef-k** [comment]
Yes this is also an option to check what is being overriden, I myself use the developer suit plugin which tells me at runtime what templates being rendered for each page like the following:

![selection_001](https://cloud.githubusercontent.com/assets/5731388/21962039/07047a98-db23-11e6-8682-58f996aa1fc4.jpg)

As for the dropdown you can always submit a pull request, help is always welcomed here by all, thanks.

**Comment by ChrisChiera** [comment]
Thank you all for that helpful information. Sounds like understrap in regards to woocommerce does add more than simply support for the plugin, but templates to work off of like Storefront, so I'll give Understrap a go first since. Thank you!
