### ISSUE TITLE
Hero Slide with Page on Home Page - Wordpress

### ISSUE THREAD

**Issue by ricardoteixxeira** [holger1411/understrap#216]
When I choose a page on the home page, I lose the Hero Slide or Hero Static. How can I fix this? If I choose a blog on the home page, the hero slide return to normal.

**Comment by holger1411** [comment]
Hi!
Check out this line:
https://github.com/holger1411/understrap/blob/master/index.php#L20

`<?php if ( is_front_page() && is_home() ) : ?>`

You could remove` && is_home()` if you want to display to slider on a frontpage which is not a post page.

**Comment by ricardoteixxeira** [comment]
Hi! I have already remove de code "&& is_home()" from the line. But nothing happens

**Comment by drewpyd85** [comment]
Im having the same issue, when my home page is set to "static page" the hero slider disappears. 

Even with the removal of && is_home() from the index.php is does not work.

Anybody have a solution for this? Thanks in advance

**Comment by holger1411** [comment]
Sorry, my fault.
If you use a page as frontpage WP uses the page.php file, not index.php.
But there is no call for the hero area in page.php.

Add this:
```
<?php if ( is_front_page() ) : ?>
	<?php get_template_part( 'global-templates/hero', 'none' ); ?>
<?php endif; ?>
```
to line 19 of your page.php file. Right above the beginning `<div class="wrapper" id="page-wrapper">`

**Comment by holger1411** [comment]
Let me know if it works for you. Will test it, too.
If it works I will implement it as default

**Comment by drewpyd85** [comment]
@holger1411 putting it on the page.php did not work for me, but putting it on the individual template I was using did. 

Thank you so much for your help and all your hard work.

**Comment by jollyfuk** [comment]
@holger1411
It worked well!. Thank you so much!

**Comment by justme101** [comment]
trying to get the slider to show on the 'front' page. read the comments from above with the php snippits to add. also read the comments from here: https://github.com/understrap/understrap/issues/457 . I did make a seperate templete named: front-page.php (basicly copied the page templete) but nothing is working. I am using  (Version: 0.8.0) this is the same on WP.org Any help would be appreciated. just a novice here.

**Comment by jdsaraiva** [comment]
Images don't show and I also have this JS error:
bootstrap.min.js?ver=2.9:6 Uncaught TypeError: Cannot read property 'offsetWidth' of undefined

I selected the images on the Hero widget and loaded the hero widget, no success. 
Any help is appreciated, thanks.
