### ISSUE TITLE
script and styles from CDNs

### ISSUE THREAD

**Issue by alwaysalready** [holger1411/understrap#217]
Not an urgent question at all, but what's the advice on using scripts and styles from CDNs with Understrap, and WP themes more generally? As an example, I'm trying jquery hosted by [Google](https://developers.google.com/speed/libraries/#jquery) instead of the file stored on my WP server.

If anyone else is doing this, any best practice advice for deregistering jquery and then registering and enqueuing the CDN version?

Thanks
Alex

**Comment by holger1411** [comment]
A bit old but still the default:
