### ISSUE TITLE
Rewrite your broken it's

### ISSUE THREAD

**Issue by mikeritter** [holger1411/understrap#220]
A note  on grammar:

I'll try to go through and fix what's in here, but watch for proper use of "its" and "it's".

<dl>
<dt>its<dt>
<dd>shows posession: <q>Hard work is its own reward.</q></dd>
<dt>it's</dt>
<dd>conjunction of it and is: <q>It's a good day to die.</q></dd>
</dl>

**Comment by holger1411** [comment]
Thx @mikeritter!
PR was merged: https://github.com/holger1411/understrap/pull/221
