### ISSUE TITLE
Add another node_modules to use in child theme

### ISSUE THREAD

**Issue by indrawanadjie** [holger1411/understrap#225]
I use understrap-child for develop.

Iam really confused:

1. After `npm install magnific-popup`
2. I add 
```
// Copy Magnific-popup JS files
    gulp.src(basePaths.node + 'magnific-popup/dist/*.js')
        .pipe(gulp.dest(basePaths.dev + '/js'));

// Copy Tether JS files
    gulp.src(basePaths.node + 'tether/dist/js/*.js')
        .pipe(gulp.dest(basePaths.dev + '/js'));

```
In gulpfile.js

3. I see that css and js, has copy in src folder.

So, my question is. How i can use or get that(magnific-popup) css and js? 

Thanks before 👍

**Comment by stef-k** [comment]
Hi, there is no support for this in Understrap but I have a branch that uses it for generating galleries with lightbox from posts.

Check here https://github.com/stef-k/understrap/tree/modific-popup

**Comment by indrawanadjie** [comment]
Thanks, so how i use it?

**Comment by stef-k** [comment]
You can check the code for details...

**Comment by holger1411** [comment]
@indrawanadjie If you add the JS to the gulpfile makes sure you run:
`gulp scripts`
after it to compile your new JS into the theme.min.js which will be loaded.
