### ISSUE TITLE
H1 on Front Page

### ISSUE THREAD

**Issue by raisonon** [holger1411/understrap#226]
For site SEO it is ideal to have your site name as an H1 tag.

I achieve this by amending the header.php as follows:

	<?php if (is_front_page()) {
	    echo '<a class="navbar-brand" href="' . esc_url( home_url( '/' ) ) . '" title="' . esc_attr( get_bloginfo( "name", "display" ) ) . '" rel="home"><h1>Title</h1></a>';
	} else {
	    echo '<a class="navbar-brand" href="' . esc_url( home_url( '/' ) ); . '" title="' . esc_attr( get_bloginfo( "name", "display" ) ) . '" rel="home">Title</a>';

	} ?>

**Comment by holger1411** [comment]
Hi!
I followed your idea of adding a H1 here:
https://github.com/holger1411/understrap/commit/7148f4f7b7e4bb5b017132d9dc373c20cfc1fda9

but using the Bootstrap 4 markup from here:
https://v4-alpha.getbootstrap.com/components/navbar/#brand
to keep the layout aligned with the BS4

**Comment by raisonon** [comment]
Not sure about is_home() - this will be true if not the home page but if the site template is a blog. Eg. if you have your blog posts at domain.com/blog/

**Comment by holger1411** [comment]
Thats why I use:
`<?php if ( is_front_page() && is_home() ) : ?>`
;-)

**Comment by raisonon** [comment]
Sorry if missing something - but in my circumstance (https://superscribe.co) when I don't have the blog template on the home page, surely that condition will be false because it requires it to be front_page and blog_template... Maybe just is_front_page() is enough?

**Comment by holger1411** [comment]
If you use a static page as homepage the page title itself is already a h1. So it makes sense not to use another h1 on a static front page for the brand/logo. 

Using the logo as h1 just makes sense if no other h1 is present. Thats just the case on a blogging frontpage.
For example on your site there is already:
`<h1>Email marketing for growing businesses.</h1> `

**Comment by raisonon** [comment]
Good point! Thanks for spotting that, will make that an H2 -- I was looking at logged_in version of home page. Cheers

**Comment by holger1411** [comment]
No problem! Thx for the initial idea/improvement!
