### ISSUE TITLE
Missing Tether after gulp copy-assets

### ISSUE THREAD

**Issue by 3cst4sy** [holger1411/understrap#227]
Hi,
when i run a clean install with `npm install`, the tether and jquery *.js-Files are missing in src/ .
Tether.js is a dependencies of bootstrap, but ignored by gulp copy-assets line: `gulp.src(basePaths.node + 'tether/dist/js/*.js')`

Can anybody check this issue?

Thanks

**Comment by holger1411** [comment]
Could you find this folder in your UnderStrap root: /node_modules/thether ?
Which UnderStrap version do you use?
Whats the error message?

And could you find this entry in your package.json:
`  "bootstrap": "^4.0.0-alpha.6",`
?

**Comment by 3cst4sy** [comment]
> Could you find this folder in your UnderStrap root: /node_modules/tether ?

No. Currently located at /node_modules/bootstrap/node_modules/tether

> Which UnderStrap version do you use?

master. but also occurs in 0.5.0 up to master

> Whats the error message?

No Errors in npm or gulp, but in the browser by bootstrap: `Uncaught Error: Bootstrap tooltips require Tether `
 
> And could you find this entry in your package.json:
> "bootstrap": "^4.0.0-alpha.6",

yes

root: /src/js doesn't hold any tether-js files

my Setup: NodeJS: 4.2.1 -  Windows 7 x64 - npm -v: 2.14.7

**Comment by holger1411** [comment]
Hm, strange. If I delete my /src folder and run:
`npm install`
It places a fresh copy of Tether into /node_modules/tether
Seems for some reason your npm handles dependencies of dependencies in antoher way.
See your version is 2.14.7....which is very old.
The latest version is 4.1.1

npm itself says "The version should be higher than 2.1.8."...

Pls try to update npm first

**Comment by 3cst4sy** [comment]
Updated my NodeJS to 6.9.4 and npm to 3.10.10

Now it's working. Thanks

Maybe add some engine dependencies to package.json ?

**Comment by holger1411** [comment]
Hi!
Yes, maybe its a good idea.
The problem is: I don´t know which the minimal node/npm version is you need...so its hard to give an advice in package.json...
