### ISSUE TITLE
Missing container and row class on sidebar-footerfull.php

### ISSUE THREAD

**Issue by NayeemNipun** [holger1411/understrap#228]
Hello,

I just tried to use your awesome starter theme - UnderStrap and found issue on sidebar-footerfull.php
When I added widgets from dashboard on Full Footer widget area all widgets were shown horizontally instead of showing vertically. Then I tried to find the problem and found the file sidebar-footerfull.php has no container and row class. That's why the problem occurred. 

I edited the file and now it works fine. 

Below is codes.

Your Code - 

`<div class="wrapper" id="wrapper-footer-full">

		<?php dynamic_sidebar( 'footerfull' ); ?>

	</div>`

My Edited Code - 

`<div class="wrapper" id="wrapper-footer-full">

		<div class="container-fluid">

			<div class="row">
	
				<?php dynamic_sidebar( 'footerfull' ); ?>

			</div>

		</div>

	</div>`

Thanks, Hope you will add the code there.

**Comment by holger1411** [comment]
Hi!
Thx for reporting this bug @NayeemNipun.
There was an issue after rebuilding the siebars dynamically. It also affects the statichero.

I fixed it a few minutes ago:
https://github.com/holger1411/understrap/commit/eeb27b00c7ddb56e6a261b90a750fc4bca36c378
