### ISSUE TITLE
Automatic code style checking

### ISSUE THREAD

**Issue by carl-alberto** [holger1411/understrap#231]
Hi Holger!

Awesome theme you have here, I would like to contribute by putting an automated way to check the coding style if it conforms with the WP Coding Standards, check out the log generated here: https://travis-ci.org/carl-alberto/understrap/jobs/195623742

You can that the bootstrap-wp-gallery.php has some warning that it is not recommending to use extract.

**Comment by carl-alberto** [comment]
Added a PR here to add the automated file checking in Travis
https://github.com/holger1411/understrap/pull/232

**Comment by stef-k** [comment]
Hi, in a recent PR I've noticed that travis reports errors related to third party code (WooCommerce). Since the code is not developed by this project and this project will update sources from upstream for the specific library, is there a way to exclude them from testing?

**Comment by holger1411** [comment]
Hm I add
 --ignore=*/woocommerce/*
to the phpcs command in travis.yml:
https://github.com/holger1411/understrap/commit/86b9f498e7277fd4bbe948779568e4f0f24f0459

Never worked with it before so I don´t know if it is the right approche to ignore folder...but it seems to work. WooCommerce issues aren´t reportet anymore by Travis:
https://travis-ci.org/holger1411/understrap/jobs/197341853

**Comment by holger1411** [comment]
@carl-alberto 
I was able to nearly remove any error message.
But one last is still there:
FILE: /home/travis/build/holger1411/understrap/comments.php

```
----------------------------------------------------------------------

FOUND 1 ERROR AFFECTING 1 LINE

----------------------------------------------------------------------

 29 | ERROR | Missing singular placeholder, needed for some languages.

    |       | See

    |       | https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals

    |       | (WordPress.WP.I18n.MissingSingularPlaceholder)

----------------------------------------------------------------------
```
There is a singular and plural placeholder present:
`esc_html( _nx( 'One thought on &ldquo;%2$s&rdquo;', '%1$s thoughts on &ldquo;%2$s&rdquo;', get_comments_number(), 'comments title', 'understrap' ) ),`

And its exactly the same code like in _s, also the `// WPCS: XSS OK.` comment did not help to suppress the error message.

@carl-alberto (or anyone else) : Any idea to fix this? Or to suppress the error message?

**Comment by holger1411** [comment]
Sorry, found a solution by myself. 
Now everything is green! :
https://travis-ci.org/holger1411/understrap/jobs/197613001

There was a (non-merged) pull request over there at the _s repo just using a code snipped from Twenty Sixtenn theme which fix it.

**Comment by carl-alberto** [comment]
@holger1411 Congratulations for passing your theme to comply the WP Coding standards :)
