### ISSUE TITLE
Ajax "Add To Basket" no longer working

### ISSUE THREAD

**Issue by typeplus** [holger1411/understrap#235]
From a default install with 1 dummy product of understrap Version: 0.5.4 the ajax function no longer works so it forces a page refresh. 

I have made sure  "Enable AJAX add to basket buttons on archives" is ticked and there is no other js being loaded, just the default understrap theme.

Any ideas?

**Comment by stef-k** [comment]
Is this a native WooCommerce functionality? If yes it should be there. I haven't removed any including JS files from the edited templates.

I'll have a look at it but I cannot guarantee when since I am working on a project these days.

**Comment by typeplus** [comment]
I had another look and cant believe it was such a simple thing. The add to cart template just needed the default ajax classes added back. I have created a pull request (its my first so I probably fudged it somehow). see #244 .
