### ISSUE TITLE
Woocommerce form-checkout uses col-1

### ISSUE THREAD

**Issue by VesterDe** [holger1411/understrap#236]
The template form-checkout.php in woocommerce uses col-1 to split customer fields. That makes bootstrap squish it to 8.3% width. Using col-12 col-sm-6 seems to make it act about the same. We will need to include form-checkout.php in understrap for that.

I'll make a pull request eventually, but if someone beats me to it that's also fine :)

**Comment by stef-k** [comment]
good catch, today I've found some time, fix incoming.

**Comment by PaulBart** [comment]
This doesn't appear to have been fixed? Or am I missing something?
