### ISSUE TITLE
Multiple Static Heroes

### ISSUE THREAD

**Issue by scottmattiza** [holger1411/understrap#238]
Your homepage https://understrap.com/ appears to utilize multiple static heroes.  Would you happen to have any example of how to achieve this myself?  Or would I need to register multiple sidebar (hero) widgets?  or do I hard code them in as a template file?  thanks!

**Comment by holger1411** [comment]
You can use the blank UnderStrap template:
https://understrap.com/understrap/?page_id=1736
Than add all your HTML layout and code into the WP editor.
Its like a empty canvas for static HTML in WordPress

**Comment by niccolox** [comment]
I got this to work using the Empty Page Template from the Pages pull down options

I assume this is correct?
