### ISSUE TITLE
Woocommerce: Variable product doesnt show default images

### ISSUE THREAD

**Issue by danvernon** [holger1411/understrap#239]
When setting a product variable, there is no default image showing.

eg. http://minitinsel.com/product/neon-triangle-birthday-box/

**Comment by holger1411** [comment]
@stef-k Do you have time to have a look?

**Comment by stef-k** [comment]
Hi, I will check it when at home and report back.

**Comment by stef-k** [comment]
Well, i've checked in my dev environment having checked out the latest commit and I do not see any problems.

Additionally i've checked your site and some products work as expected and some not, for example these work:

* http://minitinsel.com/product/halloween-wizard-hat-and-garland-set/
* http://minitinsel.com/product/valentines-love-heart-balloons/

but these aren't:

* http://minitinsel.com/product/neon-triangle-birthday-box/
* http://minitinsel.com/product/neon-confetti-birthday-box/

I don't think its a problem caused from Understrap - WooCommerce integration, i mean it should be causing the same problem every time it uses the same template.

My thoughts go to:

* another WooCommerce plugin causing the problem, if this is the case please remove the plugin(s) and check again
* another WordPress problem, if this is the case please remove the plugin(s) and check again
* bad installation
* caching - DB issues

Please check the above and report back so we can have more input.

**Comment by danvernon** [comment]
Hey Stef,

The first 2 products are simple products not variable ones. The variable products dont show the default images until you select at least one option. This works fine with 3 other themes I tried.

I am using a child theme btw.

Daniel
http://www.madebycircle.com <http://www.madebycircle.com/>

**Comment by stef-k** [comment]
Hi again,

I don't think it matters if a product is a normal or a variable one, both are using `single-product.php` template, at least this is what the [Show Current Template](https://wordpress.org/plugins/show-current-template/) dev plugin reports to me. 

I have set both product types in my environment and both are been rendered without any problems as you can see bellow:

**normal product:**

![selection_002](https://cloud.githubusercontent.com/assets/5731388/22480289/8d4e7f3a-e7f9-11e6-84ef-a4982a71225d.jpg)

**variable product:**

![selection_001](https://cloud.githubusercontent.com/assets/5731388/22480208/4654c9c2-e7f9-11e6-90de-258065336d47.jpg)

another variance of the same product

![selection_003](https://cloud.githubusercontent.com/assets/5731388/22480355/cd253de2-e7f9-11e6-8caa-00895b0ceccd.jpg)

as you can see both variances (medium and large) are working well  and render the correct image I have set up.

What are the versions of WP - WOO - Understrap you are using?

**Comment by danvernon** [comment]
You have set an option, where as there are no options selected in mine.

Have you tried it with no option selected?

**Comment by stef-k** [comment]
Again, 

with a default image set for product (unrelated with the available variations)
![selection_001](https://cloud.githubusercontent.com/assets/5731388/22480718/07eae5b6-e7fb-11e6-9f05-1446a231ff59.jpg)

and this is if I remove the default image, Woo shows a default placeholder image:

![selection_002](https://cloud.githubusercontent.com/assets/5731388/22480748/220accae-e7fb-11e6-9454-b518be6b5902.jpg)

**Comment by danvernon** [comment]
Ok I found the fix, was using a beta of woocommerce - sorry guys for the time wasting!

**Comment by stef-k** [comment]
Heh, no problem, glad it has resolved.

**Comment by holger1411** [comment]
nice to see you guys solve it +1
