### ISSUE TITLE
Watch-bs task for BrowserSync at gulpfire.js

### ISSUE THREAD

**Issue by sharewood** [holger1411/understrap#24]
Following instructions from the updated readme.md terminal outputs: 
"Task 'watch-bs' is not in your gulpfile"
Please give a task to correct gulpfire.js

**Comment by holger1411** [comment]
Make sure you update to the latest version. Changes to the gulpfile was merged just a few minutes before your post here. (pull request was two days old so it shows another date).
Here is the request: https://github.com/holger1411/understrap/pull/23

And run "npm update" or "npm install" after it.
