### ISSUE TITLE
Allow plugins/child-themes to update Tiny MCE Formats menu

### ISSUE THREAD

**Issue by arpage** [holger1411/understrap#240]
Hello,
As written, inc/editors.php overwrites any previous entries in `$settings['style_formats']`

I have a small patch that will fix this potential problem.  I am pasting it inline here.  Please let me know if I need to submit the patch differently.  Thank you:

```
diff --git inc/editor.php inc/editor.php
index fcbb307..8b6892a 100644
--- inc/editor.php
+++ inc/editor.php
@@ -57,6 +57,12 @@ function understrap_tiny_mce_before_init( $settings ) {
'inline' => 'cite'
)
);
+
+ if ( isset( $settings['style_formats'] ) ) {
+ $orig_style_formats = json_decode($settings['style_formats'],true);
+ $style_formats = array_merge($orig_style_formats,$style_formats);
+ }
+
$settings['style_formats'] = json_encode( $style_formats );
return $settings;
}
```

**Comment by holger1411** [comment]
Hi!
Thx for your hint.
Implemented it here:
https://github.com/holger1411/understrap/commit/c0ea2d9f6e8820703659503d4adbd9da96dec3f8
