### ISSUE TITLE
BS Carousel unable to follow BS documentation to implement

### ISSUE THREAD

**Issue by flyingchorse** [holger1411/understrap#243]
I am finding an small issue where I am having to wrap the carousel-item in a `<div>` for the image resizing to work. I think its a hangover from it being implemented with the hero widget. 

As I am not using the widget I have been trying to follow the correct implementation from the bootstrap documentation, but I cannot get it to work. 

So BS implementation is like:
```
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="..." alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="..." alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="..." alt="Third slide">
    </div>
  </div>
</div>
```

What I have to do to get it to work:

```
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div><img class="d-block img-fluid" src="..." alt="First slide"></div>
    </div>
    <div class="carousel-item">
       <div><img class="d-block img-fluid" src="..." alt="Second slide"></div>
    </div>
    <div class="carousel-item">
       <div><img class="d-block img-fluid" src="..." alt="Third slide"></div>
    </div>
  </div>
</div>
```

**Comment by holger1411** [comment]
Can you post the carousel code you try to implement and tell me where (in a template file, as page content or somewhere else) you try it? Or the URL?

**Comment by flyingchorse** [comment]
```
<?php
/**
 * Template Name: Home Page Template
 *
 * Template for displaying a page without sidebar even if a sidebar widget is published.
 *
 * @package understrap
 */

get_header();

$container   = get_theme_mod( 'understrap_container_type' );
$sidebar_pos = get_theme_mod( 'understrap_sidebar_position' );
// On WooCommerce pages there is no need for sidebars as they leave
// too little space for WooCommerce itself. We check if WooCommerce
// is active and the current page is a WooCommerce page and we do
?>

<div class="wrapper" id="wrapper-hero">


	<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">

			<div class="carousel-inner" role="listbox">

				<div class="carousel-item active">			
					<img class="d-block img-fluid" src="http://davids-imac/rjp/wp-content/uploads/2017/02/RANGE-ROVER-WADING_WEB-INTERIM.jpg">
				</div>
				
				<div class="carousel-item ">			
					<img class="d-block img-fluid" src="http://davids-imac/rjp/wp-content/uploads/2017/02/HORSES-PATAGONIA_WEB-INTERIM.jpg">
				</div>
		
			</div>

	</div>
</div>
<div class="wrapper" id="page-wrapper">

	<div class="<?php echo esc_html( $container ); ?>" id="content" tabindex="-1">

		<div class="row">

			<!-- Do the left sidebar check -->
			<?php get_template_part( 'global-templates/left-sidebar-check', 'none' ); ?>

			<main class="site-main" id="main">

				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'loop-templates/content', 'page' ); ?>

					<?php
					// If comments are open or we have at least one comment, load up the comment template.
					if ( comments_open() || get_comments_number() ) :
						comments_template();
					endif;
					?>

				<?php endwhile; // end of the loop. ?>

			</main><!-- #main -->

		</div><!-- #primary -->

		<!-- Do the right sidebar check -->
		<?php if ( 'right' === $sidebar_pos || 'both' === $sidebar_pos ) : ?>

			<?php if ( ! $is_woocommerce ) : get_sidebar( 'right' ); ?>
			<?php endif; ?>

		<?php endif; ?>

	</div><!-- .row -->

</div><!-- Container end -->

</div><!-- Wrapper end -->

<?php get_footer(); ?>
```

**Comment by flyingchorse** [comment]
Sorry the URL is not live as Im working locally

**Comment by flyingchorse** [comment]
I could put it live though if you need me to

**Comment by holger1411** [comment]
Not needed, but could you tell me what happends if you don´t add this extra DIV? Can you add a screenshot or something?

**Comment by flyingchorse** [comment]
![with_div](https://cloud.githubusercontent.com/assets/2514231/22553790/db932c6a-e955-11e6-90ae-8cc8ee13e3b4.png)
![without_div](https://cloud.githubusercontent.com/assets/2514231/22553791/db9344ac-e955-11e6-92d0-0a30d6fe1527.png)

**Comment by flyingchorse** [comment]
Top one is with, second without

**Comment by holger1411** [comment]
So the problem is that the image did not keep it ratio, right?
Hm, test it here adding a `.img-fluid <img>` as widget to the hero carousel and it works:
![screenshot-understrap com 2017-02-02 15-49-24](https://cloud.githubusercontent.com/assets/1568158/22554260/bdbfa72c-e95f-11e6-9c35-b8b44ed2a86f.png)

It keeps its size ratio from 1:1.33

Seems in your case `height: auto` didnt work. But can´t tell why without the full source code of your website.
I would suggest that you post it here as soon as it is available somewhere online. Than I can take a closer look at it.

**Comment by flyingchorse** [comment]
But isnt that `<img>` wrapped up in a `<div>` from whatever widget it is you use, for example I have used the text widget previously. which give you : `<div class="textwidget"><img src="http://davids-imac/rjp/wp-content/uploads/2017/02/RANGE-ROVER-WADING_WEB-INTERIM.jpg"></div>` Which works fine, if you want to use the widget.

**Comment by holger1411** [comment]
Yes, but I removed the text-widget div via my webdeveloper tools in FireFox (and Chrome for cross testing it) to check it out.
And on your screens it looks like `auto: height` didnt work...which sounds more like a CSS issue (probably)

**Comment by flyingchorse** [comment]
OK I have tried the same  on this site https://understrap.com/understrap/ and did like you said removed the containing text-widget div  . If you resize the window you get this:
![screencapture-understrap-understrap-1486049784669](https://cloud.githubusercontent.com/assets/2514231/22555979/8aacc466-e95d-11e6-81ee-aecd57e19f50.png)

**Comment by holger1411** [comment]
Thats how it looks here:
![feb -02-2017 17-33-48](https://cloud.githubusercontent.com/assets/1568158/22558420/e53f8cb4-e96d-11e6-962b-47bcd153cc7a.gif)

In the dev toolbar you can see that there is no text-widget div

Latest FireFox version on a Mac.

Please try it in another browser, too.

If you are on Chrome, please log out and clear all caches.
Especially Chrome stores a lot of stuff. Its often a problem that Chrome stores settings for one JS file from site X, than use the same variables on site Y if the same script is used, even if there are other variables.
You cant get rid off it just by clearing the cache, you have to log out too.

If that don´t help: Just add a `<div>` container around the item(s).

**Comment by flyingchorse** [comment]
Ok that's really weird.
