### ISSUE TITLE
Owl Slider Stopped Working 

### ISSUE THREAD

**Issue by tellstevens** [holger1411/understrap#246]
It looks like my customer upgraded understrap and their slider stopped working. I took a look at it and I'm seeing this error in the developer tools. Is this just an issue with an older version of the child theme? Do I just need to update that? 

![image](https://cloud.githubusercontent.com/assets/10147938/22666752/df9dd8fc-ec87-11e6-9795-f6747467c4e0.png)

**Comment by holger1411** [comment]
Hi!

Yes, seems you use an old child theme version (0.1.0.4 while 0.2 is the latest), which did not supported the latest Bootstrap 4 version, while the latest UnderStrap version based on BS4 Alpha 6 and its JS scripts.

**Comment by holger1411** [comment]
Oh, and it is important to metion than the latest UnderStrap version did not use the Owl slider anymore but the build-in Carousel script instead.

**Comment by tedgeving** [comment]
Thanks, just noticed that Owl Carousel was removed.

**Comment by tellstevens** [comment]
Thanks for the quick response. I'm at a conference so I just rolled them back to the previous version until I clean it up correctly. 

Thanks again.
