### ISSUE TITLE
WooCommerce Shop Page

### ISSUE THREAD

**Issue by evandiamond** [holger1411/understrap#248]
Default `Shop` page from WooCommerce plugin, is a hot mess. All templated files should have the same page structure, html, css for consistency.

https://www.dropbox.com/s/h8cx47brwnb96td/Screenshot%202017-02-11%2001.19.41.png?dl=0

**Comment by holger1411** [comment]
Hi!
Yes, I ´am currently working on this.
See the UnderStrap demo site´s WooCommerce implementation:
https://understrap.com/understrap/?post_type=product

If you want to use this "bleeding edge" version use the "clone or download" button here:
https://github.com/holger1411/understrap

**Comment by evandiamond** [comment]
Great. The bleeding edge version fixes it. I guess I'll use that version for now.
@holger1411 could I use my own version of a file inside inc/woocommerce.php if I needed to? How would I go about doing that?

**Comment by boylecreations** [comment]
Oops looks like i posted a duplicate issue. I just restyled this for a project I was working on. Is this finished or would you like the templates I wrote for it? I plan on using this again in the future so any help I can offer I'm happy to give.

**Comment by holger1411** [comment]
@boylecreations Hi!
Depends on your templates ;-). Do they use Bootstrap 4 markup and whats the difference between them and the UnderStrap templates for WooCommerce here: https://github.com/holger1411/understrap/tree/master/woocommerce ?

**Comment by holger1411** [comment]
Was fixed (so far...) with the latest release 0.5.7: https://github.com/holger1411/understrap/releases/tag/0.5.7

**Comment by boylecreations** [comment]
Yeah I switched the forms over to using Bootstrap 4's form classes and column sizing for the account pages. I'll have to take a look at the link, though I know the version I was using had woo commerce classes previously, so things were scrunched up together in a 2 column size for some things. It's a relatively simple fix though and I'll take a look at the newest release for sure. Really like the theme.

**Comment by evandiamond** [comment]
We definitely need those Bootstrap 4 forms for woo commerce. Nice work! Let
me know when they get integrated.


*Evan*

**Comment by foobarnautT** [comment]
Quick question -- how do I disable the blog sidebar on the shop page? 

Example: http://imgur.com/a/VgrhU

That is with the "page attribute" template being set to "Full Width Page"

**Comment by holger1411** [comment]
Argh, yes. WooCommerce uses the woocommerce.php template file, even if you select another template. Will check it.

**Comment by tommybds** [comment]
Hello, how to enable then the blog sidebar on the shop page again ?
