### ISSUE TITLE
Missing Sass folders?

### ISSUE THREAD

**Issue by jrmypttrsn** [holger1411/understrap#251]
The folders contained within the Sass folder seem to be missing. When I try to upload them I get an error saying they already exist.

I'm able to access these folders through cPanel and edit the files contained within them but the changes I make to _theme_variables.scss, for example, are not being applied.

I'm new to Wordpress so any help would be greatly appreciated.

![screenshot from 2017-02-13 19-55-41](https://cloud.githubusercontent.com/assets/16291625/22911679/9c2fba28-f226-11e6-9a8b-8a04e66f67bb.png)

**Comment by holger1411** [comment]
Hi!
If you upload tool says it already exists but did not show it it might be a caching or JS problem of the used tool.

SASS is not a WordPress thing. You don´t need to upload the files to your server.
Normally you should do your changes locally, compile your sass to css and than upload the outputted css/theme.min.css

**Comment by jrmypttrsn** [comment]
Thanks, @holger1411. I'll try that. Should note that I'm new to Sass as well.

And thanks for this theme. It's been a great way to get familiar with Wordpress and PHP, coming from Ruby and Rails as a new developer.

**Comment by holger1411** [comment]
Hi!
Here is a good starter guide for SASS: http://thesassway.com/beginner
