### ISSUE TITLE
Some Columns on the Woocommerce Dashboard Unstyled.

### ISSUE THREAD

**Issue by boylecreations** [holger1411/understrap#253]
If you look at pages like edit your billing and shipping address you'll see that the default woocommerce template is set to col-2 for their code purposes. With Bootstrap 4 though that converts over to really super small forms. Suggest filters or more templates increasing that to col-12 and/or to use bootstrap form styles

**Comment by holger1411** [comment]
Duplicate of https://github.com/holger1411/understrap/issues/248
