### ISSUE TITLE
Navbar wont float rigth

### ISSUE THREAD

**Issue by drosendo** [holger1411/understrap#255]
I have already read other posts but the nav will not go right..

I just added that line to the header.php "float-xs-right".
```
       <?php
                        wp_nav_menu(
                                array(
                                    'theme_location' => 'primary',
                                    'container_class' => 'collapse navbar-collapse',
                                    'container_id' => 'navbarNavDropdown',
                                    'menu_class' => 'navbar-nav float-xs-right',
                                    'fallback_cb' => '',
                                    'menu_id' => 'main-menu',
                                    'walker' => new WP_Bootstrap_Navwalker(),
                                )
                        );
                        ?>
```

Thanks you!

**Comment by drewpyd85** [comment]
I simply added this into my _theme.scss works perfectly fine.

`#navbarNavDropdown {
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    justify-content: flex-end;
}`

**Comment by holger1411** [comment]
Hi!
@drosendo Please use:
`navbar-nav ml-auto`
to float the navbar menu ul element to the right.
Since BS 4 alpha 6 (with flexbox alway on) there are other helper classes in use:

"ml-auto" means "add **M**argin **L**eft **auto**matically as much space as possible"

**Comment by jlkporter** [comment]
Hi @drosendo,
Flexbox caught me out for a bit - this was useful reading https://css-tricks.com/snippets/css/a-guide-to-flexbox/ and my what worked for me should, it help. 

#navbarNavDropdown{
    justify-content: flex-end;
}

.navbar-inverse .navbar-toggler {
        align-self: flex-end;
        border:0;
}
