### ISSUE TITLE
Layout broken on Safari 8+

### ISSUE THREAD

**Issue by ntrantrinh** [holger1411/understrap#256]
The Understrap layout seems to be broken on Safari 8+, it looks like flexbox isn't working very well. Is there a workaround for this? I've tried using Autoprefixer but that didn't seem to solve the problem.

**Comment by holger1411** [comment]
Can you tell me a bit more about what is broken?mThe UnderStrap demo site looks okay on the latest Safari (v 10.0 on a Mac)

**Comment by ntrantrinh** [comment]
My mistake, seems to be working fine on Safari 10.0 - Issues present on Safari 8.0. Screenshot here: http://i.imgur.com/IJR7Onu.png

**Comment by holger1411** [comment]
Bootstrap 4 Alpha 6 uses flexbox which is supported by more modern browsers only:
http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/

So its not a real UnderStrap bug, more a "older browsers are not supported by Bootstrap 4" issue.
That can´t be fixed.
But the Safari 8 marketshare is nearly zero, so it should not be a problem

**Comment by ntrantrinh** [comment]
Hm. I figured that would be the case. Thanks!
