### ISSUE TITLE
'gulp watch-bs' & 'gulp watch' does not detect scss file changes (and does not recompile)

### ISSUE THREAD

**Issue by firelite** [holger1411/understrap#258]
Hi,

I manually downloaded understrap from this repo and ran `npm install` and started `gulp watch` successfully, but when I edit and save sass files, specifically `src/sass/bootstrap4/_custom.scss` and `src/sass/understrap/style.scss`, gulp does not output any messages in terminal, nor does browser-sync automatically refresh my browser tabs.

Any ideas what might be the problem?

**Comment by firelite** [comment]
Okay, found the answer at [https://understrap.github.io/#gulp-npm-scss-example](https://understrap.github.io/#gulp-npm-scss-example) under the **Styling the Theme** section.   `gulp watch-bs` and `gulp watch` only watches files in `understrap/sass/**/*` not `understrap/src/sass/**/*`.

**Comment by holger1411** [comment]
Hi!
Yes, and you should not edit files in the /src folder. Because if you update your sources your changes will be overwritten.
