### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by bahiirwa** [holger1411/understrap#261]
Please check on missing assets for bootstrap

// Core variables and mixins
@import "../../src/sass/bootstrap4/variables";
@import "../../src/sass/bootstrap4/mixins";
@import "../../src/sass/bootstrap4/custom";

// Reset and dependencies
@import "../../src/sass/bootstrap4/normalize";
@import "../../src/sass/bootstrap4/print";

// Core CSS
@import "../../src/sass/bootstrap4/reboot";
@import "../../src/sass/bootstrap4/type";
@import "../../src/sass/bootstrap4/images";
@import "../../src/sass/bootstrap4/code";
@import "../../src/sass/bootstrap4/grid";
@import "../../src/sass/bootstrap4/tables";
@import "../../src/sass/bootstrap4/forms";
@import "../../src/sass/bootstrap4/buttons";

// Components
@import "../../src/sass/bootstrap4/transitions";
@import "../../src/sass/bootstrap4/dropdown";
@import "../../src/sass/bootstrap4/button-group";
@import "../../src/sass/bootstrap4/input-group";
@import "../../src/sass/bootstrap4/custom-forms";
@import "../../src/sass/bootstrap4/nav";
@import "../../src/sass/bootstrap4/navbar";
@import "../../src/sass/bootstrap4/card";
@import "../../src/sass/bootstrap4/breadcrumb";
@import "../../src/sass/bootstrap4/pagination";
@import "../../src/sass/bootstrap4/badge";
@import "../../src/sass/bootstrap4/jumbotron";
@import "../../src/sass/bootstrap4/alert";
@import "../../src/sass/bootstrap4/progress";
@import "../../src/sass/bootstrap4/media";
@import "../../src/sass/bootstrap4/list-group";
@import "../../src/sass/bootstrap4/responsive-embed";
@import "../../src/sass/bootstrap4/close";

// Components w/ JavaScript
@import "../../src/sass/bootstrap4/modal";
@import "../../src/sass/bootstrap4/tooltip";
@import "../../src/sass/bootstrap4/popover";
@import "../../src/sass/bootstrap4/carousel";

// Utility classes
@import "../../src/sass/bootstrap4/utilities";

**Comment by holger1411** [comment]
Pls run
`npm install`
in your terminal first.
That will move anything in place.
