### ISSUE TITLE
Custom Pagination Text

### ISSUE THREAD

**Issue by samuelgates** [holger1411/understrap#263]
Hello,

What is the best method to edit the "Older Post" and "Newer Post" pagination text within Understrap?

**Comment by holger1411** [comment]
UnderStrap replaced that links with a pagination nav. So there is no "Older/Newer" link text.
![screenshot-understrap com 2017-03-06 08-45-12 jpeg](https://cloud.githubusercontent.com/assets/1568158/23600936/4b8ee96c-0249-11e7-89d7-67940f2475e0.jpg)

**Comment by samuelgates** [comment]
Interesting, this is what came out of the box with my version of UnderStrap. (Please see attached link)
[http://imgur.com/a/60Xc0](url)

What file should I be using to access the text "Older Posts" and "Newer Posts"? I am simply looking to change those strings.

**Comment by holger1411** [comment]
Do you use and older version or a child theme with older files?

**Comment by samuelgates** [comment]
I found that source was coming from "<?php the_posts_navigation(); ?>" that was found in my category.php page.

**Comment by holger1411** [comment]
The UnderStrap theme did not come with an category.php file.
If you found it in your category.php file you can change the text right there.
Or, if it is a translatable string, use a plugin like Locco Translate to edit your language file.
