### ISSUE TITLE
Gulp stops watching on sass error

### ISSUE THREAD

**Issue by Filipwessman** [holger1411/understrap#264]
Every time i write a sass error i have to restart the gulp watch-bs, kind of anoying. Is there and easy fix for this in the gulpfile?

**Comment by MantaWray** [comment]
Duplicated .pipe(gulp.dest('./css')) in sass function on gulpfile.js 
Fix for this:

Change:
gulp.task('sass', function () {
    var stream = gulp.src('./sass/*.scss')
        .pipe(plumber())
        .pipe(sass())
        .pipe(gulp.dest('./css'))
        .pipe(rename('custom-editor-style.css'));
        .pipe(gulp.dest('./css'));
    return stream;
});

To: 

gulp.task('sass', function () {
    var stream = gulp.src('./sass/*.scss')
        .pipe(plumber())
        .pipe(sass())
        .pipe(gulp.dest('./css'))
        .pipe(rename('custom-editor-style.css'));
    return stream;
});

**Comment by holger1411** [comment]
Thx for your feedback!
Change that here: https://github.com/holger1411/understrap/commit/aed0e6440db51ae5406a5e1a4902df4ebf0ede1b
