### ISSUE TITLE
How to update an understrap project

### ISSUE THREAD

**Issue by Parcye** [holger1411/understrap#266]
What is the best way to go about updating a understrap project? 

I am not using a child theme as I want to build in some custom extra's before going on creating childtheme's. But between my start and the current date loads has been done/changed within understrap.

Is it just a npm update ? Does that not overwrite all customs additions?

**Comment by saknopper** [comment]
I usually create a new branch for a project that is based on understrap. The master branch corresponds to the upstream understrap project.

When I want to update my project I first update (pull) the master branch and then checkout my project branch. After that I simply run:
```
git rebase master
```
Though technically you could also merge, I prefer a rebase.

After all this you can use npm and gulp to update external sources and build your project.

Hope this helps a little.

**Comment by Parcye** [comment]
Well if it wasn't for @holger1411 reacting to a linkedin question a few months back I wouldn't had been using npm and guld just yet... it sounds like I need to move along to also get on with github and do my magic the way you describe. 

I am currently on version 0.5.1 and noticed some big improvements on woocommerce and that is just what I am getting on to at the moment in my project...

**Comment by LittleHamster** [comment]
@saknopper is that a good idea? because every time you pull the latest code from the repo, you will be rewriting your modifications. 

@holger1411 can you please recommend the best way to create themes based on understrap and update the core files and not lose our modifications?

**Comment by holger1411** [comment]
@LittleHamster: Use the UnderStrap child theme: https://github.com/holger1411/understrap-child Do you changes/modification there.
So you can update the parent theme without loosing your modifications.

**Comment by Rokito** [comment]
@holger1411 That sounds like a great plan! But i have another question on this topic. I would like to merge Understrap with the child theme again into a single theme. How would you recommend to do that so it's still automated?

**Comment by nuthinbutajthang** [comment]
Hi, I have a question about this topic too. I've created a website using understrap-child theme. Last month, I received an email from Holger about an update on this child theme (BASE 0.3.5). My website is based on BASE 0.3.2. And the parent theme is 0.6.2, and I see a notice for an update. I'm afraid to update parent without updating the child. What is the correct way to update the child theme? Or do I even need to do it?

**Comment by mcropper** [comment]
@holger1411 is there clear instruction on this? Like @nuthinbutajthang somewhat unclear about the correct way to update without losing any modification to the parent theme

**Comment by Mugane** [comment]
I mean, the whole point of understrap is to have a BASE theme for creating your own theme, right? using a child theme with it defeats the purpose.
