### ISSUE TITLE
Vertical one Page

### ISSUE THREAD

**Issue by Oliviercreativ** [holger1411/understrap#269]
Hi !

Why the template Vertical One Page is not found on new version Understrap please ?

And olders version, i'm using Vertical One Page, that's good for SEO ?

Sorry, i'm bad english ....

Cordialement
King regard !

**Comment by holger1411** [comment]
Sorry, it caused some trouble and we decide to remove it.
Another reason was the decision to develope UnderStrap more as a theme developer framework, not a full featured/designed enduser framework (like Avada, Divi etc.).

So we removed all "no -core" features to spend more time on the basics.

**Comment by holger1411** [comment]
And from a SEO perspective its mostly better to have more pages and separated content. In most cases there is no positiv effect in having a one pager with all content. In some cases there is even a negative effect.

**Comment by Oliviercreativ** [comment]
Ok ;)
Thanks Holger ! 
I'm continue using Understrap, my best starter theme !
