### ISSUE TITLE
Set up other language?

### ISSUE THREAD

**Issue by julienhoste** [holger1411/understrap#270]
Hello, 
First of all, thanks for this theme, an excellent starting point!
I just started an other project that should be multilingual : FR - NL. So, since the install came in english, my first move is to set FR or NL as default language. So, I went to 'WP settings > general > Site Language dropdown' - unfortunately only 'English (united States)' is available. Yet I read about Translation ready. did I missed something?

1. Should I do something to populate Site language dropdown? I try by setting - define('WPLANG', 'fr_FR'); - in wp-config.php too.
2. Should the languages folder in the theme be moved to /wp-content/languages/ ? 
3. Wondering if the french and dutch translations are ready to use? I found this https://translate.wordpress.org/projects/wp-themes/understrap But few languages seem completed. I could help for french, if needed.

Thanks by advance. 

Nb: I plan to manage multilingual aspect with Polylang. if anyone has experienced this with Understap, or has any other suggestion, thanks for letting me know ;-)

**Comment by holger1411** [comment]
Hi!
Under settings-> general ->Site Language dropdown Select French under the "Available" section. Than it will be installed automatically after hitting the "save" button.
![marz-17-2017 15-44-54](https://cloud.githubusercontent.com/assets/1568158/24048308/b4845bfe-0b28-11e7-87f7-8060c0e93fd4.gif)

**Comment by julienhoste** [comment]
Yes, this is what I had in mind, but as explained above the dropdown menu has no other choice
![screen shot 2017-03-17 at 16 09 03](https://cloud.githubusercontent.com/assets/808613/24049415/2ca5e3de-0b2c-11e7-8588-21211c2c66fe.png)

**Comment by holger1411** [comment]
No, that are two different things. The UnderStrap /language folder holds just to translations for the in-theme used text strings. Like for the next and prev buttons, the search widget etc.

The wp-content/language folder comes with the backend language set.

You can get the WP language files from here:
https://translate.wordpress.org/

If you set your WP language to, for example, french, the frontend (eg the theme) will use it, too.

It might be that the UnderStrap french translation isnt´up to date.
So if you miss something your can create a anew issue here or you can use a Plugin like Locco Translate to adjust the language file (...and also feel free to contribute it here;-)

**Comment by julienhoste** [comment]
Ok, Thanks for your enlightenment! 
I first populated the wp-content/language folder. 
And since my project language's are fr_BE and nl_BE, I had to rename the theme's po and mo files accordingly.
I keep you posted if any translation enhancement pops up.
Cheers
