### ISSUE TITLE
WooCommerce My Account Page Grid Issue

### ISSUE THREAD

**Issue by mikeoberdick** [holger1411/understrap#271]
In the form-login.php for WooCommerce the col-1 css is causing the form to squeeze into 10% of the page.

![image](https://cloud.githubusercontent.com/assets/16200630/24102241/a6cb62a2-0d51-11e7-8d24-1b7bdc5081c4.png)

**Comment by holger1411** [comment]
Hi!
Works here:
https://understrap.com/understrap/?page_id=1801
There where some changes regarding the WooCommerce setup after the last release.

Try the current Github version from here:
https://github.com/holger1411/understrap/archive/master.zip

**Comment by mikeoberdick** [comment]
If you get rid of the sidebar the issue arises.


Mike Oberdick
Designs 4 The Web <http://www.designs4theweb.com/>
203.516.0359 | mike@designs4theweb.com
<https://www.linkedin.com/in/mikeoberdick/>
<https://www.facebook.com/Designs4TheWeb>
<https://twitter.com/Designs4theWeb>
<https://plus.google.com/+Designs4thewebLLC/posts>
<https://www.youtube.com/user/Designs4TheWebLLC>

**Comment by holger1411** [comment]
Ah, now I´ve got it. 
The corresponding part just appears if the "create account" function is enabled (which is not active on my demo site...).
Changed it here:
https://github.com/holger1411/understrap/commit/6693edc72068c032d76e009a15646e9e9a321c9b

Thx @mikeoberdick !
