### ISSUE TITLE
Image optimization with imagemin

### ISSUE THREAD

**Issue by VesterDe** [holger1411/understrap#272]
Hey,
so Understrap has an /img folder, and for the most part, my projects usually have some images in it in the end.
It may be useful to add an image optimization task to our watch pipeline. WP uploads images are easy to optimize with plugins and even CLI commands, but theme specific images are often ignored in these processes.
This is the code we would need:

`//Inside the watch task.`
`gulp.watch('./img', ['imagemin'])`

`gulp.task('imagemin', function(){`
   `  gulp.src('img/*')`
    ` .pipe(imagemin())`
   `  .pipe(gulp.dest('img'))`
`});`

[Imagemin](https://www.npmjs.com/package/gulp-imagemin) is lossless by default, and ignores files other than .gif, .svg, .png, .jpg.

What do you guys think?

**Comment by holger1411** [comment]
+1
I´am sure nearly any endproduct based on UnderStrap will use some sort of images. So I thing more than 50% of all users need some sort of image optimization.

**Comment by VesterDe** [comment]
Thanks.

I guess we can close this until we see we broke something :P
