### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by jeremymcknight** [holger1411/understrap#274]
https://trailheadnc.org/message_series/holy-spirit/

I have a set of tabs that will only work when I add 
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>

But when this is added it cancels out my sub menu dropdown on the slideout menu.

I'm kindof a newbie to bootstrap and javascript any help is appreciated.

**Comment by holger1411** [comment]
Hi!

This is the repo of UnderStrap. An open source WordPress theme framework.
As far as I can see it you don´t use UnderStrap, but a custom made underscores.me theme. So I can´t help you with that.

If you have a general undersocres, JQuery or Bootstrap question you should ask / open an issue in the corresponding repos.
Sorry!
