### ISSUE TITLE
npm install doesn't finish

### ISSUE THREAD

**Issue by uitta** [holger1411/understrap#276]
I've just made a new vvv installation; when i try to npm install the understrap theme it seems to work (i can see the gulp copy-assets during the process) but when i try to gulp-watch it says gulp: command not found.
How is it possible? am i missing something very stupid, beeing one of my first time with vagrant and understrap?
It just give me some warning:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

thanks

**Comment by Alipio123** [comment]
try to delete the node_modules folder and make sure you run npm install through administrative level. 

if youre using windows make sure you run your powershell as admin 
if youre using mac run sudo npm install

**Comment by uitta** [comment]
no luck.
i tried upgrading node to v7.7.4 but still not working.


npm ERR! Linux 3.13.0-108-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! path /vagrant/www/gmrtrading/htdocs/wp-content/themes/understrap-child/node_modules/esprima/bin/esvalidate.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/www/gmrtrading/htdocs/wp-content/themes/understrap-child/node_modules/esprima/bin/esvalidate.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/www/gmrtrading/htdocs/wp-content/themes/understrap-child/node_modules/esprima/bin/esvalidate.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:

**Comment by uitta** [comment]
well it's not the gulp doesn't work, it's simply npm install doesn't finish, but i clearly cannot understand why...

**Comment by uitta** [comment]
I also tried [fixing my npm permission](https://docs.npmjs.com/getting-started/fixing-npm-permissions) (so i can npm install without sudo), but still it stops because it cannot find esvalidate.js (the error above).
I reinstalled vagrant with the last update and i don't know what to do anymore, only initialinzing my os x system, even though i know (hope so) it's not a system problem.

**Comment by uitta** [comment]
I tried using understrap in a mamp installation and everything went fine, so for now i'm using this solution. But still i'd like to know if i'm missing something o what i've done wrong.

**Comment by holger1411** [comment]
Hi!
At the end of "npm install" it runs the gulp task "gulp copy-assets" to move all needed dependency files into the /src folder.
If gulp didnt work npm install will not run this task at the end and will render an error message. So it might be a gulp problem...

**Comment by magicDamo** [comment]
i'm experiencing the same issue where the npm install 'nearly completes' then bails during the gulp copy assets task.
the npm modules are installed in the node_modules directory ( or at least it looks that way ),  but it looks like package.json is not created.
the error in terminal is:
npm WARN enoent ENOENT: no such file or directory, open '/Applications/XAMPP/xamppfiles/apps/wordpress/htdocs/wp-content/themes/understrap/package.json'
npm WARN understrap No description
npm WARN understrap No repository field.
npm WARN understrap No README data
npm WARN understrap No license field.

using npm version 4.47 and gulp version 3.9.1

please advise if you get this sorted out.

**Comment by magicDamo** [comment]
follow up: i installed node v6.10.2, and the installation issue still exists.

**Comment by lightbyte** [comment]
I solved the problem of "gulp is not installed" by executing:
   ` nodejs node_modules/gulp/bin/gulp watch`

or you can install gulp manually globally:
    `npm install --global gulp-cli`

I hope that helps you
