### ISSUE TITLE
SRC folder not in /releases

### ISSUE THREAD

**Issue by poomato** [holger1411/understrap#277]
Bootstrap SASS won't compile without the missing src folder, not found in releases.

**Comment by greatwitenorth** [comment]
I think you need to run ```npm install``` first.

**Comment by holger1411** [comment]
Will add it again in the next release to stop problems using UnderStrap out of the box.

**Comment by holger1411** [comment]
Is already added to the repo here. So its fixed and will be shipped with the newest version.
thx for pointing out that the folder was missing!

**Comment by holger1411** [comment]
/src is now again part of the install zip since 0.6.0 so I´am closing this for now
