### ISSUE TITLE
WooCommerce 3.0

### ISSUE THREAD

**Issue by Filipwessman** [holger1411/understrap#279]
Is this something that is being worked on?

**Comment by typeplus** [comment]
What are the issues?

**Comment by wimmulder** [comment]
I haven't noticed any specific issues except that the new WooCommerce product image gallery isn't implemented yet. 
https://woocommerce.wordpress.com/2016/09/07/the-new-woocommerce-product-image-gallery/

**Comment by Filipwessman** [comment]
WooCommerce indicates that the code in Understrap is outdated with the release of 3.0

**Comment by jhob101** [comment]
Woocommerce indicates the override status as:
`goalfix/woocommerce/archive-product.php, 
goalfix/woocommerce/cart/cart-empty.php, 
goalfix/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.0, 
goalfix/woocommerce/cart/mini-cart.php, 
goalfix/woocommerce/cart/proceed-to-checkout-button.php, 
goalfix/woocommerce/checkout/form-checkout.php, 
goalfix/woocommerce/checkout/form-coupon.php, 
goalfix/woocommerce/checkout/form-pay.php, 
goalfix/woocommerce/checkout/payment.php, 
goalfix/woocommerce/global/form-login.php, 
goalfix/woocommerce/global/quantity-input.php, 
goalfix/woocommerce/global/wrapper-end.php, 
goalfix/woocommerce/global/wrapper-start.php, 
goalfix/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0, 
goalfix/woocommerce/loop/orderby.php, 
goalfix/woocommerce/myaccount/downloads.php version 2.6.0 is out of date. The core version is 3.0.0, 
goalfix/woocommerce/myaccount/form-edit-account.php, 
goalfix/woocommerce/myaccount/form-edit-address.php, 
goalfix/woocommerce/myaccount/form-login.php, 
goalfix/woocommerce/myaccount/form-lost-password.php, 
goalfix/woocommerce/myaccount/form-reset-password.php, 
goalfix/woocommerce/myaccount/my-orders.php, 
goalfix/woocommerce/myaccount/navigation.php, 
goalfix/woocommerce/myaccount/orders.php, 
goalfix/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0, 
goalfix/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.0.0, 
goalfix/woocommerce/single-product/rating.php, 
goalfix/woocommerce/single-product/review-rating.php version 2.6.0 is out of date. The core version is 3.0.0, 
goalfix/woocommerce/single-product/short-description.php`

**Comment by typeplus** [comment]
I am going through these so will submit a push later on today.

**Comment by jhob101** [comment]
The product gallery also needs looking at as part of this. Sure you're on that though!

**Comment by typeplus** [comment]
@jhob101 We will get it fixed. Its to do with woocommerce theme support not being enqueued as well as the FlexSlider being required. I have partially enabled support for the Product Gallery 3.0.0 but we need to get the issue of FlexSlider resolved as it's required by the new gallery. I think they recently allowed it to be used with another slider but I don't have time to check (see here [Link](https://github.com/woocommerce/woocommerce/pull/13009)

I have created a pull request here for the template updates to 3.0.0 support:  #283

**Comment by typeplus** [comment]
Pull request went awry..... Issues with files I didn't even touch!

**Comment by holger1411** [comment]
I merged your changes here:
fde1960
I fixed some problems...the build was failed because of some changes to the WP validator...even the underscores starter theme from Automattic failed the tests ;-)
So it isn´t a real problem at this point.

It will be in the final release 0.6.0
Going to release this soon. There are just smaller issues I need to fix first.

Its already available if you use the big green "clone or download" button here on GitHub. Than you get the "bleeding edge" version.

**Comment by typeplus** [comment]
Awesome work thanks Holger!

Admittedly I have very little idea when it comes to PHP validation and hadn't been able to consistently get phpcs to find issues properly. I also wasn't aware that travis CI issues weren't life threatening 😆. Thanks for checking these out and hope itwasn'tt too much of a headache to go through.
