### ISSUE TITLE
Default WP styles not loading?

### ISSUE THREAD

**Issue by Jurero123** [holger1411/understrap#28]
Hi, 

first of all I would like to thank you for awesome starter theme.

I have one issue I can not figure out. I am building a theme and I tried adding a gallery to a post and I noticed that default WordPress styles are not being loaded (wp-content.css). I was sure I did something wrong, but then I installed your latest theme and added a gallery and it is still not working. Pictures are displayed vertically no matter how many columns I choose in a gallery.

Thank you in advance,
Jure
![capture](https://cloud.githubusercontent.com/assets/9927764/15226202/041461f4-1882-11e6-92c2-d7496b5e9f8d.PNG)

**Comment by holger1411** [comment]
Hi!
Thx for your help.
WordPress don´t load any default styles in frontend by default...so its up to the theme itself to style this the right way. 
I need to fiddle out how I can overwrite the default markup with the Bootstrap markup...

**Comment by holger1411** [comment]
As a quickfix you can add:
.gallery {width:100%;float:left;}
.gallery figure {float:left;}

to your sass/css file.

**Comment by petenorris** [comment]
I'd like to echo what Jurero123 said - great job and thanks! Combining _S, gulp and BS4 is exactly what i've been doing, but maintaining has become a chore.

There are some specific WP styling elements that I feel could be included - I have imported the WP Theme unit test (https://codex.wordpress.org/Theme_Unit_Test) and on the 'image alignment' post, the large images are distorted and the aligned left and right touch the text (no margins).

Adding the following fixes it all (borrowed from twentySixteen), but would rather this was part of the theme?

img {
	max-width:100%;
	height:auto;
}

.alignleft {
	float: left;
	margin: 0.375em 1.75em 1.75em 0;
}

.alignright {
	float: right;
	margin: 0.375em 0 1.75em 1.75em;
}

.aligncenter {
	clear: both;
	display: block;
	margin: 0 auto 1.75em;
}

blockquote.alignleft {
	margin: 0.3157894737em 1.4736842105em 1.473684211em 0;
}

blockquote.alignright {
	margin: 0.3157894737em 0 1.473684211em 1.4736842105em;
}

blockquote.aligncenter {
	margin-bottom: 1.473684211em;
}

**Comment by petenorris** [comment]
@Jurero123 You could also add the following for your WP gallery - again borrowed from twentySixteen:

.gallery {
	margin: 0 -1.1666667% 1.75em;
}

.gallery-item {
	display: inline-block;
	max-width: 33.33%;
	padding: 0 1.1400652% 2.2801304%;
	text-align: center;
	vertical-align: top;
	width: 100%;
}

.gallery-columns-1 .gallery-item {
	max-width: 100%;
}

.gallery-columns-2 .gallery-item {
	max-width: 50%;
}

.gallery-columns-4 .gallery-item {
	max-width: 25%;
}

.gallery-columns-5 .gallery-item {
	max-width: 20%;
}

.gallery-columns-6 .gallery-item {
	max-width: 16.66%;
}

.gallery-columns-7 .gallery-item {
	max-width: 14.28%;
}

.gallery-columns-8 .gallery-item {
	max-width: 12.5%;
}

.gallery-columns-9 .gallery-item {
	max-width: 11.11%;
}

.gallery-icon img {
	margin: 0 auto;
}

.gallery-caption {
	color: #686868;
	display: block;
	font-size: 13px;
	font-size: 0.8125rem;
	font-style: italic;
	line-height: 1.6153846154;
	padding-top: 0.5384615385em;
}

.gallery-columns-6 .gallery-caption,
.gallery-columns-7 .gallery-caption,
.gallery-columns-8 .gallery-caption,
.gallery-columns-9 .gallery-caption {
	display: none;
}

**Comment by holger1411** [comment]
Hi! Yep, thats the job of a theme.
The problem is that this is another CSS grid system. 
But Bootstrap is already a nearly perfect grid system and it comes already with this theme. So instead of adding another CSS component for it, my plan is to filter the default gallery markup so that it uses the BS classes for an image grid. So I don´t have to maintain two differend grid´s with anything around it (especially responsive layout) but just one.
Less code, more consistency etc.

But to do this I have to find out how I could filter and edit the default gallery template markup...
Its on my list...but more in the middle of it.

**Comment by Jurero123** [comment]
@petenorris Thank you for posting a fix, I already solved this. I was actually trying to ask the same thing as you did.

@holger1411 That "feature" would be an awesome improvement. It can be a bit confusing at the moment. Thank you again for awesome work, will donate next time I download Understrap.

Btw, do you happen to know if it is OK to use your latest version with BS4 for a Themeforest theme?

**Comment by holger1411** [comment]
Digging deeper into this (thx to this article: http://robido.com/wordpress/wordpress-gallery-filter-to-modify-the-html-output-of-the-default-gallery-shortcode-and-style/).

Seems I can overwrite the default output easily, BUT 3rd party gallery plugins relay sometime on this markup. Means they will not work without the default markup...have to think about it. Maybe it is easier to just add some basic styling for it...

@Jurero123 
UnderStrap is released under GPL2 (like WP itself). As long as you release your version under the same license you can use UnderStrap as foundation for commercial themes and sell it on themeforest. 

And even better: I will support it. Let me know if you have publish a UnderStrap based theme and I will add a section to understrap.com with a screenshot and a link (maybe with an affiliate parameter on it;-)) to it.

**Comment by Jurero123** [comment]
I know about UnderStrap licence, but what I meant is if it is ok to use BS4 as a framework for a premium theme on Themeforest since it is still in alpha? Their review team is not really author friendly. 

I will let you know when it is about to be published. I am working on this theme with a friend as a side project, we are both full time employed so it can take another month or 2. :)

**Comment by petenorris** [comment]
A good point about supporting third party plugins - and perhaps this goes beyond just the gallery.
Perhaps if the WP markup stays consistent, and somehow a Sass function would interpret that into the BS styling? Although if this was a solution, I imagine keeping things maintained would be a pain.

As you say, perhaps adding a _wp.scss is the way to go.

**Comment by holger1411** [comment]
@Jurero123 As far as I could see TF offers BS4 HTML templates already: http://themeforest.net/item/marino-bootstrap-4-dashboard-ui-kit/15735840?s_rank=1
So I´am sure they will accept WP themes based on BS4. 

@petenorris : Filters and hooks are the best practices in WP and WP themes and normally clean coded plugin´s should work with it without problems. But not every plugin is well coded...hm.

Will try both solutions and test it with the most common gallery plugins...

**Comment by holger1411** [comment]
Hey guys, I add a gallery filter: https://github.com/holger1411/understrap/commit/3703c131711c835a0b955551a0417eae454b63ad

It based on Jeff Hays I mentioned before:  http://robido.com/wordpress/wordpress-gallery-filter-to-modify-the-html-output-of-the-default-gallery-shortcode-and-style/

I adjust it so that BS markup comes out instead of the defaults.
Basically it adds a "row" class around the Gallery, calculates the columns and adds the correct "col-md-xy" class to it based on this calculation.
It adds just some classes, so it is "minimally invasive".

It seems to work good...But I check it with the WP default gallery from the unit test xml file only.
Maybe you can check it on your sites and report issues?

Thx in advanced! Especially to @Jurero123 for reporting this issue

**Comment by Jurero123** [comment]
@holger1411 No need to thank me, I should thank you. :) I will do some testing on the weekend. There are few gallery plugins I used before and are easy to use for end customers. Will keep you informed.

**Comment by Jurero123** [comment]
@holger1411 So far so good. I just switched from UnderStrap with BS3 to your latest version and everything is working out of the box. 

P.S. not sure if I overwrote it somehow (will check today), but img by default does not have width:100%; and height:auto;

Keep up the good work!

**Comment by holger1411** [comment]
Hm, no I use "max-width:100%". If I would use "width:100%" even a tiny 150px thumbnail will be stretched to full size.
But "height: auto" was missing. 
Changed it in my last commit: https://github.com/holger1411/understrap/commit/63f8dc860ec2ad7e692e317d1606ba3d92d46466

**Comment by Jurero123** [comment]
max-width is what I meant yes :+1:
