### ISSUE TITLE
Browsersync slow

### ISSUE THREAD

**Issue by paulclifford** [holger1411/understrap#281]
I'm using the provided child theme; Browsersync is working but it's very slow - takes about 8-9 seconds each save to refresh. Output from the terminal is:

[15:49:03] Starting 'sass'...
[15:49:04] Finished 'sass' after 641 ms
[15:49:04] Starting 'cleancss'...
[15:49:04] Finished 'cleancss' after 5.72 ms
[15:49:04] Starting 'cssnano'...
[BS] File event [unlink] : css/child-theme.min.css
[BS] File event [unlink] : css/custom-editor-style.min.css
[15:49:08] Finished 'cssnano' after 4.57 s
[BS] File event [add] : css/child-theme.min.css
[BS] File event [add] : css/custom-editor-style.min.css

Anything I can do to speed this up? I've used Browsersync before and it was much faster.

**Comment by kpschaper** [comment]
Please check this issue: https://github.com/holger1411/understrap/issues/197
Changing out cssnano for gulp-clean-css can speed up things
