### ISSUE TITLE
Child Theme - Why should I use it?

### ISSUE THREAD

**Issue by hottehead** [holger1411/understrap#284]
Hey,

I've got a general question regarding the child theme.

Im currently developing a theme based on understrap. I choose to develop with the child theme because using child themes is best practice in wordpress world. But meanwhile I think simply using the parent theme is much better. Understrap is more of a framework than a theme? Shouldn't I simply pull this repo and develop my theme in a new branch? In fact everything you build with understrap is a parent theme not understrap itself.

At the moment I have the overhead of installing the parent theme in the same version as the child dependency. The child itself installs understrap via npm. It then copies sass files from there to produce only one css file. If the parent gets updated I have to update the child dependency as well. They essentially only share PHP files. Why should I use the child theme? Am I missing some major benefit?

Eager to hear your opinions!

**Comment by holger1411** [comment]
Basically its up to you: You can use UnderStrap as starter theme and use it as starting point for your own parent theme, or you use it as framework and use it along with a child theme.
Or, a third way: Develope a child theme besides the parent theme and at the end merge it into just one parent theme you can ship.

The UnderStrap child theme is a nice way to separate the php files (especially the functions.php) and SASS. Yes, the child pulls everything from the parent into its own sass folder, but you can change and manage the main .scss file to add new stuff, overwrite defaults etc.

So at the end there is not "right" or "wrong". It depends more on your own workflow and the needs of your actual project.

**Comment by hottehead** [comment]
Thanks for the response holger. In the end I definitely want to have one single shippable theme which acts as a parent theme. I'd like to have only one theme shown in the WP backend. I already did the third way and merged my work back into the parent. But I would't recommend that if you have lots of code. It's a little error prone. I recommend altering the parent so the new theme can be a parent theme itself. 

Thanks for the great foundation =)
