### ISSUE TITLE
toggler and navbar bramd

### ISSUE THREAD

**Issue by neerbappoo** [holger1411/understrap#289]
I added the toggler button to the right by adding css class navbar-toggler-right to the button of my nav bar which is fixed-top.
Unfortunately both navbar brand image and toggler button are overlapping when browser reached 574px width.

`<nav class="navbar fixed-top navbar-toggleable-sm  navbar-light bg-faded">

            <?php if ( 'container' == $container ) : ?>
            <div class="container">
                <?php endif; ?>

                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
![starpress just another wordpress site](https://cloud.githubusercontent.com/assets/8381087/25118870/09c33d24-2429-11e7-878b-ffda2c0cb42b.png)
`

Any help will be appreciated

**Comment by holger1411** [comment]
The problem is that the toggle is absolute positioned with "right:1rem" on the right corner of the navbar container.
If your logo is too big it will float over it.

you can try:
.navbar-toggler-right {right:0;}
to overwrite it.

**Comment by neerbappoo** [comment]
Thanks,

Actually this worked for me

`@media (max-width: 576px) {
    nav .container {
        width: 100%;
    }
}`
