### ISSUE TITLE
[Suggestion] Add version number in Download Name

### ISSUE THREAD

**Issue by poomato** [holger1411/understrap#294]
Right now I'm on Understrap(6).zip

When downloading from the website, how about adding the version number at the end like Github.

Understrap-0.6.0.zip

👍

**Comment by typeplus** [comment]
Head to the releases page;
https://github.com/holger1411/understrap/releases

They are numbered there.

**Comment by holger1411** [comment]
Another problem with version numbers in file names it that the installation folder will have the same name instead of just /understrap if it is installed manually.
Then there might be problems with child themes or some plugins looking for a folder named exactly like the theme.
