### ISSUE TITLE
Align menu to right

### ISSUE THREAD

**Issue by Fision** [holger1411/understrap#296]
I tried to align menu to left. In [Bootstrap 4 navbar](http://www.quackit.com/bootstrap/bootstrap_4/tutorial/bootstrap_navbars.cfm) it's supposed to just use class "pull-md-right" in ul tag. But this isn't working and anything else I try also doesn't work. 

How do I do it to align menu right?

**Comment by typeplus** [comment]
Check #288 unless you mean something different? A screenshot would help if that's the case.

**Comment by washaweb** [comment]
To align menu right, add ˋmr-autoˋ to the navbar-nav : ˋnavbar-nav mr-autoˋ.

**Comment by Fision** [comment]
I checked #288 but it dosen't work. I also tried before with pull-xs-right but didn't work. 
Now I treid with mr-auto but i doesn't work. Take a look at screen-shot where you can see code. 
I use understrap 0.6 and for now I did only slight changes to source code.

Screenshot: ![sc](https://cloud.githubusercontent.com/assets/1728196/25381228/28406b98-29b3-11e7-81c7-32fa77bbbbe6.jpg)

**Comment by Fision** [comment]
I closed it by mistake. It's not solved so I reopened it.

**Comment by typeplus** [comment]
Of course `mr-auto` isnt going to work... it means `margin-right:auto!` you either need to use the proper class `ml-auto` or follow my suggestion in #288 which absolutely does work and I posed a screenshot showing it works and the code.

**Comment by washaweb** [comment]
You're right, sorry for my mistake.

**Comment by Fision** [comment]
Great, it works. "ml-auto" is right class. Even in #288 it's written wrong mr-right.

Thank you for your help.
