### ISSUE TITLE
form login woocommerce

### ISSUE THREAD

**Issue by neerbappoo** [holger1411/understrap#297]
Line 31 in form-login.php, maybe add row class to 
`<div class="u-columns col2-set" id="customer_login">`

Line 73 in form-login.php maybe should be corrected from
`<div class="u-column2 col-2">`
to
`<div class="u-column2 col-md-6">`

**Comment by holger1411** [comment]
Thx @neerbappoo 
Done it here:
https://github.com/holger1411/understrap/commit/0d3ae1e7ded9fafa21ab5892261a808d26075674#diff-89fb0f623cc42553a43402c3a8dd4af7
