### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by pierreka** [holger1411/understrap#3]
After have copied the theme on the themes directory, I run "bower install" and "npm install" to install dependencies and plugins. 

When I run "gulp watch", I ve a error
"Segmentation fault: 11"

Did you know why?
The process is it correct?

**Comment by holger1411** [comment]
Hm, that can happen if there is a missing ";" at the end. Could you post the file and line number the error message pointet to? Strang ething is it works here.

Do you add your own SASS somewhere?
