### ISSUE TITLE
Starter or parent?

### ISSUE THREAD

**Issue by bitwombat** [holger1411/understrap#30]
One clarification the README could maybe use...

Is understrap meant to be used as a starter theme (like underscores) where I'm editing/adding files to it?  Or is it meant to be used as a parent theme that I don't touch?

**Comment by holger1411** [comment]
Hi! Thx for your feedback.
Its a theme framework, so its up to you what you do inside this "frame". You can use it for both ways, as starting ground for your own theme or as parent theme for your own child theme.

I add a sentence about it to the readme, see: https://github.com/holger1411/understrap/commit/380af3098d018d1ac5aef494ccd36dccad916edf

**Comment by bitwombat** [comment]
Beaut, reads well.  I hope that was useful feedback.  Understrap's a great idea!

**Comment by holger1411** [comment]
:thumbsup: :thumbsup: :thumbsup:
