### ISSUE TITLE
Declare WooCommerce support?

### ISSUE THREAD

**Issue by shaekuronen** [holger1411/understrap#300]
I'm getting a message that the theme does not declare WooCommerce support. Not sure if it's a big deal, but just wanted to give you a heads up.

![screen shot 2017-05-02 at 5 17 54 pm](https://cloud.githubusercontent.com/assets/537283/25644553/fb93af70-2f5b-11e7-994a-d6eb98d4c767.png)

Links to these [docs](https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/?utm_source=notice&utm_medium=product&utm_content=themecompatibility&utm_campaign=woocommerceplugin)

**Comment by typeplus** [comment]
Text domain was changed to 'understrap' from 'woocommerce' in the inc/woocommerce.php file. I may be wrong but I thought you had to specify 'woocommerce' there and not the theme name. That's why the warning is appearing.

**Comment by holger1411** [comment]
Merged https://github.com/holger1411/understrap/pull/301 so Iam closing this.
Thx for finding the error (@shaekuronen) and fixing it ( @typeplus  ) !!
