### ISSUE TITLE
How to make parent navigation link clickable?

### ISSUE THREAD

**Issue by JDVirtual** [holger1411/understrap#303]
Great theme! Love it so far.

So I have a Services main navigation item, and then 3 items below it.

- Services
   > Service #1
   > Service #2
   > Service #3

I'd like to have the main Services, parent page be clickable and for a user to go that page! Currently you can't, if you have any children pages in the drop down.

Any idea how I can do this?

**Comment by typeplus** [comment]
You can do this but it requires hover (or javascript), but then what about mobile or tablet / non computer devices? They don't have hover! You would then need to use some javascript and make it a double tap option and it just gets very unintuitive. If you still want to go ahead and do it, have a look here;
#54

**Comment by JDVirtual** [comment]
@typeplus Ah, okay! Makes sense.

Would the best alternative here then just be to add that Services page, under Services then?

So it would be:

- Services
   - Services
   - Service #1 
   - Service #2 
   - Service #3

**Comment by Thomas-A-Reinert** [comment]
Probably - yes. Make sure to design "Services" (and its wording (on the submenu)) as appealing and calling-to-action as you´d do with the "Services" main menu item. 
Also make sure to lead users in-depth from there and to commuicate what its good for. Remember: You usually have only three clicks until users quit..

**Comment by holger1411** [comment]
And keep in mind it will breake the mobile navigation. On mobile devices you have no "hover" effect so you need to cklick on something. but if that click opens a new page instead of the dropdown you have a problem because no mobile device user can use the dropdown anymore.
So it´s not a bug but the correct mobile behavior pattern.
