### ISSUE TITLE
How to make a full-width navbar?

### ISSUE THREAD

**Issue by JDVirtual** [holger1411/understrap#304]
By default, the logo / navigation items are within the container. I'd love to bring these items to be full-width!

I've tried changing the container to container-fluid, things just break.

Any idea?

**Comment by typeplus** [comment]
You can either set in customizer under 

**Theme Layout Settings > Container Width > Full Width Container** or if you want the pages within the grid and the Navigation to be full width add a class such as `.nav-container{width:100%;}` to the Container div;

![image](https://cloud.githubusercontent.com/assets/20927976/25769538/19e5d2a8-325b-11e7-9122-8b91d3e80f7a.png)

There are a number of other ways to do it as well.

**Comment by holger1411** [comment]
Or if you just want to have the navbar full width remove this:
```
		<?php if ( 'container' == $container ) : ?>
			<div class="container">
		<?php endif; ?>
```
in header.php from line 38 - 40 and the closing </div> in line 77

**Comment by JDVirtual** [comment]
@typeplus @holger1411 

Awesome! Thanks guys!
