### ISSUE TITLE
Navigation bar not displaying all item when resized

### ISSUE THREAD

**Issue by SkipperNatsume** [holger1411/understrap#305]
Hi. I add a few more menu location into the navigation bar, but when resized into mobile, it show only the first menu for some reasons. 
This is how I add more menu in the header.php

`<?php wp_nav_menu(
					array(
						'theme_location'  => 'second-menu',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>`
I added 5 extras, making a total of 6 menus
This is how the page look normally:
![capture3](https://cloud.githubusercontent.com/assets/17261486/25769326/d06b77c2-321e-11e7-8cfa-00c19dad8cf4.PNG)

This is how it only show 1 menu:
![capture4](https://cloud.githubusercontent.com/assets/17261486/25769332/dba665fc-321e-11e7-9e7f-ff3ca13e3d10.PNG)

Can someone tell me what I am doing wrong?

**Comment by typeplus** [comment]
Can you show us what the source code looks like (chrome inspector is fine)?

**Comment by SkipperNatsume** [comment]
This is the functions.php file:
[functions.php.txt](https://github.com/holger1411/understrap/files/980756/functions.php.txt)

This is the header.php file
[header.txt](https://github.com/holger1411/understrap/files/980753/header.txt)

They are both quite long so I put them in the text files.

I have only edited these 2 files when getting the problem, so everything else should be the same as the original.

**Comment by typeplus** [comment]
Just a screenshot of the chrome inspector (F12) showing the elements and the css on the right is fine. If you don't use chrome, Internet Explorer and Safari or Moz have this ability as well.

**Comment by SkipperNatsume** [comment]
Here is what I've got from the inspector:
![capture5](https://cloud.githubusercontent.com/assets/17261486/25772114/e255a226-326b-11e7-9a66-00cff26867de.PNG)

**Comment by SkipperNatsume** [comment]
I managed to solve this problem by removing the "container_class, container_id, and menu_class" from all of the wp_nav_menu and put all of them in the <li></li> of `<div class="collapse navbar-collapse myNavbar "><ul class="nav navbar-nav"><li>..</li></ul><div>` and calling `data-target=".myNavbar"` in the button instead. 
Now it work as what I wanted it to. I hope this help someone in the future.
