### ISSUE TITLE
WooCommerce support issue

### ISSUE THREAD

**Issue by umerkakar** [holger1411/understrap#306]
Hello,
When we install WooCommerce and activate it. It display an error that theme not support WooCommerce. So, I just debug and found that framework have an issue error that is mistakenly update. 
understrap > inc > woocommerce.php on line 13 
		add_theme_support( 'understrap' );

I have changed understrap to woocommerce and after that line code looks like that.
		add_theme_support( 'woocommerce' );

And issue solved. So, I will recommend to look into the issue. So, other will not dig into it to solve the issue next time.
Have a good day.

**Comment by typeplus** [comment]
There is a request under #301  😃

**Comment by umerkakar** [comment]
That is good if its already in report. As now I am creating a theme for client for woocommerce support. So, noticed it. Before that made lot of themes with understrap but without woocommerce. 
Will say keep it up.

**Comment by holger1411** [comment]
#301 was merged. Thx to both of you!
