### ISSUE TITLE
WooCommerce my account page

### ISSUE THREAD

**Issue by umerkakar** [holger1411/understrap#309]
Hello Mates,
I have found an issue on my account page of WooCommerce in understarp.  When you are logged out from wp-admin and visit the page. Then it loads login and registration boxes from login template or WC.

The login box have 6 col div and registration box have 2 col width. And both are out from a row div. And that making the look of the page worst. So, I did some changes as mentioned before. Added a row div and then change registration col 2 to 6. So, both boxes are equal.
Hope that can help to fix the issue. Have a good day.

**Comment by typeplus** [comment]
This is what I see ( understrap 0.6.0 );

![image](https://cloud.githubusercontent.com/assets/20927976/26022590/71ba8d92-37e8-11e7-8b7a-0754010f3e38.png)

Looks like it's already two 6 columns and inside a row. Do i misunderstand you?

For others be sure to set the option **Enable customer registration on the "My account" page.** under Woocommerce > Settings > Accounts.

**Comment by umerkakar** [comment]
I don't know if there is any difference in your and mine copy of the theme. As I share the issue in 0.6.0.
Here is the screenshot from form-login.php

![screenshot_1](https://cloud.githubusercontent.com/assets/11842713/26023107/a8c4b96c-37ce-11e7-8152-d2b6c3e53991.png)

**Comment by typeplus** [comment]
The one in the repository;
https://github.com/holger1411/understrap/blob/master/woocommerce/myaccount/form-login.php

I think it's `col-md-6 + col-md-6` inside `col2-set row`. Maybe you have a different version, or maybe I am just too tired!

**Comment by umerkakar** [comment]
I have the latest version of understrap 0.6.0. Or maybe the version you are viewing and the version I have downloaded, have different files. I got it from understrap website.
Yeh, the link you mentioned above is okay. Then you need to check public versions and your master versions.

**Comment by typeplus** [comment]
The master looks normal so I would just copy it over mate.

**Comment by holger1411** [comment]
Yes, it was fixed after the 0.6.0 release and will be shipped with 0.6.1.
Here is the commit:
https://github.com/holger1411/understrap/commit/0d3ae1e7ded9fafa21ab5892261a808d26075674
