### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Studioartcz** [holger1411/understrap#31]
Hi, 

are this theme under MIT license?
Can you add license to readme?

thanks

**Comment by holger1411** [comment]
Hi!
It is released under the terms of the GPL version 2 or (at your option) any later version (same like WordPress).
I added some infos to the readme.md file, too.

**Comment by holger1411** [comment]
See https://github.com/holger1411/understrap/commit/316e0c7cfcb7a3fa3586c52e9e9e68c50b4dc3d1
