### ISSUE TITLE
How should I work with sass files?

### ISSUE THREAD

**Issue by ewtstudio** [holger1411/understrap#310]
Hello All,
I am making changes to the sass/theme/_theme.scss file. But I can not see the result is on the frontend. There is no change. Where am I making mistakes?
I will be grateful for any help you can provide. 
Thank you very much & Kind Regards,

**Comment by Thomas-A-Reinert** [comment]
You should follow instructions in the documentation on how to set up your environment. Check https://understrap.github.io/#developing .
Closing the topic - in case you need further help, feel free to reopen it, okay?
