### ISSUE TITLE
Infinite Scrolling by jetpack not working

### ISSUE THREAD

**Issue by umerkakar** [holger1411/understrap#312]
Hello mates,
I am trying to achieve infinite scrolling via load more button. But it's not working. Everything looks okay in theme and also in the jetpack settings. Everything is normal.
But it's not working in both modes with load more buttons and without load more button. 

![1](https://cloud.githubusercontent.com/assets/11842713/26029971/b9822e2c-385c-11e7-88cf-13a58bca64a9.png)
![2](https://cloud.githubusercontent.com/assets/11842713/26029972/b9985f4e-385c-11e7-81c6-a63baec8a63c.png)
![3](https://cloud.githubusercontent.com/assets/11842713/26029976/d209efd4-385c-11e7-81c8-e5da6d023f07.png)
Can you please guide me where is the issue?

**Comment by typeplus** [comment]
What function did you add to declare theme support? did you add any template declaration either?

**Comment by umerkakar** [comment]
I haven't declared any function. As found jetpack.php that have declared functions. So, just active the plugin option for infinite scrolling. And hide pagination using CSS.
The id for main and footer looks also okay in settings. When I press load more button. There is loading icon and then disappear without loading anything. Yet, not debugged the issue. Because wanted to know before, from you. If, its an issue or not for you.

**Comment by typeplus** [comment]
I just had a go and get the same thing. Not great with with ajax so hoping someone else can chime in.

**Comment by umerkakar** [comment]
Yeh, there is some issue. I am now on my seat to start work on the client project. I will also try to debug the issue. I will update here if I failed or successful here. And waiting for updates from you also.

**Comment by typeplus** [comment]
#323 Should fix this issue mate.

Also instead of hiding the pagination via css you could just remove or comment out line 62 of the index.php file.

**Comment by holger1411** [comment]
Close this for now - thx to both of you!

**Comment by Copylefter** [comment]
Same problem. Clean understrap Version: 0.8.0 and last Jatpack
