### ISSUE TITLE
How to increase the width of the drop-down menu?

### ISSUE THREAD

**Issue by JDVirtual** [holger1411/understrap#319]
I'd like to be able to increase the width of the dropdown menu. 

As you'll see in the screenshot, the width is pretty thin. I tried adjusting the padding - it did increase the width of the drop-down menu itself, but the text didn't actually spread out.
![dropdown](https://cloud.githubusercontent.com/assets/28408167/26124514/ba5a42ca-3a4c-11e7-94ec-b271d7d4da2b.jpg)

Is there anyway to do this?

**Comment by typeplus** [comment]
`.dropdown-menu` is one class you could alter. It currently has `min-width:10rem;` try increasing that to suit your needs. You could also alter the  `li`, or `a` padding there depending on what you have going on.

**Comment by JDVirtual** [comment]
@typeplus increasing the min-width on .dropdown-menu did it! Thank you very much!
