### ISSUE TITLE
Mobile menu doesn't work fine

### ISSUE THREAD

**Issue by andreavigani** [holger1411/understrap#32]
The mobile nav not works the right way. When you tap the toggle icon it starts and animation with vertical menu, and then it put all nav items horizontally.

![issue-mobile nav](https://cloud.githubusercontent.com/assets/6072750/15857852/d3936a0c-2cbd-11e6-8010-ae019a828a27.png)

**Comment by dvlopes** [comment]
Same here. I have a solution for that. Will create a Pull Request soon.

**Comment by holger1411** [comment]
@dvlopes  +1

**Comment by andreavigani** [comment]
@dvlopes Could you please post your solution here?

**Comment by dvlopes** [comment]
@andreavigani I'm working on the integration of the solution into Understrap (as I've done this on another project) and will create the Pull Request in one hour or so then Holger can merge it.

**Comment by holger1411** [comment]
Hm, also working on it

**Comment by holger1411** [comment]
See https://github.com/holger1411/understrap/commit/1a761eff725f2a044d4b7715ca4cff902a7904b0
I set the menu width to 100% if it is in "collapsing" mode

**Comment by holger1411** [comment]
@dvlopes Feel free to post your solution, too.

**Comment by dvlopes** [comment]
@holger1411 I've check your solution and it seems better.
I did the same but messed with my website styles.

**Comment by holger1411** [comment]
thx to @andreavigani for reporting this issue and to @dvlopes for your support!

**Comment by TomKisielewski** [comment]
When i click on the menu toggle button while menu is expanding ( animating?)some default styles loading and my custom styles follow later. It doesn't look right. I use @media(max-width:544px){ which I think is the breakpoint for the mobile menu. Any ideas?

**Comment by holger1411** [comment]
Hi!
The default BS4 breakpoints are:
```
// Small devices (landscape phones, 34em and up)
@media (min-width: 34em) { ... }

// Medium devices (tablets, 48em and up)
@media (min-width: 48em) { ... }

// Large devices (desktops, 62em and up)
@media (min-width: 62em) { ... }

// Extra large devices (large desktops, 75em and up)
@media (min-width: 75em) { ... }
```
So @media(max-width:33em) would be the correct breakpoint for the smallest devices. Thats with 1em = 16px x33 = 528px.
So the smallest breapoint is "up to 33em" while the next one is "from 34em"
Means that your changes overwrite the default between 528px and 544px

**Comment by TomKisielewski** [comment]
Thanks for your help, it still doesn't work, but it is my "custom" theme so I will need to try with fresh install of understrap. It is the most likely my fault. Have you considered to open mailing list so people could seek help with things which are not really issue with framework itself. I have noticed that understrap is finally on wordpress.org so there will be more different issues soon.
