### ISSUE TITLE
Tab is not working properly

### ISSUE THREAD

**Issue by surajkhanal** [holger1411/understrap#324]
I am using the understrap as my startup theme. When i implement the tab component, the tab is not opening automatically but it does when i click to the next tab button and again to the initial tab button.
![image](https://cloud.githubusercontent.com/assets/16777752/26196231/0d8522c0-3bde-11e7-8a69-826ff66108d1.png)

**Comment by holger1411** [comment]
Hi!

Works here perfectly:
https://understrap.com/understrap/?page_id=2
So it seems its not a genereal Bootstrap or UnderStrap bug.
More an issue how and where you integrate it.
Could you post the URL or the source code for the tab component you use?
