### ISSUE TITLE
Toggable Nav Tabs/Pills not working

### ISSUE THREAD

**Issue by andreavigani** [holger1411/understrap#33]
1.Missing style for nav tabs/pills. (it's not a problem, it's easy to implement)

**2.Toggable nav tabs/pills work only on first interaction.**

Es. TAB A | TAB B | TAB C
If I click A, then B, then C it works, but If I try to re-click any of them it doesn't work.

**Every tab work for only once.**

**Comment by holger1411** [comment]
Hi!
Could you post a link? 
Than I can take a deeper look into it.
