### ISSUE TITLE
Bootstrap boxed width .contrainer class

### ISSUE THREAD

**Issue by kayacanakin** [holger1411/understrap#34]
Hello,
I'm trying to change Understrap theme from full-width to boxed-width. I couldn't find an option in Wordpress, so I tried to make it in CSS but Bootstrap classes doesn't work for me.

Does Bootstrap classes works in Understrap?
Does Understrap supports or prevents boxed-width?
Is there any ready to use way to make it boxed-width instead drowning in css?

Thanks.

**Comment by kayacanakin** [comment]
I found some bugs and fixed them. So, .container class works for now.

**Comment by holger1411** [comment]
Hi!
Yep, there is a sourrounding DIV called "site".
Add:
.site {
width: 1234px;
margin: 0px auto;
}
for a boxed layout.

Or add the Bootstrap ".container" class to this sourrounding DIV.
You find it in header.php line 26:
`<div id="page" class="hfeed site">`

Change it to:
<div id="page" class="hfeed site container">
