### ISSUE TITLE
Multi-Level Dropdown

### ISSUE THREAD

**Issue by tellstevens** [holger1411/understrap#340]
I'm running this locally so I can't provided a link. I'm wanting to add a multi-level dropdown but when I add them it's just indenting the menu-items. Any advice?
![image](https://cloud.githubusercontent.com/assets/10147938/26701373/796ef214-46e6-11e7-9796-6afcd05ba7d6.png)

![image](https://cloud.githubusercontent.com/assets/10147938/26701392/8f885f0e-46e6-11e7-9e79-56c6b97dbd25.png)

**Comment by holger1411** [comment]
Was removed from BS4 Alpha.
But here is a solution:
https://github.com/twbs/bootstrap/issues/17408
