### ISSUE TITLE
make menu pull right

### ISSUE THREAD

**Issue by wpsitexpress** [holger1411/understrap#341]
Hello:
I have found Understrap very good but I am having an issue getting the menu to pull right. I have

				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav mr-auto',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>

using mr-auto as I understand from various sources should work in BS4 - it isnt - so clearly there is something else required. Could anyone say what?

Thanks
Robert

**Comment by holger1411** [comment]
Pls see:
https://github.com/holger1411/understrap/issues/296

**Comment by wpsitexpress** [comment]
Thank You I have used "ml-auto" and also added "navbar-toggler-right" so that the collapsed mobile version is right aligned as well - Thanks

**Comment by hyprdigital** [comment]
How do I filter this in the child theme?

**Comment by holger1411** [comment]
@hyprdigital : Copy the header.php file from the parent theme into your child theme folder.
That edit this file, instead of the original header.php

WP will notice that there is a file with the same name in the child themes directory and will use this, automatically.

**Comment by hyprdigital** [comment]
@holger1411 That's what I have done as a fix. But why won't the normal WP filter classes function work on this?
