### ISSUE TITLE
Add child theme to Wordpress library

### ISSUE THREAD

**Issue by selfagency** [holger1411/understrap#349]
Please add the child theme(s) to the Wordpress theme library so that it can be installed with Composer via wpackagist.

**Comment by MikeFoden** [comment]
Shouldn't this issue be logged at https://github.com/holger1411/understrap-child

**Comment by holger1411** [comment]
The problem is that it took 8 month of my life to get UnderStrap into the Repo.
Nothing you can do over night.
And a child theme makes (normally) no sense, because its a blank canvas to add your own changes. This changes will be overwritten if you update the child theme. Thats the reason why child themes exists.
It just would make sense if you publish a child theme with it´sown design/markup/functions etc

**Comment by selfagency** [comment]
The issue, IMHO, is what happens when you want to add the blank child theme to a project as a dev dependency in Composer. When I'm scaffolding a project based on Understrap, I don't want to have to download and extract the file manually. I just want to run my Composer install and be done with it.

**Comment by holger1411** [comment]
Hm, I never worked with Composer. 
Can´t you add Git Repos as dependencies like in Bower or npm?

Nevertheless I submitted it to wordpress.org, if you want you can accompany the process:
https://themes.trac.wordpress.org/ticket/45030

**Comment by selfagency** [comment]
nah, composer annoyingly requires its own type of repos. that's why wpackagist exists— it automatically turns the wordpress theme and plugin directories into a composer repo.

**Comment by holger1411** [comment]
Ah okay. Learned something again ;-)
Now we have to wait till something happends to this thicket:
https://themes.trac.wordpress.org/ticket/45030

**Comment by Thomas-A-Reinert** [comment]
Just as a sidenote: Envato/Themeforests´ commercial themes usually include a basic child-theme in the parents folder if available. I guess it would also be pretty easy to copy it to its own folder upon parent-theme activation. So every computer-dummy would know that there is a child available.

**Comment by selfagency** [comment]
looks like for some reason wordpress rejected adding the child theme to their repo several months back. any idea why?

**Comment by crstnio** [comment]
See this long list of required things a theme within the directory must have? Plenty of reasons why a child theme will never be approved. And I don‘t think putting it into the theme and extract it automatically at activation would be a better idea.

It looks like there are ways to require GitHub repos as Composer dependencies. Google gave me some quick results.

**Comment by selfagency** [comment]
maybe try being less obnoxious when contributing to an open source community

**Comment by crstnio** [comment]
I am sorry if I hit your feelings. Was not my intention, since I am not a native speaker.
