### ISSUE TITLE
Does understrap use a CDN?

### ISSUE THREAD

**Issue by AlanaFarkas** [holger1411/understrap#351]
Hello,

I am developing a wordpress site locally using an understrap child theme and need to migrate it to an install on WP Engine. If I create a transferable install for my client to take over after the build is complete, WP Engine told me that I cannot use any CDNs as the theme will break so I'm wondering if understrap uses any CDNs. 

Thanks in advance.

**Comment by typeplus** [comment]
Understrap is just a theme (an awesome one 😄 ) and a CDN is related to the hosting. Usually you just offload your static resources to a CDN to get better performance by making the media upload directly to your CDN. When I need to for international sites I just setup a function like;
```
function cdn_url() {
    return 'http://yoursite.yourcdn.com';
}
add_filter( 'pre_option_upload_url_path', 'cdn_url' );
```
You can do the same for css and js files by altering your `wp_enqueue_style` and `wp_enqueue_script` to include the full url to the cdn they are hosted on.

There are many plugins to do this as well, but it's easy to do a few lines of code.

**Comment by Thomas-A-Reinert** [comment]
Short answer (please note that @typeplus is absolutely correct!): Nope it doesn´t. I´ll close that topic for now. Feel free to reopen if needed.
