### ISSUE TITLE
css changes not getting to browser

### ISSUE THREAD

**Issue by MichaelLSmith** [holger1411/understrap#353]
I've made some css changes in the theme.scss file. I'm running gulp watch. I see the changes in the theme.css file that gulp generates in my text editor, but the changes aren't being loaded by browser. When I look at the theme.css file in the developer tools, I don't see the changes.

I've cleared my browser's cache.

I'm using VVV, if that makes a difference.

**Comment by typeplus** [comment]
The default setup is to put your styles into `/sass/theme/_theme.scss` while running `gulp watch` and the changes will be uglified & minified and will appear in your `/css/theme.min.css`

Is that your setup?
