### ISSUE TITLE
Background-image in theme category container, where is / path ?

### ISSUE THREAD

**Issue by GU8187** [holger1411/understrap#355]
Hey I tried to add backgorund-image in div, that is custom tag related.

I can work my css as far as background-color is concerned, even tried to put existing absolute path, but dont seem to show any improvement in my solution.

I do have a paste bin, so you can overlook some code https://pastebin.com/mqjUXKUZ
This issue concerns sccs as category names are converted  via tag->slug into proper classes 
from line 19 to 26 in bin.
we'd like to have icon as container background

Here is public url
http://aludafrmbi.cluster021.hosting.ovh.net/demandes/

**Comment by typeplus** [comment]
`background-image` should be changed to just `background` in your css as you are specifying position and repeat.

**Comment by GU8187** [comment]
Thanks man, the other attributes caused some trouble. I've worked my way around using ../images as path, adding files in that /understrap/images folder
