### ISSUE TITLE
Where can I delete parts of the Understrap Styling (instead of overwriting it)?

### ISSUE THREAD

**Issue by Lalilu** [holger1411/understrap#358]
Hey guys,

I'm still new to gulp and sass, so I'm not able to answer this by myself…

If I want e.g. to get rid of FontAwesome (or at least those hundreds of lines which link to all FontAwesome symbols) to shrink the theme.min.css file size – how should I do that?

I'd be happy to hear your thoughts and approaches…

Thanks!
Martin

**Comment by typeplus** [comment]
Absolutely. The file `/sass/theme.scss` just comment out line 6 which is `@import "assets/font-awesome"; // <------- Font Awesome Icon font` while running `gulp watch`

**Comment by Lalilu** [comment]
Ah, nice!

And if I want to delete other parts?
E.g. if I'm not using breadcrumbs or parts?

Asked in a different way: Till which level does gulp watches changes? What is not watched?

**Comment by typeplus** [comment]
It can get tricky removing bootstrap 4 components but you can remove them via `/sass/assets/bootstrap4.scss`  by commenting out the ones you don't use. If you remove a component that is being used the `gulp watch` is likely to throw an error so at least you know you probably need that component.

`Gulp Watch` basically runs through a task list of things specified in the `gulpfile.js` script. You can see what it watches and ultimately what it compiles.

**Comment by Lalilu** [comment]
A little bit late, but: Thanks, Jason! :)
