### ISSUE TITLE
Without gulp, bower etc.

### ISSUE THREAD

**Issue by aneeshjajodia** [holger1411/understrap#36]
Hello,

Can I get this theme without those gulp, bower etc and just the wordpress theme?

Best.

**Comment by holger1411** [comment]
If you don´t need it don´t use it. 
You might delete the package.json and bower.json and the /src and /sass folder
In this case you have to edit the css file manually and add your stuff at the end of it.
It is much easier to change Bootstrap defaults using Gulp/Sass, but it is okay to do it good ol style

**Comment by aneeshjajodia** [comment]
The thing is, I do not have setup for all this, since am using apache and
old stuff. Get me?

..
Anish Jajodia

On 23 June 2016 at 13:50:31, Holger (notifications@github.com) wrote:

If you don´t need it don´t use it.
You might delete the package.json and bower.json and the /src and /sass
folder
In this case you have to edit the css file manually and add your stuff at
the end of it.
It is much easier to change Bootstrap defaults using Gulp/Sass, but it is
okay to do it good ol style

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/holger1411/understrap/issues/36#issuecomment-227981664>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABA3MFUtX5iCn0SWBXoGB6q2VZhhe4U4ks5qOkHOgaJpZM4I8i_c>
.

**Comment by holger1411** [comment]
You don´t need anything...just use the good old plain CSS and the PHP files and you are good to go. And of course you need a running WordPress install to test it.

You CAN use Bower, Gulp, npm, Sass etc.It will make it easier to develop your own UnderStrap version and add your own design.

But you don´t have to.

**Comment by dkrieger** [comment]
Why are sources duplicated? I'm new to using bower, so this may be a common pattern, but it seems unnecessary.

```shell
$ find . -name "_grid*" | grep -v "bootstrap-sass" | grep mixins
./bower_components/bootstrap/scss/mixins/_grid-framework.scss
./bower_components/bootstrap/scss/mixins/_grid.scss
./src/sass/bootstrap4/mixins/_grid-framework.scss
./src/sass/bootstrap4/mixins/_grid.scss
```

Also, bootstrap-sass shouldn't still be in bower_components unless I'm missing something.

**Comment by Thomas-A-Reinert** [comment]
Bower components can be updated to the latest version with a simple "bower update". Bower saves them there, but they will never be actually _used_ in your project. The Gulp task then copies them to the src-folder. These are the files you may want to change.

From there, with another Gulp task they will be translated to actually browser-usable CSS. Hope that sheds some light on it. As Holger said - just ignore the bower folder if you don´t know what to do with it/how to handle it and just work with the SCSS files if you know how to use THEM. If you also don´t know how to handle SCSS, just go with the usual flow and work with the php-files (the actual template files) and the CSS files..

Everything is absolutely alright the way its actually handled.

**Comment by holger1411** [comment]
Yep, @Thomas-A-Reinert is right. The /src folder is the working folder, /bower_components the update folder

**Comment by dkrieger** [comment]
Thanks for the clarification, it looks like I needed to do a `bower update && bower prune` . @holger1411 can you shed any light as to why working files are duplicated from bower files? Is this to simplify bower configuration or some other reason? RTFM is an acceptable answer of course, just thought I'd ask in case you have a ready answer.

**Comment by holger1411** [comment]
Its just add´s an extra portion of safety. You need to type in an extra command before you overwrite your files. Keeping external dependencies and your own stuff separated make sense, especially if you working in a team.
If you find it unhandy you might change the sass files and point it directly to the /bower_components folders. It will work, too.

**Comment by dkrieger** [comment]
Makes perfect sense, thanks for the explanation.
