### ISSUE TITLE
Woocommerce 3.1.0 updates

### ISSUE THREAD

**Issue by lutsen** [holger1411/understrap#362]
Woocommerce released version 3.1.0 and the following files are out of date:
- understrap/woocommerce/cart/cart-empty.php version 2.0.0 is out of date
- understrap/woocommerce/cart/cart.php version 3.0.3 is out of date
- understrap/woocommerce/cart/mini-cart.php version 2.5.0 is out of date
- understrap/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date.
- understrap/woocommerce/single-product/rating.php version 2.3.2 is out of date.
- understrap/woocommerce/single-product/review-rating.php version 3.0.0 is out of date.

**Comment by typeplus** [comment]
Check #359 mate.

**Comment by lutsen** [comment]
Nice!
