### ISSUE TITLE
change global css

### ISSUE THREAD

**Issue by MichaelLSmith** [holger1411/understrap#364]
Where would I change a global css setting? Such as the base font-family for all <p> tags, for instance.

**Comment by holger1411** [comment]
Basically the default SASS variables from Bootstrap 4 are in use.
If you want to overwrite em open:
sass/theme/_theme_variables.scss

There is already the default value in it as example:
`$font-family-sans-serif:Arial, sans-serif;`

Change the variable `$font-family-sans-serif` to something else than `Arial, sans-serif;` and recompile your SASS 

If you want to add your own sass classes the right place for it is here:
sass/theme/_theme.scss

For example if you just want to use another font for p tags while you use the default font for anything else add:
 p {font-family: Helvetica;}
and recompile your sass
