### ISSUE TITLE
How do I register a custom widget area?

### ISSUE THREAD

**Issue by allirense** [holger1411/understrap#366]
I attempted to register a new custom widget area to add a widget area to my header. I added this to widgets.php right under the one for the Footer Full widget area:

`		register_sidebar( array(
			'name'          => __( 'Header Right', 'understrap' ),
			'id'            => 'headerright',
			'description'   => 'Widget area in the header',
				'before_widget'  => '<div id="%1$s" class="header-widget %2$s '. slbd_count_widgets( 'headerright' ) .'">',
				'after_widget'   => '</div>',
				'before_title'   => '<h3 class="widget-title">',
				'after_title'    => '</h3>',
		) );`

I then added this to my header.php where I wanted the widget area to go:

`<?php get_sidebar( 'headerright' ); ?>`

I'm able to add widgets to the area in admin, but I'm not seeing them on the page. What am I missing?

**Comment by washaweb** [comment]
Hi, 
the correct way to call your sidebar is with the ´<?php dynamic_sidebar('headerright'); ?>´ function.

**Comment by washaweb** [comment]
Sorry something went wrong with the code: the function is : dynamic_sidebar('rightsidebar');
https://codex.wordpress.org/Function_Reference/dynamic_sidebar

**Comment by typeplus** [comment]
@washaweb is bang on.
After registering your widget area in the widgets.php just call it like so (only add if exists) in the `header.php`;

`<?php if ( !function_exists( 'dynamic_sidebar' ) || !dynamic_sidebar('off-canvas-menu') ) ?>`

**Comment by allirense** [comment]
Thanks, that works!

**Comment by peterjrees** [comment]
Can new custom widget areas be added to a child theme? I tried creating an inc folder containing  `widgets.php` in my child theme and registered the new widget  but it doesn't appear in the widget admin area?

**Comment by axlright** [comment]
Here's the WordPress documentation. This has worked for me.

https://codex.wordpress.org/Function_Reference/register_sidebar

https://developer.wordpress.org/reference/functions/register_sidebar/

**Comment by fredperes** [comment]
I added in the functions.php file, and iit worked:
register_sidebar(
			array(
				'name'          => __( 'Newsletters', 'understrap' ),
				'id'            => 'newsletters',
				'description'   => __( 'newsletters form', 'understrap' ),
				'before_widget' => '<div id="%1$s" class="footer-widget %2$s dynamic-classes">',
				'after_widget'  => '</div>',
				'before_title'  => '<h3 class="widget-title">',
				'after_title'   => '</h3>',
			)
		);

To display whatever you want:

<?php dynamic_sidebar( 'newsletters' ); ?>
