### ISSUE TITLE
Float Menu Right 

### ISSUE THREAD

**Issue by tellstevens** [holger1411/understrap#368]
I've tried everything I can think of to float this menu right towards the search button but nothing works. I've tried floating it in dev tools I've added "float-md-right" to the menu class and it does nothing. Is there something over-riding it to the left that I cannot find? 

![image](https://user-images.githubusercontent.com/10147938/28189832-677416c0-67ed-11e7-8732-0278ab0ddd19.png)

**Comment by typeplus** [comment]
Those classes were removed in the latest bootstrap 4 releases, so you need to use the class `ml-auto` as in which is `margin-left:auto;`.

**Comment by tellstevens** [comment]
![image](https://user-images.githubusercontent.com/10147938/28197604-9ff99dbe-681d-11e7-8e3f-5e06e8fcb7ea.png)
that didn't do anything either. I thought it might have something to do with the search button being on there but I removed it and that didn't do anything either.

**Comment by tellstevens** [comment]
Found the problem. I wrapped that mobile menu in another nav ID and it was adding the display: flex to it and keeping everything from affecting alignment. Thanks for looking.
