### ISSUE TITLE
Error: Cannot find module 'lodash.assign'

### ISSUE THREAD

**Issue by maxcoyote** [holger1411/understrap#369]
Following the Developing with npm & Gulp section of the docs and getting the following error:

`Error: Cannot find module 'lodash.assign'`

I am working in Cloud9 Ubuntu environment. See attached screenshot for more context.

[Error Image](http://imgur.com/EzfBkkm)

**Comment by holger1411** [comment]
Hi!
Please make sure you installed Gulp globally on your machine, too.

**Comment by maxcoyote** [comment]
Ok, I reinstalled everything and it worked the second time around. Thanks!
