### ISSUE TITLE
Understrap dropdown nav not working

### ISSUE THREAD

**Issue by mnidever** [holger1411/understrap#370]
Hi,

Dropdown navs don't appear to be working and I can't figure out why. I was using a child theme, but reverted to just use understrap to see if I could get the dropdowns to function there, but they don't work there either. I've tried reinstalling understap (and everything else I can think of), but still can't seem to make it function. Here are some screenshots of my setup:

![screenshot 2017-07-17 08 58 15](https://user-images.githubusercontent.com/22449030/28269039-852803aa-6ace-11e7-97af-e574c51c1595.png)
![screenshot 2017-07-17 08 58 37](https://user-images.githubusercontent.com/22449030/28269042-8798898e-6ace-11e7-9a2d-54c672d59784.png)

You can see it live at staging.globallearningcouncil.com.

**Comment by holger1411** [comment]
I can´t connect to your staging server...
But do you can use it here:
https://understrap.com/understrap/
? For example works the "Unit Test Page" dropdown link?

Do you see anything in your browser console / debug log / dev tools ?

**Comment by mnidever** [comment]
Thanks for getting back to me so quickly! 

I entered the wrong link for my staging server, sorry - try http://staging.globallearningcouncil.org/ 

I can't find anything wrong in the console, and it looks like the right things are happening when I click the link

![understrapgif](https://user-images.githubusercontent.com/22449030/28269407-fcbd3e7a-6acf-11e7-9300-fa261e9096e4.gif)

**Comment by holger1411** [comment]
Strange thing. Its physically there (you can select it with your browser developer tool) but not viewable.
But I get an jQuery error.
Please disable all plugins and retry it at first.

**Comment by mnidever** [comment]
Hi! Thanks for the recommendation. It looks like the plugin that was causing the issue was an older plugin I don't user anymore called 

Contact Bank Lite Edition Version 2.1.40

Now that it is disabled, everything appears to be working correctly. Thanks again for your help!
