### ISSUE TITLE
Theme name change

### ISSUE THREAD

**Issue by pevoje** [holger1411/understrap#38]
Hi,

what is the easiest way to change the theme name folder? So not to use under wraps as a default theme name, but something custom-but keep the functionality of the understrap theme.

I want to build my own theme around understrap but not as a child theme-if you understand what I want.

Thanks

**Comment by holger1411** [comment]
Just use the "find and replace" function of your editor.
Replace "understrap" everywhere with your own name

**Comment by nuthinbutajthang** [comment]
Is it necessary to replace all sources? Modifying the comment section in style.css isn't enough?

**Comment by kash101** [comment]
I tried to replace it using Atom Editor and keeping the case sensitive on, but now browser-sync is not working.

[Browsersync] Watching files...
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
[Browsersync] Reloading Browsers...

**Comment by FerhatBicakci** [comment]
Found this solution for macOS

Open your Terminal and type:
`grep -rli 'understrap' * | xargs -I@ sed -i '' 's/understrap/NEW_THEME_NAME/g' @`
