### ISSUE TITLE
Caption shortcode showing

### ISSUE THREAD

**Issue by AustinFCline** [holger1411/understrap#39]
When I add a caption to an image, the caption shortcode shows on my pages instead of underneath the image. 
 
<img width="954" alt="caption shortcode" src="https://cloud.githubusercontent.com/assets/19785806/16452927/e11b65f4-3dd8-11e6-8330-2da8de6fd73a.png">

**Comment by holger1411** [comment]
Hi!
I test it on the demo site here:
https://understrap.com/understrap/?page_id=735
without problems.
Is it possible to post/send me the link/admin account to your page? Feel free to send it to hello@understrap.com

**Comment by holger1411** [comment]
Please switch to a WordPress default theme first, and check if the problem presists.
If yes: Can it be that you copy the image code in text mode and past it in visual editing mode?

**Comment by holger1411** [comment]
Thx for the account!
I test it with the default parent theme, the default child theme and another default WP theme (twentysixteen) in all this cases the caption works fine. Just if I activate your customized version of the UnderStrap child the caption will render as shortcode.
So it must be related in some way to your changes/customizations. Especially your changes to the functions.php might cause the trouble. Revert it to  the original and try it again
Sorry that I can´t help you more with it.
I close this issue becaus eit seems it is not related to UnderStrap.
But feel free to reopen it if you find a bug in the original code.
