### ISSUE TITLE
Invalid ID for div in 404.php

### ISSUE THREAD

**Issue by VesterDe** [holger1411/understrap#392]
As per [this link](https://benfrain.com/when-and-where-you-can-use-numbers-in-id-and-class-names/) a css selector starting with a number is not valid.

That makes [this line](https://github.com/holger1411/understrap/blob/master/404.php#L15) invalid (as a possible css target, it is perfectly valid HTML).

I'll make a pull request at some point, but you're welcome to beat me to it.

Perhaps something like `#error-404`, if it isn't confusing that a class with the same name exists already?

**Comment by holger1411** [comment]
Hi!
Change that here: 
https://github.com/holger1411/understrap/commit/11a79476680568e7c384bd942d6a21ae3d2c7346

New name of that 404 wrapper id is:
`#error-404-wrapper`

Thx @VesterDe for pointing me to this issue!
