### ISSUE TITLE
Navbar-toggler-right not working since new update

### ISSUE THREAD

**Issue by JDVirtual** [holger1411/understrap#394]
Hey everyone!

So I've built many sites with this so far, and it's worked awesome.

I just downloaded a fresh copy today, and tried using "navbar-toggler-right" on the navbar-toggler button class, to essentially move the hamburger icon on mobile to the right side, and keep the logo to the left:

`<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>`

The hamburger menu icon is still on the left on mobile, and the logo actually switches to the right on mobile (even though it was on the left on desktop!)

Does anyone have a fix for this?

Desktop:
![desktop](https://user-images.githubusercontent.com/28408167/29429513-f245340a-835e-11e7-9201-c8602629c0af.jpg)

Mobile:
![mobile](https://user-images.githubusercontent.com/28408167/29429523-f9fd1ece-835e-11e7-99f6-14bb6a356a89.jpg)

**Comment by 0dp** [comment]
are you using UnderStrap version 0.6.5?

**Comment by JDVirtual** [comment]
@0dp Yes sir!

**Comment by 0dp** [comment]
@JDVirtual check my updated answer

**Comment by holger1411** [comment]
Update it here:
https://github.com/holger1411/understrap/commit/4ca76066afe41cf9f5ff4d00014f357744facc60

Just move the <button> markup belo the navbar-brand markup
Will be release with the next update. If you wanna archive it without waiting for it just use the new header.php from the master branch:
https://github.com/holger1411/understrap/blob/master/header.php
Thx @JDVirtual & @0dp for pinting this out!

**Comment by holger1411** [comment]
Close this issue. Feel free to reopen if there is still an issue with the hamburger toggle on mobile

**Comment by JDVirtual** [comment]
Thank you very much, both of you guys! @0dp @holger1411 :)
