### ISSUE TITLE
child theme variables usage

### ISSUE THREAD

**Issue by uitta** [holger1411/understrap#402]
Hi everybody.
I'm still learning so i don't know if the problem is something i'm doing wrong or if i'm missing something or if ther's something else.
I'm trying to change the default color of the theme, so i'd like to change the default blue.
There is a $brand-primary variable in the child_theme_variable.scss that doeas nothing because, i think, it's not in the _variable.scss file. Which i guess is a misprint from prior version (this variable is not present in the parent theme).
So i'd like to change the color of the theme, which i think is the $theme-color("primary") variable, used also in the &link-color.
My problem is that i'm not able to override it.
If i try

$theme-colors: (
  primary: #008A94
) !default;

i got

argument `$color` of `rgba($color, $alpha)` must be a color

Am i missing something.
How can i change the default primary color?

thanks

**Comment by uitta** [comment]
the complete error message is 

messageFormatted: src/sass/bootstrap4/_forms.scss
Error: argument `$color` of `rgba($color, $alpha)` must be a color

       Backtrace:
       	src/sass/bootstrap4/_forms.scss:280, in function `rgba`
       	src/sass/bootstrap4/_forms.scss:280
        on line 280 of src/sass/bootstrap4/_forms.scss
>>   background-color: rgba($form-feedback-invalid-color,.8);
   --------------------^

    messageOriginal: argument `$color` of `rgba($color, $alpha)` must be a color

Backtrace:
	src/sass/bootstrap4/_forms.scss:280, in function `rgba`
	src/sass/bootstrap4/_forms.scss:280
    relativePath: src/sass/bootstrap4/_forms.scss

**Comment by fullcolorcoder** [comment]
Workaround that's working for me: Edit the `_variables.scss` directly in `src/sass/bootstrap4`. Hit save on the file that includes these assets (`sass/assets/bootstrap4.scss`) while `gulp watch` is running. Disco. 

I'm using the child theme but should work on the master theme just the same. Not exactly ideal in regards to the intentions of this entire setup, but it'll get you running and there's nothing wrong with editing the variables file.

**Comment by uitta** [comment]
@steffmueller thanks a lot! for now i solved using custom varibles where i need them. I'll give it a try on my next project.

**Comment by holger1411** [comment]
The Bootstrap guys fixed that already and will ship it with the next BS4 release. Meanwhile we need that workaround.
I also use (and can confirm) the workaround described by @steffmueller 
You can also donwload the latest "bleeding edge" BS4 version from Github and place the corresponding files into /src/sass/bootstrap4 and than run:
`gulp styles`
Might work, too but will add unreleased changes to your styles
