### ISSUE TITLE
plain css

### ISSUE THREAD

**Issue by zalkowitz** [holger1411/understrap#404]
What is the name of the file that I should use to edit the css? I do not want to use SASS.

Thank You

**Comment by axlright** [comment]
Out of the box, the functions.php has the theme pulling a single css file - /css/child-theme.min.css so if you want to use your own minified css, you could rename your file to be that or you can change the name of the file / directory in functions.php to be anything you want.

**Comment by Thomas-A-Reinert** [comment]
Or you leave it as it is and enqueue another CSS-file as a overwrite. It´s totally up to you.
But honestly why won´t you use SCSS? It ain´t rocket-science and really, really worth taking the low learning curve, resulting in cleaner CSS.

**Comment by typeplus** [comment]
You dont even need to write SASS, just use CSS and it wlil be minified/uglified along with the rest of the SASS. as @Thomas-A-Reinert says just give it a go it will save you time in the end and there are many things you can do that css cant.

**Comment by zalkowitz** [comment]
My thanks to all who responded.
