### ISSUE TITLE
Nested columns not aligning properly

### ISSUE THREAD

**Issue by flipnotic** [holger1411/understrap#407]
When nesting columns inside of eachother, like so:
```
        <div class="col-sm-6">
            <div class="col-sm-8">
                <p>text</p>
            </div>
            <div class="col-sm-4">
                <img src="#" />
            </div>
        </div>
```
The col-8 and col-4 don't stay inline, for some reason, in Chrome's dev tools, they both render an infinite margin to the right, which pushes the column down.
(I don't know if I'm allowed to post links) You can view the issue here, under the "Family law section": http://108.174.153.189/~jtavocate/

**Comment by Thomas-A-Reinert** [comment]
Hi flipnotic,

I actually didn´t try it (not on comp right now), but as far as I know, you´d need another row around them, so the following code _should_ work as expected:

`<div class="col-sm-6">
  <div class="row">
    <div class="col-sm-8">
      <p>text</p>
    </div>
    <div class="col-sm-4">
      <img src="#" />
    </div>
  </div>`

Please holla if it does/does not.

**Comment by flipnotic** [comment]
@Thomas-A-Reinert That worked perfectly! Thanks a ton!

**Comment by Thomas-A-Reinert** [comment]
No problem, you´re welcome ;)
