### ISSUE TITLE
Bootstrap's offset styles missing from theme.min.css?

### ISSUE THREAD

**Issue by jamie49** [holger1411/understrap#408]
I noticed that these styles are no longer included (e.g. offset-md-1). They used to be working with previous versions of UnderStrap which I've used. Am I doing something wrong here?

**Comment by axlright** [comment]
offset classes are no longer supported in Bootstrap 4.

https://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns

"With the move to flexbox in v4, we no longer have v3’s style of offset classes. Instead, use margin utilities like .mr-auto to force sibling columns away from one another."

or

https://mdbootstrap.com/layout/layout-grid/

add justify-content-start / justify-content-center / justify-content-end / justify-content-around / justify-content-between to .row containing the columns

**Comment by holger1411** [comment]
Thx @axlright for pointing out the changes.
Close this issue
