### ISSUE TITLE
inc/security.php cannot be overwritten

### ISSUE THREAD

**Issue by ErinPo** [holger1411/understrap#409]
The two functions

no_generator()
show_less_login_info()

do not check if the function already exists like all the others do and therefore cannot be turned off from the child theme. Please someone push the change I don't have GitHub. thanks.

**Comment by holger1411** [comment]
Thx @ErinPo for reporting. Was fixed here:
https://github.com/holger1411/understrap/commit/10f5e9212e2fb56a86554be67fe8be1a38f73af9
