### ISSUE TITLE
Font Awesome not working

### ISSUE THREAD

**Issue by tellstevens** [holger1411/understrap#41]
I might be completely missing something but I see the font awesome scss file in the parent and child themes. I see where it's imported in the theme.scss file but when I add the code for a font awesome icon I'm not getting anything. Am I missing something where it has to be activated or something?

**Comment by holger1411** [comment]
Hi!
Works perfectly here. Add the github icon to the CTA button of the first slide on the demo site here:
https://understrap.com/understrap/ and it appears....hm.

Could you send me the URL of the page where it did not work? If you don´t want to post it here feel free to send it to hello{at}understrap.com

**Comment by holger1411** [comment]
Oh, and do you use the latest version(s) of parent and child?

**Comment by tellstevens** [comment]
I downloaded the parent and child yesterday. Here is the link. http://biozymeinc.com/gainsmart/ This is my first time using the Understrap and I'm not a SASS guy but I'm trying. There should be an icon in front of the search bar.

**Comment by holger1411** [comment]
Hi!
Yep, there is no Font Awesome styling in your css file.
Seems you grap some CSS from here:
http://bootswatch.com/
and overwrite the child themes css totally with it including the FA styles.
Pls just edit /sass/theme/_child-theme.scss, add your styles here and than compile the sass to css.

And another important thing: UnderStrap and its Child theme use Bootstrap 4, not Bootstrap 3. Your bootswatch code is for BS3.

**Comment by tellstevens** [comment]
Oh got it. That make sense. Thanks.
