### ISSUE TITLE
Content area width wrong with one sidebar or none at all

### ISSUE THREAD

**Issue by SeanRParker** [holger1411/understrap#410]
When I use just one sidebar, the content-area width is too wide to be on the same line (appears col-md-12 instead of col-md-8). I've bypassed by making the last else statement return col-md-8 in left-sidebar-check.php (not the correct solution, but a temporary fix).

As a result when there are no sidebars, the content area only goes 8 columns instead of 12.

I believe it may have something to do with `get_theme_mod( 'understrap_sidebar_position' );` returning `'both'` no matter what sidebars are used.

**Comment by holger1411** [comment]
Hm, works on the demo site here: https://understrap.com/understrap/?page_id=1767

Can you post the URL where that happends?
Does it appear on a single article page or all pages?

**Comment by SeanRParker** [comment]
Happens on both posts and pages. There's no URL as it's not currently live. 
Here's the child theme I'm building on: https://github.com/SeanRParker/understrap_cms

To troubleshoot I echoed out $sidebar_pos. It says `both` no matter which sidebars are active. Left sidebar alone goes above content. Right sidebar alone goes below content.

The current `left-sidebar-check.php` file in that repo has my workaround where line 38 defaults the class to `col-md-8` instead of `col-md-12`

I'm going to check this with an fresh child theme to see what happens.

**Comment by SeanRParker** [comment]
Clean child-theme didn't work. I modified the `left-sidebar-check.php` to rely on is_sidebar_active() function instead of get_theme_mod(). It works now. I'm attaching the snippet below in case somebody else hits this problem. 

Thanks for everything. The theme rocks.

```
<?php
/**
 * Left sidebar check.
 *
 * @package understrap
 */

?>

<?php
$sidebar_pos = get_theme_mod( 'understrap_sidebar_position' );
$left_active = is_active_sidebar( 'left-sidebar' );
$right_active = is_active_sidebar( 'right-sidebar' );
$both_active = is_active_sidebar( 'right-sidebar' ) && is_active_sidebar( 'left-sidebar' )
?>

<?php if ( $left_active || $both_active ) : ?>
	<?php get_sidebar( 'left' ); ?>
<?php endif; ?>

<?php {
	if ( $both_active ) {
		$html = '<div class="';
		if ( $both_active ) {
			$html .= 'col-md-6 content-area" id="primary">';
		} else {
			$html .= 'col-md-12 content-area" id="primary">';
		}
		echo $html; // WPCS: XSS OK.
	} elseif ( $right_active || $left_active ) {
		$html = '<div class="';
		if ( $right_active || $left_active ) {
			$html .= 'col-md-8 content-area" id="primary">';
		} else {
			$html .= 'col-md-12 content-area" id="primary">';
		}
		echo $html; // WPCS: XSS OK.

	} else {
	    echo '<div class="col-md-12 content-area" id="primary">';
	}

}
```

**Comment by Giorgos-pl** [comment]
I got the same issue. Thank you very much for your help Sean!

**Comment by ZacharyElkins** [comment]
Are you using the latest Understrap parent theme? This should have been fixed here:
https://github.com/understrap/understrap/commit/a068183c08a1e0533b0abc4bf9d2241a9898d4ee
