### ISSUE TITLE
CSS not taking

### ISSUE THREAD

**Issue by kaydeeweb** [holger1411/understrap#412]
Hi Holger, thanks so much for UnderStrap. I am a newbie to compiling SASS, so bear with me!

I am using BASE, the child theme provided. 

I am using NPM and the Node Sass Chokidar watcher to output the css. 

I do not want to minify my css file each time I make a change, so I added this line to the child function file, just so that on my development site I could see the changes: 

wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.css', array(), $the_theme->get( 'Version' ) );

I can see that Chokidar outputs OK as I can see them at the bottom of the file css/child-theme.css. 

However none of the changes are appearing on the front end. 

Would you give a pointer please? K

**Comment by Thomas-A-Reinert** [comment]
Check that it's correctly enquired in functions.php.

**Comment by kaydeeweb** [comment]
Hi Thomas, thanks for your response. 

In the child functions file the action and function is as follows:

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {

// Get the theme data
$the_theme = wp_get_theme();

wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.min.css', array(), $the_theme->get( 'Version' ) );
// My line below
wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.css', array(), $the_theme->get( 'Version' ) );
wp_enqueue_script( 'jquery' );
wp_enqueue_script( 'popper-scripts', get_template_directory_uri() . '/js/popper.min.js', array(), false);
wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/child-theme.min.js', array(), $the_theme->get( 'Version' ), true );
}

Is this correct?

**Comment by Thomas-A-Reinert** [comment]
I would also comment the line where it enqueues the child-theme.min.css - otherwise you´re loading the original one for no reason causing bloat, unneccessary latency while loading etc. pp.

**Comment by kaydeeweb** [comment]
Also just realised I needed change the $handle of my wp_enqueue_style, as they should be unique (https://developer.wordpress.org/reference/functions/wp_enqueue_style/). 

Working now, thanks so much!

**Comment by Thomas-A-Reinert** [comment]
Fine it works now - anway, not really neccessary to change the handle - you would delete/comment it anyway (which makes it unique then ;) )

You´re welcome.
