### ISSUE TITLE
How to remove all sidebars excluding right sidebar?

### ISSUE THREAD

**Issue by damithruwan1234** [holger1411/understrap#413]
I am creating new theme using understrap. But having left sidebar option and (both left and right sidebar option) takes too much time to testing and developing.

So I would like to download understrap with just right sidebar. I mean then users can't select the layout from customze (Under theme layout setting of wp-admin/customize.php.). It should have just right-sidebar.

How can I do it with understrap?

**Comment by MrAndreius** [comment]
inc/customizer.php
comment lines
from 74
to 92


do not worry
if the value of the variable will be different from the right

then when you activate the theme
it will be installed automatically
inc/theme-settings.php

`// Sidebar position.
$understrap_sidebar_position = get_theme_mod( 'understrap_sidebar_position' );
if ( '' == $understrap_sidebar_position ) {
	set_theme_mod( 'understrap_sidebar_position', 'right' );
}
`

**Comment by holger1411** [comment]
Thx @MrAndreius for helping @damithruwan1234  with the correct solution!
I close this now, feel free to reopen if neccessary
