### ISSUE TITLE
How to correctly add theme style

### ISSUE THREAD

**Issue by sariyanta** [holger1411/understrap#417]
Hi I'm liking this theme a lot and I want to style it to my own liking. 

Following the instruction on the code page, I added a new scss file called dsrstyle.scss in /understrap/sass/theme/. I imported it from the theme.scss located in /understrap/sass/ 

Here's what the theme.scss now look like: 
`@import "theme/theme_variables";  // <--------- Add your variables into this file. Also add variables to overwrite Bootstrap or UnderStrap variables here
@import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Change from /bootstrap3 to /bootstrap4 Watch out! just for testing in the moment!
@import "understrap/understrap";// <-------- Loads the UnderStrap defaults. Just a few classes to incorporate BS in WP

//Optional files - If you dont use the corresponding scripts/fonts comment em out
@import "assets/font-awesome"; // <------- Font Awesome Icon font
@import "assets/underscores"; // <------- Underscores media styles

// Any additional imported files //
@import "theme/theme";  // <--------- Thats where you can add your own design. Thats your part!
@import "theme/contact-form7"; // contact form 7 - Bootatrap 4 support

@import "theme/dsrstyle"; // <--- my new theme`

And here's what I wrote on the dsrstyle.scss to test if it's working for me.

`#wrapper-footer {
  background-color:#000;
}
`

I reloaded the website so many times, but nothing changed. I'm developing the website locally with xampp. What did I do wrong? 

Regards, 

Sariyanta

**Comment by typeplus** [comment]
You are running `gulp watch` aren't you?

**Comment by sariyanta** [comment]
Okay, I need to learn what that is. Hahaha extreme noob here... Thank you






On Tue, Sep 26, 2017 at 11:29 AM +0800, "Jason King" <notifications@github.com> wrote:












You are running gulp watch aren't you?

**Comment by typeplus** [comment]
All good, just follow the install procedure and when developing make sure you run `gulp watch` from the command line in the understrap folder. It will make sure any changes made to sass are compiled and hence visible.

**Comment by sariyanta** [comment]
Thank you so much :), I managed to do it with gulp watch. 

Do I have to install node.js also on my cpanel? Now I'm developing locally with xampp using vhosts.

**Comment by Thomas-A-Reinert** [comment]
Nope. I wouldn't even transfer the node_modules folder to the server.

**Comment by sariyanta** [comment]
Got it.
Correct me if I'm wrong:

If I want to change some styles, I will have to do it on the local files,
and then upload the sass and the css folder manually to the theme.

Thank you so much for your help. This is really helpful :)

Best Regards,


*I Made Sariyanta*
Program Manager

www.sariyanta.com
desar@sariyanta.com
+62 81 337 778 565

On Tue, Sep 26, 2017 at 2:21 PM, Thomas A. Reinert <notifications@github.com

**Comment by Thomas-A-Reinert** [comment]
Absolutely correct. You´re welcome..

**Comment by birdm99** [comment]
You can use `gulp dist-product`. It will create dist folder which you can upload on server. It contains all necessary files.

**Comment by sariyanta** [comment]
Wow. This is exciting. As a complete noob, I am learning a lot. 

I will look into the gulp dist-product and find out what it is. 

Thank you.

**Comment by Thomas-A-Reinert** [comment]
@birdm99  - you´re totally correct. Sorry for me being a dumb@ss. Should´ve known that, but I usually don´t use that task.

**Comment by h2ocreative** [comment]
Thomas and BirdM you are both very kind..... so nice to assist those who
know less.... lovely to see! nice one! :)

**Comment by redknite** [comment]
when I use gulp dist-product it leaves the sass and node_modules in the new dist-product directory.  Why does it do that?

**Comment by 0dp** [comment]
@redknite, please open new issue :)

**Comment by redknite** [comment]
> 
> 
> @redknite, please open new issue :)

okay.  thanks
