### ISSUE TITLE
Image Alignment test page fail

### ISSUE THREAD

**Issue by nikmartin** [holger1411/understrap#42]
Looking at this page: https://understrap.com/understrap/?page_id=1133 in chrome v51, the images don't have proper margins/padding as the text describes. Screenshot attached.
![screenshot from 2016-07-07 12-14-46](https://cloud.githubusercontent.com/assets/1226452/16662419/374e2d2a-443d-11e6-8e9a-d7f574114fc7.png)

**Comment by holger1411** [comment]
Hi!
Thx @nikmartin for reporting, fixed that. 
See latest commits

**Comment by nikmartin** [comment]
I was able to add bootstrap css classes to the media in the editor and that was a sufficient workaround for now, but it would be nice for the theme to add the proper classes to the media object when align left, right, center, etc are added to an inserted piece of media:

![screenshot from 2016-07-07 13-19-39](https://cloud.githubusercontent.com/assets/1226452/16664492/d6671d74-4445-11e6-83c2-17781f19835a.png)

That is a result of adding `.pull-xs-left` and `.media-left` to the image, which adds it in front of the wordpress added `'alignleft` class.
