### ISSUE TITLE
hidden-sm-up etc missing

### ISSUE THREAD

**Issue by Dazeh** [holger1411/understrap#420]

**Comment by birdm99** [comment]
With bootstrap 4 hidden classes were completely removed. 
https://stackoverflow.com/questions/45666656/bootstrap-4-responsive-utilities-visible-hidden-xs-sm-lg-not-working

**Comment by Thomas-A-Reinert** [comment]
That is not quite true. See: https://v4-alpha.getbootstrap.com/layout/responsive-utilities/

And all of those seem to be working. At least for me.. ;)

**Comment by birdm99** [comment]
You are referring to V4-alpha. In V4 those classes are missing. Instead you can use .d- classes. https://getbootstrap.com/docs/4.0/utilities/display/

**Comment by Thomas-A-Reinert** [comment]
Oh, you´re correct. Still working with the alpha-version and didn´t check the url :/ Sorry for any confusion!
