### ISSUE TITLE
Git repository stays empty after targetting at Understrap

### ISSUE THREAD

**Issue by INQ88** [holger1411/understrap#421]
I cant manage to create a Git repository from all of my local Understrap files. When targetting on the `../themes/understrap ` folder on my machine the only file showing up in the repository is `.gitattributes`.  Probably very noob'ish question but any thoughts are appreciated 🤷🏻‍♂️

**Comment by Thomas-A-Reinert** [comment]
Sorry, but this question is beyong the scope of this issue-tracker. Try to get a quick start at https://guides.github.com/activities/hello-world/ or comparable.
