### ISSUE TITLE
Body Class on Page Template

### ISSUE THREAD

**Issue by sariyanta** [holger1411/understrap#422]
So, I don't know if this an issue or anything, but I make a page with the fullwidthpage template for my homepage. When I looked at the source code, the body class become like the following: 

   `<body class="page-template page-template-page-templates page-template-fullwidthpage page-template-page-templatesfullwidthpage-php page page-id-5 logged-in admin-bar no-customize-support">`

Is this a non-issue? 

Thanks 

Made

**Comment by holger1411** [comment]
Sorry, can´t see any code ... ? Can you repost it?

**Comment by sariyanta** [comment]
So, I don't know if this an issue or anything, but I make a page with the fullwidthpage template for my homepage. When I looked at the source code, the body class become like the following:

`<body class="page-template page-template-page-templates page-template-fullwidthpage page-template-page-templatesfullwidthpage-php page page-id-5 logged-in admin-bar no-customize-support">
`
Is this a non-issue?

**Comment by holger1411** [comment]
Strange, now I see your code in both comments...;-)
Oh, and yes, it is normall...
It adds the templates internal name and template slug, pade type, template type, page id and other paramters as class to the <body>
It basically let you identify any single page at any status via CSS.
Powerfull if you need it, a bit messy if not...

**Comment by Thomas-A-Reinert** [comment]
Not an issue. Closing it.
