### ISSUE TITLE
Mobile menu on left side

### ISSUE THREAD

**Issue by crlmn** [holger1411/understrap#425]
Hi!

Understrap isn't working like in the demo. The mobile menu on my fresh installs appears on the left side while it is on the right side in the demo. 

How can I change the position?

Thank you very much!

crlmn

**Comment by typeplus** [comment]
In your header.php file move this code;

```
<!-- Your site title as branding in the menu -->
<?php if ( ! has_custom_logo() ) { ?>

	<?php if ( is_front_page() && is_home() ) : ?>

		<h1 class="navbar-brand mb-0"><a rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>"><?php bloginfo( 'name' ); ?></a></h1>

	<?php else : ?>

		<a class="navbar-brand" rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>"><?php bloginfo( 'name' ); ?></a>

	<?php endif; ?>
```


Directly before the code;

```
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
```

**Comment by davigarcas** [comment]
<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse justify-content-end',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav justify-content-end',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>

I think is in one of those try each one and see which one works

**Comment by holger1411** [comment]
The problem is that the demo site already features version 0.6.6 of understrap, while you can install v0.6.5 via WordPress installer.
At the moment there are incompatibilities between WP core jQuery component and the way jQuery is implementet into Bootstrap 4 Beta 2.
So I can´t release 0.6.6 officially on wordpress.org at the moment.
The BS4 team is working on this and they will release a fix for it with Bootstrap 4 Beta 3.
Thats the reason why the demo site is a bit different at the moment.

**Comment by melanieceraso** [comment]
You can also change the order of the elements since they are using flexbox.  Just apply an order to .navbar-toggler, .navbar-brand.custom-logo-link, and .navbar-collapse.

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.
