### ISSUE TITLE
Nav with hover and 1st (top) item clickable

### ISSUE THREAD

**Issue by bruceconlon** [holger1411/understrap#426]
Is there an easy way in the markup to make the submenu show on hover rather than click? 

Also to make the primary 1st nav item clickable to go to its page?

Similar to how it works here: [https://www.cisco.com/](https://www.cisco.com/)

I've made the hover mostly work with the following, (although the menu stays on click):

	.dropdown-menu {
		border-radius: 0;
		border-top: 1px solid $gray-lighter;
		.sub-menu {
			left: 100%;
			position: absolute;
			top: 0;
			visibility: hidden;
			margin-top: -1px;
			li {
				#{$hover-focus} {
		  			visibility: visible;
				}
			}
		}
	}

	.dropdown {
		#{$hover-focus} {
			.dropdown-menu {
				display: block;
			}
		}
	}

	.nav-tabs .dropdown-menu,
	.nav-pills .dropdown-menu,
	.navbar .dropdown-menu {
		margin-top: 0;
	}

And get the menu link if I change the following in the navwalker:

			if ( $args->has_children && $depth === 0 ) {
				// Change this to '#' if only wanting a hover, and not wanting clickable link
				$atts['href']        = ! empty( $item->url ) ? $item->url : '';
				$atts['data-toggle'] = 'dropdown';
				$atts['class']       = 'nav-link dropdown-toggle';
			} else {

But I can't see with the standard header menu code, why the primary menu item is not clickable?

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				
				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>

**Comment by Thomas-A-Reinert** [comment]
It´s not really recommended due to mobile optimization, so I guess it will neither be included in Bootstrap4 by default nor in UnderStrap.

But check this Pen ( https://codepen.io/bsngr/pen/frDqh ) and try to built from there on your own. As far as I can see (on a very quick check), you don´t need to change of the CSS but just need to customize the jQuery call to your needs.

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.

**Comment by tournetorres** [comment]
Did you ever figure it out? Remove THIS

` $atts['data-toggle'] = 'dropdown';`

**Comment by tournetorres** [comment]
Also @bc1974A , you helped me a lot!

**Comment by nelitow** [comment]
Had a similar problem and solved by deleting `$atts['data-toggle']   = 'dropdown';` from _call-wp-bootstrap-navwalker.php_, setting `$atts['href'] = ! empty( $item->url ) ? $item->url : '#';` for it to get a URL, and adding this JS `  jQuery('a.dropdown-toggle').hover(function() {
    jQuery(this).siblings('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
  }, function() {
    jQuery(this).siblings('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
  });`

**Comment by axlright** [comment]
Just be careful of how you apply this - tablets and larger touch screen monitors have no hover state so you'll render the menu dropdown inaccessible.

**Comment by nelitow** [comment]
Sure, I wouldn't do it myself, it was by client request. But in this case, the "parent" page is just a page that points to the submenus, so nothing gets lost. But thanks for the concern.

**Comment by areddxx** [comment]
Has anyone found a solution that works for mobile?
