### ISSUE TITLE
Shop home missing?

### ISSUE THREAD

**Issue by bruceconlon** [holger1411/understrap#430]
I was looking for either archive-product.php or woocommerce.php in parent theme, so I can customise the shop home, but there doesn't seem to be one, is that correct? eg. https://github.com/holger1411/understrap/tree/master/woocommerce

I can download one from the woocommerce site and modify it so I can override in the child theme, but wanted to check first

**Comment by bruceconlon** [comment]
ignore me, its at the root level, apologies

**Comment by holger1411** [comment]
Check ;-)
