### ISSUE TITLE
Is understrap theme follow envato Submission Requirements

### ISSUE THREAD

**Issue by damithruwan1234** [holger1411/understrap#431]
I am going to build a theme using understrap  and sell it on theme forest.

Guideline : https://help.market.envato.com/hc/en-us/articles/202822450-WordPress-Theme-Submission-Requirements

Please can I know that understrap theme followed that guideline too?

**Comment by holger1411** [comment]
Sorry, don´t know.
Feel free to check it on your own and report back.
