### ISSUE TITLE
 what is the best way to hide elements in mobile?

### ISSUE THREAD

**Issue by asiz15** [holger1411/understrap#433]
Hi guys, the class .hidden-sm-down is not working for me.

i aprecciate your help.

regards

**Comment by axlright** [comment]
Use .d-none (for display none) and .d-sm-flex (for display flex for small and up) or .d-sm-block (for display block for small and up) or .d-md-block (for display block for medium and up) etc.

Bootstrap 4 no longer supports just .hidden-sm - the newer way seems a bit more complicated but it's good in that you can specify the display value (block, inline-block, inline, flex) when you do what the element to display.

**Comment by asiz15** [comment]
Thanks mate! 
 here i found the way tho do this.

https://stackoverflow.com/questions/45687643/how-to-hide-element-on-small-screens-with-bootstrap-4-beta

regards.

**Comment by axlright** [comment]
Yup that's the way to do it :-)
