### ISSUE TITLE
Bootstrap4 SASS src files missing classes

### ISSUE THREAD

**Issue by denislam** [holger1411/understrap#438]
After a bit of debugging, I discovered certain bootstrap4 style classes were not working because they are missing in the source files. For example in `_dropdown.scss`, your menu positioning class `.dropdown-menu-right` is missing. Adding the following to the scss file solved the issue:

```
// Menu positioning
//
// Add extra class to `.dropdown-menu` to flip the alignment of the dropdown
// menu with the parent.
.dropdown-menu-right {
  right: 0;
  left: auto; // Reset the default from `.dropdown-menu`
}

.dropdown-menu-left {
  right: auto;
  left: 0;
}
```
**Suggestion:** Update the bootstrap4 src files to the latest version and make sure the new variables are compatible to your other sheets.

**Comment by holger1411** [comment]
Thats a class from Bootstrap 4 Alpha. UnderStrap uses Bootstrap 4 Beta.
The class is no longer in use
