### ISSUE TITLE
How to use Owl Carousel??

### ISSUE THREAD

**Issue by sajiddesigner** [holger1411/understrap#44]
Hello
Please tell me how can i use owl carousel with child theme. i have tried adding widgets in Hero Slider Widget area but it does not work.

**Comment by holger1411** [comment]
Hi!
Its important to place the widgets again AFTER the child theme was activated.
If you use the parent theme, place the widgets and active the child after it the widgets will disappear (because they are assigned to the widget area from an inactive theme)

**Comment by holger1411** [comment]
Does it fix the issue?
Will close that, let me know if not (reopen it)

**Comment by sajiddesigner** [comment]
Hello,
yes i have fixed this. 
Thanks
