### ISSUE TITLE
Modify understrap_pagination

### ISSUE THREAD

**Issue by antonapua** [holger1411/understrap#440]
Anyone could help me with my issue. Found the pagination.php under "inc" folder in understrap. 

However when I created the "inc" folder in my child theme (understrap-child-0.3.4) and copy the pagination.php there and tried modifying it seems it's still using the one from the parent theme.

**Comment by typeplus** [comment]
In your functions.php file in the child theme you can create an override as the pagination function is pluggable. For instance;

```
if ( ! function_exists( 'understrap_pagination' ) ) :
    function understrap_pagination() {
        ......Your Customisation's Here
    }
    endif;
```

**Comment by antonapua** [comment]
@typeplus Thanks for the response, I was aiming for changing the structure and stuff. Could you guide me how to approach this.

**Comment by antonapua** [comment]
@typeplus would this be the cleanest approach? I'm using a CPT in a plugin. So I would probably put an include right in there to manage it in a separate file away from the main plugin file.

**Comment by typeplus** [comment]
You can also use `require` in your child theme functions.php;

`require( get_stylesheet_directory() . 'inc/pagination.php' );`

Definitely cleaner, but an include is fine as well. Depends how far you want to modify the pagination.

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.
