### ISSUE TITLE
Problem with jquery.slim.min.js

### ISSUE THREAD

**Issue by yamaks** [holger1411/understrap#441]
Why do I have a problem with jquery.slim.min.js?

![image](https://user-images.githubusercontent.com/1436067/32003207-12c48496-b9a7-11e7-8c85-df8c9396574c.png)

**Comment by joshuafredrickson** [comment]
Looks like you're using both effects and ajax, which aren't included in the slim package. Try swapping it with standard jQuery instead.

> Slim version of jQuery that excludes ajax, effects and currently deprecated code.
[jquery-slim](https://www.npmjs.com/package/jquery-slim)

**Comment by axlright** [comment]
Here's how I've done this - works great. I downloaded the full jQuery and put it in my /js/ directory. Note below that I'm compiling my css and main js files to different names, so be sure to change the main site css.min and js.min files to be what you use:

`/* OVERRIDE understrap_scripts WITH CUSTOM SCRIPTS + STYLES
================================================== */

function understrap_scripts() {
	// Get the theme data.
	$the_theme = wp_get_theme();
	wp_enqueue_style( 'custom-styles', get_stylesheet_directory_uri() . '/css/style.min.css', array(), $the_theme->get( 'Version' ) );
	wp_deregister_script('jquery');
	wp_register_script('jquery', (get_stylesheet_directory_uri() . '/js/jquery-3.2.1.min.js'), false, '3.2.1');
	wp_enqueue_script( 'jquery' );
	wp_enqueue_script( 'popper-scripts', get_template_directory_uri() . '/js/popper.min.js', array(), false );
	wp_enqueue_script( 'custom-scripts', get_stylesheet_directory_uri() . '/js/app.min.js', array(), $the_theme->get( 'Version' ), true );
	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}

add_action( 'wp_enqueue_scripts', 'understrap_scripts' );`

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.
