### ISSUE TITLE
Looks like wp hasn't been updated to 0.6.6

### ISSUE THREAD

**Issue by ErinPo** [holger1411/understrap#450]
Just sayin'

**Comment by holger1411** [comment]
Yes, problem is that Bootstrap 4 Beta 2 need jQuery 3+ while WP needs 1.12. So the WP repo did no accept UnderStrap 0.6.6

The BS4 team is aware of this and will provide support for older jQuery with Bootstrap 4 Beta 3.

Till then there will be no official Wordpress.org release...
Maybe there is a workaround, if not I have to wait till Beta 3 to release a new version.

**Comment by ErinPo** [comment]
Actually Bootstrap 4 Beta 2 still only requires jQuery 1.9.1 or higher so I think you can stick to that for now and get it published until maybe in WP 4.9 there is a solution for jQuery 3.

> Bootstrap still requires jQuery 1.9.1 or higher, but you’re advised to use version 3.x since v3.x’s supported browsers are the ones Bootstrap supports plus v3.x has some security fixes.

https://getbootstrap.com/docs/4.0/migration/

**Comment by holger1411** [comment]
The dev version does that, the released Beta 2 needs jQuery 3+ and don´t work with the WP jQuery version in noConflict mode. (noConflict mode seems to be the real problem here, not the jQuery version itself)

If you use the current released Beta 2 the dropdown will not work and some other strange things will happen (https://github.com/holger1411/understrap/issues/457)

So you can pull in the bleeding edge dev version (which already includeds the fix but is not yet released) manually and recompile the css and js it works or you switch back to UnderStrap 0.6.5.

**Comment by ErinPo** [comment]
I use the beta 2 included in Understrap 0.6.6. Is that the dev version or the released version?

**Comment by holger1411** [comment]
The release version.
The dev version is if you hit the green download button on the Bootstrap 4 Github page.
Than you get every commit, including any changes after the Beta 2 release

**Comment by ErinPo** [comment]
Ok, and do I need to replace the SASS sources or bootstrap.min.js or both?

**Comment by ErinPo** [comment]
Hm, I just noticed that the child theme is set to load bs4.js from its js folder rather than from the parent theme and since the child theme hasn't been updated since the release of bs4 beta 2, it still loads bs4 beta 1... That wouldn't be why there are those issues with jQuery 3 you mention, would it?

**Comment by holger1411** [comment]
No, I just don´t update it becuse of the jQuery issue. 
And yes, you should replace all BS4 scss files in src/sass/bootstrap4 and the js files in src/js/bootstrap4
Than recompile the stylesheet and the js file.

Hopefully they release Beta 3 soon so we can rid off this glitch...

**Comment by ErinPo** [comment]
Ok, I have done that, but now I am confused by your subsequent releases of version 0.6.7 here and 0.6.8.1 on Wordpress, for the latter of which I could not find release notes. How was the jQuery situation fixed in 0.6.7. The release notes details are insufficient. I actually need to keep using the AP native jQuery because many plugins do not yet work with 3.x. Which version should I use then?

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.
