### ISSUE TITLE
Comments in _theme_variables.scss need update for Bootstrap 4 alpha 2

### ISSUE THREAD

**Issue by ianwyllie** [holger1411/understrap#461]
The comments in _theme_variables.scss refer to $brand-primary which has sort of disappeared into maps and theme colours in Bootstrap 4 I think. You could replace the comments with:

// Use this file to overwrite the basic Bootstrap variables and add your own variables

// To overwrite a Bootstrap variable you don´t have to touch the Bootstrap folder. 
// Just copy a variable from /sass/bootstrap/_variables.scss, paste it here and edit the value.
// As example you can demonstrate changing the body background color using $body-bg: class and the
// the $body-color: classs. 
// $body-bg: #000;
// $body-color: #ffffff;
// Just add your color code here, compile the theme.scss file to change this color everywhere

**Comment by holger1411** [comment]
Was already changed.
The sample overwrite in _theme_variables.scss is now:
$primary: #0A42E8;

**Comment by holger1411** [comment]
And the comment is more unspecific:
```
// Use this file to overwrite the basic Bootstrap variables and add your own variables
// To overwrite a Bootstrap variable you don´t have to touch the Bootstrap folder. 
// Just copy a variable from /sass/bootstrap/_variables.scss, paste it here and edit the value.
```

**Comment by holger1411** [comment]
Ah, okay. The path is the wrong one. Adjust it here:
https://github.com/holger1411/understrap/commit/94eba946ce25346bf7856f9f3f15ef6f4184c3dd

**Comment by ohjakobsen** [comment]
The primary color is now #563d7c. Should this be changed back to #0A42E8?
