### ISSUE TITLE
WordPress Menu Title Attribute Not Displaying

### ISSUE THREAD

**Issue by JDVirtual** [holger1411/understrap#463]
I'm developing a site that needs to be AODA accessible.

One of the primary components is making the main navigation items have descriptive title attributes. I've set these up to be descriptive for each main navigation item, however when you hover over it, the description title attribute I created does not show.

So for example if I hover over "About", it should say "About (Company Name)". However even though I set the title attribute for that menu item to be About (Company Name), when I hover over it on the site, it still says "About".

How do we fix this?

**Comment by JDVirtual** [comment]
@holger1411 Any fix for this? We can't launch the site without this feature working. Not sure why it wouldn't be.

**Comment by shansmith01** [comment]
My understanding is that the title attribute showing on hover is that it's dependent on the browsers. Sometimes it works and sometimes it does not. I'm not sure which ones support it. You may want to look at tooltips to force the display, but I'm not sure if this meets you accessibility requirements https://getbootstrap.com/docs/4.0/components/tooltips/

**Comment by Thomas-A-Reinert** [comment]
File to be changed would be understrap/inc/bootstrap-wp-navwalker.php

I can so far confirm that it does not only ignore custom titles, but also custom classes.

``$atts['title']  = ! empty( $item->title ) ? $item->title : ''; ``
always seems to return the actual menu item name no matter what you write there.

Whereas the class always returns a static 'nav-link'. XFN-relations and link target work though.

**Comment by JDVirtual** [comment]
@shansmith01 Thanks for your help Shan. Tried Chrome, Firefox, Edge and IE, none of them work. :(. I'll look into whether the tooltips are accessible, appreciate it.

@Thomas-A-Reinert thanks for pointing it out there, figured it was in the navwalker file. Just wasn't sure how to make it work! So basically you're saying there's no current fix to this?

**Comment by Thomas-A-Reinert** [comment]
See line 102 which reads:
``$atts['title']  = ! empty( $item->title ) ? $item->title : ''; ``

Change it to;
``if ( empty( $item->attr_title ) ) {
	$atts['title']  = ! empty( $item->title )   ? strip_tags( $item->title ) : '';
} else {
	$atts['title'] = $item->attr_title;
}``

Solves your problem.

Credits to: https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/master/wp-bootstrap-navwalker.php

@holger1411 You should check [WP Bootstraps´](https://wp-bootstrap.org/) updated version..

**Comment by JDVirtual** [comment]
@Thomas-A-Reinert Thank you so much sir! Really appreciate it.

**Comment by Thomas-A-Reinert** [comment]
No problem, you´re welcome.

**Comment by holger1411** [comment]
@Thx @Thomas-A-Reinert: Will test it and merge your solution soon.

**Comment by jfksdca** [comment]
Not sure this will post but the wordpress problem persists.  Thomas' code change still works but is now on line 173.

**Comment by Thomas-A-Reinert** [comment]
Hi @jfksdca - I´m not sure if I understand correctly, but in my installations I always see the title-attribute attached to the link and it´s also getting displayed. The latest version of my portfolio is built upon the latest UnderStrap version.
![image](https://user-images.githubusercontent.com/5886977/60487897-c24c6e00-9ca0-11e9-9753-9273e9b2e818.png)

Just make sure you use the latest version. And please correct me if I got anything wrong.
