### ISSUE TITLE
Post on and last modified text should be separated?

### ISSUE THREAD

**Issue by bruceconlon** [holger1411/understrap#466]
From the demo (https://understrap.com/understrap/) the following post, which has been modified, has the two dates merged together as "January 11, 2013August 12, 2015"

![image](https://user-images.githubusercontent.com/7244699/33048102-19aa5836-cebe-11e7-8a8a-8ec71a278ad0.png)

Should they be split to say something like the following with the phrase ", updated" inserted between?

"Posted on January 11, 2013, updated August 12, 2015 by themedemos"

I noticed this when developing the child them as it comes from the parent.

**Comment by holger1411** [comment]
I add some space and brackets around the edited date
