### ISSUE TITLE
Menu title only uses the Navigation label and not the title attribute

### ISSUE THREAD

**Issue by jirodearmas03** [holger1411/understrap#468]
I am using understrap and a child-theme. The theme seems to use only the "Navigation label" as the title of the menu even if I change the "Title Attribute".
![wp-menu-title](https://user-images.githubusercontent.com/29938616/33115357-f3dc776c-cf60-11e7-843e-56a9667dc1d8.jpg)

**Comment by Thomas-A-Reinert** [comment]
See https://github.com/holger1411/understrap/issues/463#issuecomment-346185843 and https://github.com/holger1411/understrap/pull/467/commits/038675e6c988cfdba9119226a206ee498010be62 which - in combination - should solve your problem.
