### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by azharijelek** [holger1411/understrap#469]
Hi, I'm developing a theme using understrap. Though it's easy to install, I get some error for minified javascript. 

`Uncaught ReferenceError: $ is not defined`

why is that?

**Comment by holger1411** [comment]
Its a problem with the Bootstrap 4 Beta 2 requirements for jQuery and WordPress.
The problem will be fixed with Beta 3
Till then pls use UnderStrap 0.6.5

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.
