### ISSUE TITLE
Missing /inc/theme-settings.php?

### ISSUE THREAD

**Issue by axlright** [holger1411/understrap#472]
I'm probably being dense here. Went to update understrap_child to 0.3.6 and understrap parent to 0.6.7 but I see that in understrap/inc/setup.php there's a `require get_template_directory() . '/inc/theme-settings.php';` but there's no /inc/theme-settings.php included in the 0.6.7 update, though this file does exist in 0.6.6

Are we to stick with 0.6.6. while using the understrap child theme? Seems like the above would cause problems even using just the parent theme.

Thanks @holger1411 !!

-Alex

**Comment by kingsj** [comment]
I updated understrap this evening and got the same error - can we have a rollback please?

**Comment by Vishal-Deshpande** [comment]
I have added back the missing file & moved the required file code to functions.php

Please merge @holger1411

**Comment by olemo** [comment]
Wordpress is offering a Version 0.6.8.1 with the same error. Rollback to 0.6.7 is working fine for me

**Comment by kjostling** [comment]
Got the same issue. Fixed it by removing the "require get_template_directory() . '/inc/theme-settings.php';" line from setup.php altogether since that was the intention from start (reading the commit message).

**Comment by holger1411** [comment]
Hi!
I currently prepare 0.6.11 where the problem was already fixed.
