### ISSUE TITLE
mobile menu strange behaviour

### ISSUE THREAD

**Issue by TomKisielewski** [holger1411/understrap#48]
How styles are applied , I can't fix it. When I add custom style, first default are applied, then my custom and there is a "jump" between styles. The same is when using clear understrap installation, is it a bug or I am missing something?
I put video on youtube https://youtu.be/qKck6qI3RTo

**Comment by holger1411** [comment]
Hi!
Yeap, it´s a bug...
Its on my list for the next update

**Comment by holger1411** [comment]
*Should* be fixed by https://github.com/holger1411/understrap/commit/eaa316b2beea59a8d5d2187f178d91443a4c7daf
