### ISSUE TITLE
Current version?

### ISSUE THREAD

**Issue by brainchildguru** [holger1411/understrap#480]
If I run `https://github.com/holger1411/understrap.git`I get version _0.6.8.2_, but if I hit the "Download" button on understrap.com, I get version _0.6.7_ . What is the most current version and it's corresponding changelog. Thanks ahead of time and great theme!

**Comment by zreese** [comment]
As far as I can tell, the distribution on https://understrap.com/ is compiled from this git repo. So the repo will always be the most recent version. 

[Changelog is in the repo](https://github.com/holger1411/understrap/blob/master/CHANGELOG.md).

**Comment by holger1411** [comment]
The newest version is alway released here on GitHub. Usually I wait a few days before I release the new version on understrap.com and wordpress.org to avoid bugs slipping through...
