### ISSUE TITLE
Dropdown-Menu false

### ISSUE THREAD

**Issue by DUGeCommerce** [holger1411/understrap#481]
Hi,
after the update to 0.6.9 the dropdowns of the "navbarNavDropdown"-Menu are not longer work. Same in the child-theme.

**Comment by knightknight** [comment]
Latest update to the parent and child are not working here either.

**Comment by corycpf** [comment]
Adding in the console log as reference. 

Reproduced on UnderStrapVersion: 0.6.9.3 / UnderStrap ChildVersion: 0.3.6; 
Browsers: Chrome: v64; FF Dev v58; Safari v10; Opera 49

Console log: 
`(index):45 GET https://"url.com"/wp-content/themes/understrap/js/jquery.slim.min.js?ver=3.2.1 net::ERR_ABORTED
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
(index):45 GET https://"url.com"/wp-content/themes/understrap/js/jquery.slim.min.js?ver=3.2.1 net::ERR_ABORTED
child-theme.min.js?ver=0.3.6:1 Uncaught TypeError: Cannot read property 'fn' of undefined
    at child-theme.min.js?ver=0.3.6:1
    at child-theme.min.js?ver=0.3.6:1
    at child-theme.min.js?ver=0.3.6:1
(anonymous) @ child-theme.min.js?ver=0.3.6:1
(anonymous) @ child-theme.min.js?ver=0.3.6:1
(anonymous) @ child-theme.min.js?ver=0.3.6:1`

**Comment by knightknight** [comment]
As a quick test I pulled in [068572b4e6b2583a02a7371219ad86ad9232dd65](https://github.com/holger1411/understrap-child/blob/068572b4e6b2583a02a7371219ad86ad9232dd65/js/child-theme.js) commit for [child-theme.js](https://github.com/holger1411/understrap-child/blob/068572b4e6b2583a02a7371219ad86ad9232dd65/js/child-theme.js) and this version is working as far as dropmenu is concerned.

**Comment by corycpf** [comment]
@knightknight Attempted that same work around, but I wasn't successful, dropmenu was still not working after pulling in the reference commit for child-theme.js

**Comment by knightknight** [comment]
@corycpf I commented out child-theme.min.js from the understrap-child function.

**Comment by knightknight** [comment]
Latest [js rebuilds](https://github.com/holger1411/understrap/commit/ec3562fcd4e254dc44c57e8aebc1b32e7ba602e4) have fix the dropdown issue.

**Comment by holger1411** [comment]
Thx for reporting guys, _should_ be fixed with 0.3.7 now

**Comment by corycpf** [comment]
Thanks @holger1411 for the quick deployed fix. Fix is verified, It's working perfectly now. Issue can be closed.

**Comment by DUGeCommerce** [comment]
Thanks to all. Now it works.

**Comment by DUGeCommerce** [comment]
Hmm....
after the update to 0.6.10 the dropdown already don't work.
console -> `theme.min.js?ver=0.6.10:1 Uncaught ReferenceError: jQuery is not defined
    at theme.min.js?ver=0.6.10:1`

**Comment by holger1411** [comment]
Sounds like jQuery is not loaded. It works on my local testing and on demo (https://understrap.com/understrap/)

Can you verify that your page loads jQuery?

**Comment by DUGeCommerce** [comment]
Hi holger1411.
That's right! jQuery isn't loading. But why? I replaced the installed theme with a "fresh" downloaded version of your theme 0.6.10 with **no** changes and it still don't work.

After editing `<?php wp_enqueue_script('jquery'); ?>` before `<?php wp_head(); ?>` it works.
I am faced with a riddle.

**Comment by DUGeCommerce** [comment]
fixed with 0.6.11
