### ISSUE TITLE
How can I make My Original Child Theme with learn start.

### ISSUE THREAD

**Issue by tonbo** [holger1411/understrap#482]
Hi. 
Thank you for your kind support.
Today, I have some question to make my own understrap child theme.
Would you tell me the minimum file system setting about understrap cild theme?

For example,
if I want to have change (add) only home.php,
which files should I make for child theme, and what is the content of those files?

My trial is,
1) make new dhirectory named 'undestrapchild'.
2) make new style.css file, like this code,
---
/*
 Theme Name:   CHILD THEME of Me.
 Theme URI:    https://myowntheme.com
 Description:  My theme
 Author:       me
 Author URI:   http://myowntheme.com
 Template:     understrap
 Version:      1.0.0 (understrap based)
 License: GNU General Public License v2 or later
 License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain:  understrap-child
 Tags: one-column, custom-menu, featured-images, theme-options, translation-ready
*/
---
3) copy 'index.php' and rename as 'home.php' from understrap parent directory.
4)make function.php
...I tried some function.php code referring from understrap parent file and official child theme and wordpress codex, but by now, I don't success.

I just want to have learn start from same function and design with understrap parent theme, and make some cutsom in new child theme directory.
I'd like to start minimum change such as 'home .php' and may expand the changes to css, js, or some templete files. And the files that no necessary to be changed should be inherited the features from parent files.

Would you give me some ideas or suggestion in particular about 'function.php'.
Thank you for your help in advance.

**Comment by Thomas-A-Reinert** [comment]
Hi @tonbo - Sorry to say, but this question is far beyond the scope of this issue-management for UnderStrap. This is a generic WordPress issue. But i´ll give you a heads-up, just follow the links below and work through each of them.

- Get the UnderStrap4 premade Child-theme here: https://github.com/holger1411/understrap-child
- Copy the files you need to change from the parent to the child and change them there.

For some more detailed infos on how to create child-themes check the following links:

- WordPress on Child-themes https://codex.wordpress.org/Child_Themes
- https://premium.wpmudev.org/blog/how-to-create-wordpress-child-theme/
- http://www.wpbeginner.com/wp-themes/how-to-create-a-wordpress-child-theme-video/

**Comment by tonbo** [comment]
Thank you @Thomas-A-Reinert .
Now I compare both scss and js files of parent and child theme, and understand that they are almost same feature.
And I faced another problem about understrap parent theme.

I wanted to add a extra js file (for ACF google map fatures) in "/src/js/" directory. So I added a line,
basePaths.dev + 'acf-googlemap.js'
to add  gulp scripts in " gulpfile.js".

After then, I tried to execute the command from the terminal,

#npm install

(or #npm install --unsafe-perm)
at understrap theme directory as root user, 
the therminal says:
---
npm WARN Invalid version: "0.6.9.3"
npm WARN understrap No description
npm WARN understrap No repository field.
npm WARN understrap No README data
npm WARN understrap No license field.
---
and I can't update gulp scripts.
How can I do for it?

**Comment by holger1411** [comment]
Arg, yes. npm just allows version numbers with three digits like x.x.x
I switched back to a main version number in package.json:
https://github.com/holger1411/understrap/commit/d1d6f5603a732432bfd16c78e6ba01defbcb562e

I also published this 0.6.9 package on npm.
Just change the version number in your package.json from 0.6.9.3 to 0.6.9 and retry it

**Comment by tonbo** [comment]
Thank you!!
Now working.
