### ISSUE TITLE
bootstrap-wp-navwalker.php -> divider, disabled (menu attr) don't work

### ISSUE THREAD

**Issue by DUGeCommerce** [holger1411/understrap#483]
Hi.
In my understrap dummy-installation I tried to build up a "megamenu" in the navbar.
BE:
![wp-menu-be](https://user-images.githubusercontent.com/3601303/33424981-ba69a17c-d5bd-11e7-84f4-8c47676fadbb.png)

FE:
![wp-menu-fe](https://user-images.githubusercontent.com/3601303/33425158-2cf3c754-d5be-11e7-9103-20a90b2782b7.png)

In "WP -> Appearance -> Menus" I can use the "HTML-Attribut title (optional)" to render a Dropdown-Header, -Devider and a disabled link. This is managed in the bootstrap-wp-navwalker.php.
Line 64:
`if ( strcasecmp( $item->attr_title, 'divider' ) == 0 && $depth === 1 ) {
			$output .= $indent . '<li class="divider" role="presentation">';
		} else if ( strcasecmp( $item->title, 'divider' ) == 0 && $depth === 1 ) {
			$output .= $indent . '<li class="divider" role="presentation">';
		} else if ( strcasecmp( $item->attr_title, 'dropdown-header' ) == 0 && $depth === 1 ) {
			$output .= $indent . '<li class="dropdown-header" role="presentation">' . esc_html( $item->title );
		} else if ( strcasecmp( $item->attr_title, 'disabled' ) == 0 ) {
			$output .= $indent . '<li class="disabled" role="presentation"><a href="#">' . esc_html( $item->title ) . '</a>';
		} else {`

- attr -> dropdown-header -> FE rendering -> **works**
- attr -> divider (maybe dropdown-divider would be better) -> **FE rendering don't work** -> because in BS4 the class has to be "dropdown-divider"
- attr -> disabled -> **FE rendering don't work** -> because the class has to be at the a-Tag -> `else if ( strcasecmp( $item->attr_title, 'disabled' ) == 0 ) {
			$output .= $indent . '<li role="presentation"><a class="dropdown-item disabled" href="#">' . esc_html( $item->title ) . '</a>';
		} else {`
- the depth is allways `$depth === 1`. I don't know if this is a "have to" for normal menus. But if it is not a problem, is it posible to set the depth to `$depth >= 1`? Then a possible deeper menu-structure will work.

Here the complete changed code:
`if ( strcasecmp( $item->attr_title, 'divider' ) == 0 && $depth >= 1 ) {
			$output .= $indent . '<li class="dropdown-divider" role="presentation">';
		} else if ( strcasecmp( $item->attr_title, 'divider' ) == 0 && $depth >= 1 ) {
			$output .= $indent . '<li class="dropdown-divider" role="presentation">';
		} else if ( strcasecmp( $item->attr_title, 'dropdown-header' ) == 0 && $depth >= 1 ) {
			$output .= $indent . '<li class="dropdown-header" role="presentation">' . esc_html( $item->title );
		} else if ( strcasecmp( $item->attr_title, 'disabled' ) == 0 ) {
			$output .= $indent . '<li role="presentation"><a class="dropdown-item disabled" href="#">' . esc_html( $item->title ) . '</a>';
		} else {`

And sure to build such a mega-menu - "xtra" CSS is necassery.

Thanks Holger for your good work and your time!!!

**Comment by DUGeCommerce** [comment]
The Point with the devider is fixed in 0.6.11.

**Comment by axlright** [comment]
@DUGeCommerce Do you have a link to a public website using this technique? Do you have any updates on the edited Navwalker code?
