### ISSUE TITLE
Bug with BS beta-2 -- fix below

### ISSUE THREAD

**Issue by raisonon** [holger1411/understrap#485]
As per: https://github.com/twbs/bootstrap/issues/24417

Perhaps set $ = jQuery.noConflict(true) before we load BS so we don't get the above error.

A fix is out in beta-3 but in the meantime, it might be smart to add this fix.

What do you think?

**Comment by holger1411** [comment]
Thx @raisonon for your solution!

Fixed this issue by:
I pulled in the fixed BS4 version into the /src folder to fix this issue and comment out BS4 Beta2 as dependency in gulpfile.js to avoid an overwrite on "gulp copy-assets" or "npm install"
Its just a workaround till Beta 3 comes out, but it works too.

To be honest it seems your solution is more elegand, but hopefully Beta 3 is released soon...

**Comment by raisonon** [comment]
Nice one, to be honest I fixed it on mine just like you did ;)
