### ISSUE TITLE
Add cutsom template page issue

### ISSUE THREAD

**Issue by VinceSchlo** [holger1411/understrap#486]
hi,
I'm trying to add a new custom template in the Understrap theme but it didn't work. 

This is what I wrote on top of my php file :
```
/*
Template Name: My new template
*/
```
I can choose this template with the "Draft Child Theme" but i can't with Understrap. (And the file is within the Understrap folder)

Do you have any idea ?

**Comment by Thomas-A-Reinert** [comment]
Did you put it in the 'page-templates' folder?

**Comment by VinceSchlo** [comment]
Yes I've tried every folder, even in the root, but it's not working.

I've tried also to copy/paste the code of an existing template which is visible in dropdown menu and change only the "Template Name" but that's doesn't work.

**Comment by acolas** [comment]
Are you using Wordpress 4.9? If so, there is this bug: https://core.trac.wordpress.org/ticket/42573 causing the template files to only be rescanned once every hour.

You can add this code below to functions.php to fix this template caching issue 
`function wp_42573_fix_template_caching(WP_Screen $current_screen)
{
    // Only flush the file cache with each request to post list table, edit post screen, or theme editor.
    if (!in_array($current_screen->base, array('post', 'edit', 'theme-editor'), true)) {
        return;
    }
    $theme = wp_get_theme();
    if (!$theme) {
        return;
    }
    $cache_hash = md5($theme->get_theme_root().'/'.$theme->get_stylesheet());
    $label = sanitize_key('files_'.$cache_hash.'-'.$theme->get('Version'));
    $transient_key = substr($label, 0, 29).md5($label);
    delete_transient($transient_key);
}
add_action('current_screen', 'wp_42573_fix_template_caching');
`

**Comment by VinceSchlo** [comment]
Yes I'm using Wordpress 4.9 and I tried this way and always not visible... I've tried to install Wordpress 4.8, but it doesn't work anyway.

The strange thing is, I can see my custom template with the child theme without waiting 1hour but I can't with understrap. 

Am I the only one to have this issue ? I use the 0.6.7 Understrap.

Thank you for your help.

**Comment by ZacharyElkins** [comment]
This is a WordPress 4.9 issue. 

They are tracking it here:
https://core.trac.wordpress.org/ticket/42573

Visit that link and apply the latest patch (only) to the following file:
src/wp-includes/class-wp-theme.php

**Comment by holger1411** [comment]
Thx @ZacharyElkins for the explanation!
Close this issue
