### ISSUE TITLE
Understrap Nav Walker depth =>3

### ISSUE THREAD

**Issue by opolanco23** [holger1411/understrap#487]
Hello,

I am trying to setup the navwalker to handle a third level droprown, using depth => 3 like suggested from the documentation for the navwalker does not work. Any ideas?

Example:
menu
-page 1
 --subpage1
-page 2
-page 3

**Comment by DUGeCommerce** [comment]
Mabye [https://github.com/holger1411/understrap/issues/483](https://github.com/holger1411/understrap/issues/483) will help.

**Comment by holger1411** [comment]
By default Bootstrap 4 did not support a deeper menu item structur so UnderStrap will not support it, too.
But maybe @DUGeCommerce  solution is something for you
