### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wc_form_field_args' 

### ISSUE THREAD

**Issue by wildfang** [holger1411/understrap#488]
Hi,

getting this recently on check out:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wc_form_field_args' not found or invalid function name in xxxxxxx/wp-includes/class-wp-hook.php on line 286

It appears in every place a form field should be (billing and shipping details).

Not sure where to start looking to fix this... Any idea?

Thanks!

**Comment by Thomas-A-Reinert** [comment]
This is most likely not UnderStrap related. Try deactivating all plugins and reenable them one after the other.

**Comment by wildfang** [comment]
Mh, so maybe it is woocommerce related? It is the only plugin that is activated.

**Comment by wildfang** [comment]
Quickfix:

Change understrap/inc/woocommerce.php to:

Line 23: 	add_filter( 'woocommerce_form_field_args', 'understrap_wc_form_field_args', 10, 3 );

**Comment by holger1411** [comment]
Thx @wildfang 
Was fixed here: https://github.com/holger1411/understrap/commit/44c38d710a4f078d21a548b4756e38fe86dc6835
