### ISSUE TITLE
Can't chosse right sidebar by default

### ISSUE THREAD

**Issue by VinceSchlo** [holger1411/understrap#493]
Hi everyone,

I have an issue about setting the right sidebar by default. I'm using understrap 0.6.10 and the BASE child theme. Within the customizer menu I choose "right sidebar" and I can see it but when I leave the customizer menu, the sidebar disapear unless i chosse the custom template "Rigth sidebar layout". But i don't want to do it for every page...

I didn't override page.php and the code to add right sidebar is inside : 
```
<!-- Do the right sidebar check -->
<?php if ( 'right' === $sidebar_pos || 'both' === $sidebar_pos ) : ?>
<?php get_sidebar( 'right' ); ?>
<?php endif; ?>
```

Maybe I have misunderstood something.

**Comment by vitaliykyrylyuk** [comment]
Yeah, same here, after installation i had no sidebar, but when i pressed "Customize", it appeared, but dissapeared when i closed customization...  I changed settings in "Change layout settings" area, and after that sidebar appeared completely.

**Comment by VinceSchlo** [comment]
Thank you vitali, I changed the settings to "No sidebar", saved and change again to "Rigth Sidebar" and now it's working.
