### ISSUE TITLE
Missing container class - row negative margin cause overflow-y

### ISSUE THREAD

**Issue by 0dp** [holger1411/understrap#496]
Hi there,

Fresh install of understrap, using FF57. Don't know how or where this fit in, but `.row`s negative margin seems to create overflow on the y-axis.
<img width="1100" alt="screen shot 2017-12-11 at 22 41 49" src="https://user-images.githubusercontent.com/3642367/33855302-c8f91dca-dec4-11e7-919e-eab4a0d11d62.png">

Is this normal behavior and if so, how would you avoid it correctly?

**Comment by craigpotter** [comment]
It's missing a container for me ......

**Comment by 0dp** [comment]
@holger1411 I think I got something here.
On a fresh install `get_theme_mod( 'understrap_container_type');` seems to return nothing. If I go to customize and select a container size, ` understrap_container_type ` gets set to `container`. If I try and change container type to "full width" `container` is not changed to `container-fluid`.

**Comment by 0dp** [comment]
in customizer.php:50
$choices = $setting->manager->get_control( $setting->id )->choices; 
Returns NULL.

**Comment by 0dp** [comment]
customizer.php:69
container_type should be `understrap_container_type`

**Comment by antonapua** [comment]
same

**Comment by antonapua** [comment]
#470 I shifted back to 6.5 until there are updates.

**Comment by 0dp** [comment]
@antonapua you should be able to apply the fix yourself. Check my comment or the PR i've made

**Comment by holger1411** [comment]
Should be fixed now with 0.6.12 (parent theme) and 0.3.10 (child theme)

**Comment by 0dp** [comment]
I haven't tested yet, but it looks like it's the same

**Comment by 0dp** [comment]
Tested on v. 0.6.12 issue is still present
