### ISSUE TITLE
Support for woocommerce 3.0 gallery?

### ISSUE THREAD

**Issue by bruceconlon** [holger1411/understrap#499]
Was looking to add support for the new WooCommerce 3.0 gallery features, using:

add_action( 'after_setup_theme', 'yourtheme_setup' );

function yourtheme_setup() {
add_theme_support( 'wc-product-gallery-zoom' );
add_theme_support( 'wc-product-gallery-lightbox' );
add_theme_support( 'wc-product-gallery-slider' );
}

(such as described in https://createandcode.com/broken-photo-gallery-and-lightbox-after-woocommerce-3-0-upgrade/)

However, when clicking the next thumbnail, the other images don't show?

**Comment by typeplus** [comment]
as per the docs you need;
https://woocommerce.com/flexslider/

Cheers

**Comment by bruceconlon** [comment]
Actually that isn't needed, the code above is correct. Its due to the max-width on the figure as described by @jhob101 in https://github.com/holger1411/understrap/issues/384

Closing this issue, as is tracked in 384

**Comment by typeplus** [comment]
I was only repeating what I was told from the official woo devs but you are absolutely correct. I just never bothered with the gallery in my projects as I use a custom one. Testing using `figure.woocommerce-product-gallery__wrapper {
    max-width: inherit;
}` and the gallery slider works fine.

**Comment by bruceconlon** [comment]
Much appreciated, thanks Jason.

**Comment by typeplus** [comment]
Sorry I didn't look into it mate, but here's a pull request to make sure no one else gets this issue: #519 😄

**Comment by bruceconlon** [comment]
Great stuff, ta

**Comment by jacksellwood** [comment]
I'm still having this issue with a child theme, so I added the CSS above, and the gallery is working now. Has that CSS snippet been added to the parent stylesheet on master? Seems like this should be patched instead of a manual hot fix on each site?

**Comment by reggieofarrell** [comment]
@jacksellwood It seems that the issue is that the Understrap child theme uses it's own scss and this fix has not been applied to that repo.  I just banged my head up agains the wall for a while on this one as well.
