### ISSUE TITLE
Owl Carousel won't start 

### ISSUE THREAD

**Issue by Ionut-Milas** [holger1411/understrap#50]
Hi there,

I want to build a slider on a custom page. 

`<div class="owl-carousel">

          <div class="item">div content 1</div>
          <div class="item">div content 2</div>
          <div class="item">div content 3</div>

        </div>`

and in footer...

`$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})`

Got no errors in the console, bot the carousel won't start...

Thanks for ideas guys

**Comment by holger1411** [comment]
Can you post the URL here? It´s hard to tell without seeing the code...

**Comment by holger1411** [comment]
Ah, sorry, was already closed...
