### ISSUE TITLE
Can only edit via FTP

### ISSUE THREAD

**Issue by sgrener** [holger1411/understrap#506]
For some reason I can only edit pages or posts on my website via FTP. If I try to edit through the wordpress dashboard the pages and posts do not have a text box for me to type in when in editing mode. The site has the Understrap theme.

Can you help figure out why i cannot edit my site in the wordpress dashboard? I do not want it to be FTP only.

Thanks

**Comment by holger1411** [comment]
Does it work if you switch to another theme, for example Twenty Seventeen?

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.
