### ISSUE TITLE
unbalanced <div>s in page.php

### ISSUE THREAD

**Issue by chrisgo** [holger1411/understrap#513]
This is just a minor nitpick but page.php does not have balanced <div>

The `<div id="primary">`  seems to be started somewhere deeper into the other templates but it should be in page.php so that the `<div>` tags are balanced

<img width="851" alt="screenshot 2017-12-29 21 37 27" src="https://user-images.githubusercontent.com/140798/34451622-9edaf016-ece0-11e7-8818-201fd8cb4c7f.png">

**Comment by Vishal-Deshpande** [comment]
Thanks @chrisgo . Although it looks like it is a misplaced div, it is not.

#primary div is generated by <?php get_template_part( 'global-templates/left-sidebar-check' ); ?> which is closed after <main>.

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.

**Comment by jack-fdrv** [comment]
For my opinion, better to move this closed tag to this template.

![Image of code](https://src.fdrv.guru/180329210736.jpg)
