### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'enqueue_my_styles_and_scripts' not found or invalid function name

### ISSUE THREAD

**Issue by gawronix** [holger1411/understrap#520]
### 

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'enqueue_my_styles_and_scripts' not found or invalid function name in E:\xampp\htdocs\wp-includes\class-wp-hook.php on line 286

`// Avoid the array_slice if possible.
				if ( $the_['accepted_args'] == 0 ) {
					$value = call_user_func_array( $the_['function'], array() );
				} elseif ( $the_['accepted_args'] >= $num_args ) {
					$value = call_user_func_array( $the_['function'], $args );
				} else {
					$value = call_user_func_array( $the_['function'], array_slice( $args, 0, (int)$the_['accepted_args'] ) );
				}
			}
		} while ( false !== next( $this->iterations[ $nesting_level ] ) );

		unset( $this->iterations[ $nesting_level ] );
		unset( $this->current_priority[ $nesting_level ] );

		$this->nesting_level--;

		return $value;
	}`

**Comment by crstnio** [comment]
Well, seems like you try to hook `enqueue_my_styles_and_scripts()` and the class `WP_Hook` cannot find said callback function.

Check the callback function you try to hook. It could be misspelled, in a `namespace` or declared as `private`/`protected` inside a class. WordPress hooks cannot find private methods.

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.

**Comment by philosophernazrul** [comment]
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'amusic' not found or invalid function name in C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php on line 286
﻿ how can i solve this warnig

**Comment by 0dp** [comment]
Show us how and where you include amusic
