### ISSUE TITLE
Consider ditching bower in favor of npm

### ISSUE THREAD

**Issue by fridays** [holger1411/understrap#53]
Hello guys, great project. The dependency management and build process could be simplified by ditching bower in favor of npm, together with gulp-browserify. Here is a good explanation: https://gofore.com/stop-using-bower/
Would that be an option?

**Comment by fridays** [comment]
More info: https://www.quora.com/Why-use-Bower-when-there-is-npm

**Comment by holger1411** [comment]
Yep, it is a good idea. No need for two dependency managers (anymore?).
Need to check anything first...and I need time for it...

**Comment by holger1411** [comment]
Just want to let you know that I work on it. There is a new branch called "no-bower" where I shift all dependencies step-by-step from bower to npm.
If it is ready and tested I will merge it into the master.
understrap itself is also available as npm package, now.

**Comment by holger1411** [comment]
Hi!
I jusr merged the "no-bower" branch into the master.
Means Bower is gone. All dependencies are handled by npm now.
You just need to type in
`npm install understrap` 
to install a fresh UnderStrap package with all dependencies 
plus
`gulp copy-assets`
to move everything in place.

**Comment by holger1411** [comment]
I will close this issue.
But feel free if you notice problems/bugs etc.
 :+1: to @fridays
