### ISSUE TITLE
Error: no mixin named -assert-ascending

### ISSUE THREAD

**Issue by elenabr** [holger1411/understrap#535]
Hi,
When trying to compile my scss with gulp I get this error: 

```
Message:
    src\sass\bootstrap4\_variables.scss
Error: no mixin named -assert-ascending

       Backtrace:
        src/sass/bootstrap4/_variables.scss:175
        on line 175 of src/sass/bootstrap4/_variables.scss
>> @include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
   ---------^
```

Can anyone tell me how to fix this? Would be very much appreciated..

**Comment by crstnio** [comment]
Looks like you're not the only one who runs against this wall: [Bootstrap repo: #23451](https://github.com/twbs/bootstrap/issues/23451)

This mixin is defined inside `_functions.scss` within the same directory. It should be included, too.

**Comment by elenabr** [comment]
Hey and thanks for answering! 
I somehow managed to get past the issue by updating understrap and also the child-theme.
