### ISSUE TITLE
Quick Question / Suggestions about Updating

### ISSUE THREAD

**Issue by dairc** [holger1411/understrap#539]
I'm currently using understrap 6.5 with the understrap child theme and everything is working well. However when I try to update beyond this version I get errors and actually with the latest versions (6.8 - 7.0) the entire page is nearly blank. The only thing I see is the site brand. I'm testing in a local env and will start a sprint tomorrow morning and dig in (6.7 has some jquery issues but I know these were fixed in the later versions and when I test 7.0 I'm showing no console errors.)

Anyway question is anyone have any ideas of where to start looking for what is causing this? 

Thanks in advance.

**Comment by axlright** [comment]
Do you have `define('WP_DEBUG', true);` in your config.php? That could help.

My first guess is that you need to change to `'walker'          => new understrap_WP_Bootstrap_Navwalker(),` in the `wp_nav_menu()` function in your `header.php`

You may have the old Navwalker listed there.

**Comment by dairc** [comment]
@axlright thank you sir, flipped the debug switch first / only thing that came up of course was exactly what you said.. saved me some time, fully appreciate it.
