### ISSUE TITLE
Dropdown menu no parent link

### ISSUE THREAD

**Issue by typeplus** [holger1411/understrap#54]
Hi Holger,
(My apologies if this isn't an issue but more a suggestion. Delete if need be.)

When there are dropdowns the parent link no longer works and is not clickable (#). To fix this you can modify the /inc/bootstrap-wp-navwalker.php file from line 90;

		
```
// If item has_children add atts to a.
if ( $args->has_children && $depth === 0 ) {
$atts['href']   		= '#';
$atts['data-toggle']	= 'dropdown';
$atts['class']			= 'nav-link dropdown-toggle';
} else {
$atts['href'] = ! empty( $item->url ) ? $item->url : '';
$atts['class']			= 'nav-link';
}
```

To

```
// Enable parent link dropdowns. If item has_children add atts to a.
if ( $args->has_children && $depth === 0 ) {
$atts['href'] = ! empty( $item->url ) ? $item->url : '';
//$atts['data-toggle']   = 'dropdown';
$atts['class']           = 'nav-link dropdown-toggle';
} else {
$atts['href'] = ! empty( $item->url ) ? $item->url : '';
$atts['class']			= 'nav-link';
}
```

Also you need to add the CSS (in either /sass/Bootstrap4/_dropdowns.scss or /sass/theme/_theme.scss or whichever override you have)

`.dropdown:hover .dropdown-menu {
display: block;
    }`

As I said delete if offtopic, but it may help someone else.

Cheers,
T+

**Comment by holger1411** [comment]
Sorry, a parent with a dropdown can´t be clickable. It will not work on mobiles. You can just touch the parent and open it or don´t open the drop down. There is nothing link :hover on mobiles.

So its not a bug but the correct behavior. The parent is just an empty placeholder.

**Comment by typeplus** [comment]
Sorry for the trouble Holger. I have some JavaScript that makes it work on mobile via double tap or holding down but you are definitely right its not a bug its just semantics.

**Comment by holger1411** [comment]
@typeplus no problem!

**Comment by deardorffdev** [comment]
I like this parent link solution but I haven't figured out how to pull it off yet. http://www.balibaytradingcompany.com/
What would I have to do to accomplish this?  I was able to add some jquery to make the dropdown hover, but I can't get the parent to link to it's url.

**Comment by holger1411** [comment]
Hi!
I would not recomend this parent link solution at all.
As you can see on your sample page it did not work on mobile mode.
The parent link works, but you can´t hover (there is no "hover" on mobile...) over it and open the submenu.
With other words: This solution makes submenu links useless on mobile devices.
