### ISSUE TITLE
Single Post Template contains incomplete html tags

### ISSUE THREAD

**Issue by MihirGosai** [holger1411/understrap#544]
`</div><!-- #primary -->`
This line points to `<div class="row">` tag

Please check: [single.php](https://github.com/holger1411/understrap/blob/master/single.php)

**Comment by axlright** [comment]
Check the left-sidebar or other loops that set start `<div>` tags. You can inspect elements on the final compiled html to see that the tags are (should be) complete. You can also run final compiled html through various validators to confirm the presence of any stray tags. I've not found any validation errors on incomplete tags.

**Comment by Adrian-S** [comment]
And when we start customising we have no idea there is important code in the left sidebar. A warning comment would help, but maybe there is room for improvement.

**Comment by MihirGosai** [comment]
Ok, Yes, I just checked the final html and all is well. It was too early to post here after seeing an error in wordpress's new editor. Thanks.
