### ISSUE TITLE
Understrap 0.8.0 WooCommerce error: version 3.1.0 is out of date. The core version is 3.3.0

### ISSUE THREAD

**Issue by TonyTheTech** [holger1411/understrap#546]
I am sure this is probably already known, but just pointing it out in case it is not or if someone has an ETA or advice on upgrading the templates. 

Woocommerce currently gives a bunch of template errors for Understrap saying "version 3.1.0 is out of date. The core version is 3.3.0"

Btw, thanks again for such an awesome theme!!

**Comment by typeplus** [comment]
Have an update I will push sometime this week. Just doing testing across a number of sites.

**Comment by aatanasow** [comment]
Also, some of the templates are version 1.6.4 or version 2.2.0. I'm not sure if this is intentional or not.

**Comment by holger1411** [comment]
Thx @TonyTheTech for reporting!
Fixed it with this commit: https://github.com/holger1411/understrap/commit/7b1f482f87ae0b3b5c198449041cb8eb98e4bf33

Will be part of the upcoming 0.8.1
