### ISSUE TITLE
screen reader text showing on desktop?

### ISSUE THREAD

**Issue by reil86** [holger1411/understrap#55]
The "posts navigation" title shows at the bottom of pagination and I'm wondering why it shows on my desktop. I thought it was only supposed to show if you have some sort of accessibility feature enabled? Unless Windows 10 or firefox automatically enables it?

I was going to just use a display: hidden class, but I was just curious!  

Also, semi-related: where do you edit the post nav?  I can't find it anywhere... Ex: Change "Older Posts" to "More Posts"

Thanks!

**Comment by holger1411** [comment]
"post navigation" is just the headline of the posts navigation. 
Its not an accessibility thingy.

The post navigation is a core WP function. Means the text comes from WP, not the theme by default.
Here is an article about it:
https://codex.wordpress.org/Function_Reference/the_posts_pagination

you can add parameters to it to overwrite the default text, or add a function to the functions.php to do it globally

Alternatively you may create an english text file to overwrite the defaults in one place
