### ISSUE TITLE
Issues creating a user - theme conflict with Wholesale Lead Capture plugin

### ISSUE THREAD

**Issue by JoeReadSEO** [holger1411/understrap#551]
Hi there,

I'm working on my first Understrap based project which has worked great so far - thank you!

I have come across a theme-plugin conflict against the 'Wholesale Lead Capture plugin':

https://wholesalesuiteplugin.com/product/woocommerce-wholesale-lead-capture/

The plugin uses the standard Wordpress username field as part of a registration form to register a new user.

However when combined with understrap, the form returns an error: "Cannot create a user with an empty login name".

The registration/plugin works with other themes I've tested but seems to conflict with understrap

Has the user registration process been altered in understrap? And if so, is there a way I can reset this back to default using my child theme?

Thanks in advance
Joe

**Comment by JoeReadSEO** [comment]
Update:

I debugged this further today, and found this routes back to the Understrap parent theme file woocommerce.php

More specifically the below line of code was blocking the user from being registered.

`// hook in and customizer form fields.
add_filter( 'woocommerce_form_field_args', 'understrap_wc_form_field_args', 10, 3 );`

Removing this line fixes the error but breaks the styling - short term I've used jquery to inject the classes back into the form fields.

Note: the woocommerce.php file cannot be overridden by the child theme - please could you resolve the above issue and push through the fix on the parent theme in the next update?

Let me know if you'd like me to send you the plugin file to test this,

Thanks
Joe

**Comment by dewoni** [comment]
Hi,

Thanks for the pointers Joe!

I fixed this in the following way:

In your custom php-file, set the disturbing filter to be removed on your wholesaler registration page.

add_action('wp_head', 'wholesaleRegFix');
function wholesaleRegFix() {
    if( is_page( 'your-registration-url')){
        remove_filter( 'woocommerce_form_field_args', 'understrap_wc_form_field_args', 10, 3 );
    }}

**Comment by JoeReadSEO** [comment]
That's great, make sense - thanks for this! Have added to my functions ready for the next update
