### ISSUE TITLE
issue with fixed-top navbar

### ISSUE THREAD

**Issue by kumakuta** [holger1411/understrap#553]
I've been trying to fix this by myself but i can't figure it out.

whenever i try to use fixed-top navbar, the content of the page is slipped under the navbar (ex: the carousel)

how to fix this? i got no idea how to

**Comment by ericlammel** [comment]
When you fixed navbars and others components, they automatically overlap the content.
To fix it, set your body tag with padding-top: 3rem;

**Comment by holger1411** [comment]
Closing this because of @ericlammel answere. He is right, you need some padding-top if you use a fixed like in this official bootstrap smaple: http://getbootstrap.com/docs/4.0/examples/navbar-fixed/
