### ISSUE TITLE
missing Bootstrap classes

### ISSUE THREAD

**Issue by uBaranQA** [holger1411/understrap#56]
Hi,
really great idea to combine the power of _s with Bootstrap and great workflow.

I've tried to customise the theme a little bit and found that:
- there's no .navbar-right class (ok in version 3 stable)
- there are some issues with formatting tablist - shows as an ordinary list instead

Are there some Bootstrap resources missing or some features work differently in v. 4?

Thanks,
Piotr

**Comment by holger1411** [comment]
Yes, there are several changes from BS3 to BS4. Please check out the v4 doc:
http://v4-alpha.getbootstrap.com/

**Comment by uBaranQA** [comment]
Thanks for the answer. I've switched to v.3 so far, but I'll take a closer look to the alpha.
