### ISSUE TITLE
wrapper ID naming inconsistent

### ISSUE THREAD

**Issue by ErinPo** [holger1411/understrap#565]
#single-wrapper
#page-wrapper
#search-wrapper
#archive-wapper
#error404-wrapper

but index.php uses:
#wrapper-index

it should be:
#index-wrapper

**Comment by holger1411** [comment]
Of course you are right...see: https://github.com/holger1411/understrap/commit/7230dd4fdd2df3643a6c9dc914cc4d22e68aaf30
Thx @ErinPo !
