### ISSUE TITLE
Use Non-Minified theme.css file

### ISSUE THREAD

**Issue by thefliik** [holger1411/understrap#57]
Hi!

Because understrap is setup to produce both a `theme.css` and a `theme.min.css` file out of the box (from the scss), I'm assuming there is a way to tell wordpress to use the `theme.css` file rather than the `theme.min.css` file? I can't figure out how to do this though.

Any help is greatly appreciated!

**Comment by holger1411** [comment]
Hi!
Here:
https://github.com/holger1411/understrap/blob/master/inc/enqueue.php#L9
you can change the file name.

**Comment by thefliik** [comment]
Excellent! Thank you so much!!

**Comment by tammoterhark** [comment]
But at each update of the understrap theme this change will be reverted. How to make this permanent?

**Comment by axlright** [comment]
You'd need to use a Child Theme if you want to change the default stylesheet and have it remain persistent through each upgrade of the Parent Theme.
