### ISSUE TITLE
Production version?

### ISSUE THREAD

**Issue by elpeyotl** [holger1411/understrap#58]
Thank you for this awsome theme. I like it! It helps me fasten my workflow. But i got a question. What do I have to do when i want to put this theme in production? Can I delete the node and Bower folders? At the moment the template is more than 100mb's which is quite high in my opinion. What is the best workflow? Using a childtheme? 

Thank you for your help

**Comment by typeplus** [comment]
In something like filezilla you can go to view > filename filters and mess with those settings.

[More info here](http://superuser.com/questions/13733/how-can-i-get-filezilla-to-ignore-folder-or-files-like-svn-or-cvs)

**Comment by elpeyotl** [comment]
Ok I understand that. So I can remove Node_modules and Bower_components in production? Wouldn't it make sense to create a gulp command which will create a DIST folder for production? Already cleaned up with only the necessary files? I can try if I find a solution...

**Comment by holger1411** [comment]
Yes, the bower and node stuff is just used in your dev enviroment. You don´t need to upload all these stuff to your live server

**Comment by holger1411** [comment]
Folder you don´t need on your live server:
/sass
/bower_components
/node_modules
/src

**Comment by holger1411** [comment]
Oh and yes: A dist task makes sense but I want to keep the git repro here sorted like the final zip install file.
So you can hit the "download" button on github and install it right in your WP. 
If you have an extra folder for it it will not work anymore...but it is a tradeoff.

**Comment by elpeyotl** [comment]
Okay. I created one for myself...Here is the code if anyone is interested in it. 

`// Run
// gulp dist
// Copies the files to the dist folder for distributon
gulp.task('dist', function() {
    gulp.src(['!sass','!bower_components', '!node_modules','!src','!dist','!bower.json', '!gulpfile.js', '!package.json', '*'])
        .pipe(gulp.dest('dist/'))
});`

**Comment by holger1411** [comment]
I add the task. You can now use the githubs zip file for installation OR upload the content of your /dist folder
/src and /dist are also in .gitignore so they are no part of the downloaded zip.
There are just there after running "gulp copy-assets" and "gulp dist"

**Comment by holger1411** [comment]
Clos

**Comment by elpeyotl** [comment]
@holger1411 Unfortunately I got some error with my code. This is the right one. Please update it if possible. 

```
// Run
// gulp dist
// Copies the files to the dist folder for distributon
gulp.task('dist', function() {
    gulp.src(['!sass','!bower_components', '!node_modules','!src','!dist','!bower.json', '!gulpfile.js', '!package.json', '*','*css/**/*','*fonts/**/*', '*img/**/*',
        '*inc/**/*','*js/**/*','*languages/**/*','*loop-templates/**/*','*page-templates/**/*'])
        .pipe(gulp.dest('dist/'))
});
```

THX
