### ISSUE TITLE
No categories on admin page?

### ISSUE THREAD

**Issue by jastuccio** [holger1411/understrap#6]
Hello,

I do not see categories in my dashboard when I create a new page.  They are in the database under wp_terms.  Are they turned off in this theme or is something wrong with my installation?

**Comment by holger1411** [comment]
No, the theme did not touch the admin settings. 
Categories are for posts only in WordPress. You can´t assign a page to a category. But you can create a parent page and assign child pages to it if you want to give your pages some structures.

**Comment by holger1411** [comment]
Clsoing this because its not a theme issue

**Comment by jastuccio** [comment]
Thank you holger1411.  Im new to WP too and learning things everyday.

**Comment by holger1411** [comment]
No problem! Have fun with WP!
