### ISSUE TITLE
Something wrong with the hero slider.

### ISSUE THREAD

**Issue by cnkevinlee** [holger1411/understrap#61]
In the index.php of the template file:
> if ( is_front_page() && is_home() ) {
>      get_sidebar('hero'); 

But it looks like there's no sidebar named hero anymore, I have tried the 
> get_sidebar('heroslider'); 

and it works.

But there's still no slide effect, and no class name of  _owl-carousel_ etc., like how the demo works. 

So, could you please tell me what's the exact way to use the owl-carousel, or is this feature is given up?

Thanks

**Comment by holger1411** [comment]
Hi!
The widgets id is "hero" see:
https://github.com/holger1411/understrap/blob/master/inc/widgets.php#L21

So:
```
if ( is_front_page() && is_home() ) {
get_sidebar('hero'); 
```
is correct, too.
Just its name ist "Hero Slider". Thats the text you see in your WP backend.

Make sure you use the latest version of UnderStrap (0.4.7).

And you must publish two widgets of this position, at least, to see the slider working.

**Comment by cnkevinlee** [comment]
@holger1411 Thanks!

I have seen that ID is "hero" too, which looks all right. But it's really strange here on my test server, `get_sidebar('hero'); ` doesn't work, but `get_sidebar('heroslider'); ` works...

Really strange...

**Comment by holger1411** [comment]
It could be that you start with an older version where "heroslider" position was present. After updating the widgets ID was gone, but your widget is already published on the old version. If you rename the new position to the old name the widget will appear again...

The solution should be unpublishing the widget, and than publish it again on the new her pos
