### ISSUE TITLE
Date posted and modified run together.

### ISSUE THREAD

**Issue by sbaldini** [holger1411/understrap#62]
I can't tell if this is a theme issue, but it seems that if you edit a post, it will have 2 dates posted next to each other: original post date and date modified. However; the date modified doesn't have any spacing after the original post date, or any indication of what it is.

**Comment by holger1411** [comment]
Hi!
Yep, its just the raw output.
The WP class for it is ".updated"
with time.updated{padding:0 10px;} <- just as example
in your CSS you can adjust the layout
