### ISSUE TITLE
SCSS dependency paths

### ISSUE THREAD

**Issue by JoelSanchez** [holger1411/understrap#63]
Hi, great theme, but I needed to edit the paths in:

sass/assets/owl-carousel2.scss
sass/assets/bootstrap4.scss
sass/assets/font-awesome.scss

Previously, they were like this:

`@import "../../src/sass/owl-carousel2/owl.carousel";`

Now they are like this:

`@import "../../bower_components/OwlCarousel2/src/scss/owl.carousel";`

Not sure if it is a bug or not, maybe I did something wrong (I executed npm install, bower install). Now everything works correctly.

**Comment by holger1411** [comment]
Hi!
Older versions of UnderStrap loads the assets directly from the /bower_components" folder...
Make sure you use the latest version 0.4.7

**Comment by JoelSanchez** [comment]
I'm using 0.4.7, just downloaded it from the website. 
The problem is that I don't have a /themes/understrap/src/ folder (that's why I changed the paths to bower_components), is is supposed to be generated somehow?

**Comment by diegoversiani** [comment]
Hi, Joel,

The `src` folder is generated by the command `$ gulp copy-assets`. You should run these commands as stated in https://github.com/holger1411/understrap#installing-dependencies:
```
$ npm install
$ bower install 
$ gulp copy-assets
```

**Comment by JoelSanchez** [comment]
Oops.
