### ISSUE TITLE
Feature: FTP upload of compiled CSS files

### ISSUE THREAD

**Issue by JoelSanchez** [holger1411/understrap#64]
I added these two tasks, which you may want to incorporate into the theme (or not):

https://gist.github.com/JoelSanchez/4ff2a8c6b0439ebf3334520522e485ac

**Comment by holger1411** [comment]
Good idea!
But just if it fits into your personal workflow and deployment process.
So its more an extra than a default task.
Will think about it...

**Comment by JoelSanchez** [comment]
I agree, wanted to share just in case :)

**Comment by holger1411** [comment]
:+1:
