### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by joelcomit** [holger1411/understrap#67]
I'm trying to use, but getting error when I make edits to _theme.scss. Error reads below:

Error: File to import not found or unreadable: ../../src/sass/bootstrap4/custom.
       Load paths:
         /Users/JoelMcDonald/Local Test Server/jamsbooks/wp-content/themes/understrap-master/sass
         Sass::Globbing::Importer
        on line 8 of /Users/JoelMcDonald/Local Test Server/jamsbooks/wp-content/themes/understrap-master/sass/assets/bootstrap4.scss
        from line 2 of /Users/JoelMcDonald/Local Test Server/jamsbooks/wp-content/themes/understrap-master/sass/theme.scss
  Use --trace for backtrace.

There is no "src" directory within the theme, but it is referenced. Am I missing something?

**Comment by holger1411** [comment]
Pleas install the dependencies first: 
https://github.com/holger1411/understrap#installing-dependencies
and make sure you run this command 
`gulp copy-assets`
That graps all 3rd party stuff and copies it into a new /src folder

**Comment by trevorgehman** [comment]
I got the same error and had to run `bower install` before it would work.

**Comment by holger1411** [comment]
If you use version 0.4.7 or older please run:
`npm install`
than
`bower install`
and
`gulp copy-assets`

If you use UnderStrap 0.4.8 (or newer) you just need to run:
`npm install`
and
`gulp copy-assets`

(Bower was skipped since this version)
