### ISSUE TITLE
Owl Slider on all pages

### ISSUE THREAD

**Issue by mkoller** [holger1411/understrap#68]
I have two different owl sliders on my homepage and have the owl setting setup in `slider_settings.js`. I also have Hero Slider and Hero Static activated in widgets. They both work perfectly but I would like to move one of the owl sliders into the footer.php so it gets included on all my custom pages. Doing so breaks the slider I took out of my homepage and placed in my footer.

I believe I need to change the following function in my `index.php`

```
 <?php
       if ( is_front_page() && is_home() ) {

       get_sidebar('hero'); 
       get_sidebar('statichero');

    } else {
    // Do nothing...or?
    }
    ?>
```

How do I change the slider so it conditionally shows up on all my wordpress pages?

**Comment by holger1411** [comment]
Hm, just to clearify it a bit: You want to have two different slider at the same time, one active in the upper header area and another in the footer area?

**Comment by mkoller** [comment]
I have 2 different sliders working on the the home / front page, the owl slider doesn't work on any other pages. I just need to figure out how to get the slider to work on pages that are not front page or home, or better yet not limit the slider functionality just to these two pages.
