### ISSUE TITLE
Woocommerce loop suggestion

### ISSUE THREAD

**Issue by typeplus** [holger1411/understrap#69]
The default woocommerce loop is set as the catchall;

`<?php woocommerce_content();`

this just spits out everything and to my knowledge doesn't allow you to style it as any changes you make to the default templates won't make any difference.

The easy fix would be to add this to the woocommerce.php file in either the master or child theme;

````
<!-- The WooCommerce loop -->

<?php
if (is_singular('product')) {
    woocommerce_content();
} else {
    //For ANY product archive.
    //Product taxonomy, product search or /shop landing
    woocommerce_get_template('archive-product.php');
}
?>
```

This enables changes to the archive-product.php to have an effect. Can confirm this works using a child theme or the parent theme.

**Comment by holger1411** [comment]
Makes sense, I test it and it *seems* to work.
Add it with latest commit: https://github.com/holger1411/understrap/commit/0c23350cae0d2978b355351a23c3532f40731fcc

Please report issues!

Thx @typeplus for this suggestion

**Comment by typeplus** [comment]
Thanks for testing and the commit :+1: 

Also thanks again for all your work on this project.
