### ISSUE TITLE
ERROR HEADER.PHP LINE 50

### ISSUE THREAD

**Issue by acoman** [holger1411/understrap#72]
PHP Parse error:  syntax error, unexpected '}' in /var/www/gallinasyfocas/wp-content/themes/understrap/header.php on line 50, referer: http://gallinasyfocas.com/wp-admin/options-reading.php

I fixed adding two ";" on the finish of function bloginfo and the_custom_logo
`<a class="navbar-brand" href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" rel="home"><?php if ( !has_custom_logo() ) { bloginfo( 'name' ); } else { the_custom_logo(); } ?></a>`

**Comment by jessijean** [comment]
Hi @acoman. There are a few things that should be changed to make sure you don't have issues toggling the logo on and off in the customizer.

Replace your code above from header.php with the following:

`<?php if (!has_custom_logo()) { ?>
<a class="navbar-brand" href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a>
<?php } else { the_custom_logo(); } ?>
`

Add this filter into inc/extras.php:

`add_filter('get_custom_logo','change_logo_class');
function change_logo_class($html)
{
	$html = str_replace('class="custom-logo"', 'class="img-responsive"', $html);
	$html = str_replace('class="custom-logo-link"', 'class="navbar-brand" custom-logo-link', $html);
	return $html;
}
`

This should fix any issues.
