### ISSUE TITLE
How to unregister the parent theme widgets?

### ISSUE THREAD

**Issue by sebgates** [holger1411/understrap#748]
Hi, I am trying to remove the widgets that ship with the parent theme. I am customising a child and added the following to my functions.php file as recommended here:

https://codex.wordpress.org/Function_Reference/unregister_sidebar
 Use the following code:

function remove_some_widgets(){

	// Unregister some of the sidebars
	unregister_sidebar( 'Hero Slider' );
	unregister_sidebar( 'Top Full' );
	unregister_sidebar( 'Hero Canvas' );
}
add_action( 'widgets_init', 'remove_some_widgets', 11 );

No joy - Any ideas how I remove the widgets from the WP admin area? (Apologies in advance if this is something easy, I am in my first few months of moving from the Genesis Framework to Standard WP templates)

![screen shot 2018-07-19 at 14 23 13](https://user-images.githubusercontent.com/7439402/42945065-4ba8aa14-8b5f-11e8-9927-e23425ca9869.png)

**Comment by KarineDia** [comment]
Maybe try with the 'slugs' name of the widgets:
unregister_sidebar( 'hero' );
unregister_sidebar( 'herocanvas' );

**Comment by sebgates** [comment]
That did the job. Thanks.....

**Comment by KarineDia** [comment]
Cool!
