### ISSUE TITLE
gulp copy-assets error ENOENT

### ISSUE THREAD

**Issue by pandorawombat** [holger1411/understrap#76]
Trying to set this up, and when I run the gulp copy-assets after npm install and bower install, I get an error ENOENT, complaining about not being able to find a specific directory named "vendor," located at /understrap/node-modules/node-sass/vendor. All directories leading up to it are there, but there is no vendor directory in that node-sass directory. What is going wrong? If I create that directory, will it fix this? Or is something misnamed somewhere? It's 0.4.7

**Comment by holger1411** [comment]
Hi!
Sorry for the late reply. Seems I missed it...
Please update to 0.4.8 and run:
`npm install`
and
`gulp copy-assets`
in your terminal.

That *should* fix the problem
