### ISSUE TITLE
OwlCarousel versions incompatibility

### ISSUE THREAD

**Issue by lord-enzo** [holger1411/understrap#77]
I cannot get included owlcarousel to work the way I need it to, and I would really prefer to keep using v1 until v2 gets out of beta. How could I remove owl from the theme so I can add the v1 in my theme?

**Comment by maxdmyers** [comment]
You can follow these steps to use Owl Carousel v1.

- change the line in **package.json** that reads `"owl.carousel": "^2.1.4"` to `"owlcarousel-pre": "^1.3.3"`.
- In **gulpfile.js** change `gulp.src(basePaths.node + 'owl.carousel/dist/*.js')` to `gulp.src(basePaths.node + 'owlcarousel-pre/owl-carousel/*.js')`
- In **gulpfile.js** change `gulp.src(basePaths.node + 'owl.carousel/dist/assets/*.css')` to `gulp.src(basePaths.node + 'owlcarousel-pre/owl-carousel/*.css')`
- Run `gulp copy-assets`
- Run `gulp scripts`

After that, you should be using the latest version of Owl Carousel v1. Let me know if you have any issues, but it worked for me. Someone else can jump in if there's something I've missed.

**Comment by maxdmyers** [comment]
@holger1411 I think this issue can be closed now. Maybe we could create a branch with this implemented so people could choose easily?
