### ISSUE TITLE
Missing folder src

### ISSUE THREAD

**Issue by emanuelepinna** [holger1411/understrap#78]
Hi,
why is now available folder **src** in donwload file?

thank you
Regards

**Comment by holger1411** [comment]
Its just a folder holding a copy of the third party assets. It will appear as soon as you run:
`gulp copy-assets`
But it is used for dev ourposes only, so there is no need to included it into the install pack by default.

**Comment by emanuelepinna** [comment]
if i compile file _theme.scss with Codekit i get this error without **src** folder


```
Error: File to import not found or unreadable: ../../src/sass/bootstrap4/custom.
       Load paths:
         /Applications/MAMP/htdocs/1wordpressdemo/wp-content/themes/understrap/sass
         Sass::Globbing::Importer
        on line 8 of /Applications/MAMP/htdocs/1wordpressdemo/wp-content/themes/understrap/sass/assets/bootstrap4.scss
        from line 2 of /Applications/MAMP/htdocs/1wordpressdemo/wp-content/themes/understrap/sass/theme.scss
  Use --trace for backtrace.
```
am I doing something wrong?

**Comment by holger1411** [comment]
Are you sure you run the "gulp copy-assets" command in your terminal before?
This:
../../src/sass/bootstrap4/custom
file is the first file which is loaded by the sass file from the /src directory.

**Comment by emanuelepinna** [comment]
yes I run "gulp copy-assets"

this is my terminal 
`MacBookdiEmanuele:understrap myname$ gulp copy-assets
[15:44:58] Using gulpfile ~/Desktop/understrap/gulpfile.js
[15:44:58] Starting 'copy-assets'...
[15:44:58] Finished 'copy-assets' after 14 ms
MacBookdiEmanuele:understrap myname$ 
`

but i can't see src folder inside understrap folder

**Comment by holger1411** [comment]
Do you run 
`npm install`
before?
Is there a /node_modules folder in your /understrap folder?

**Comment by emanuelepinna** [comment]
ok now all work fine.
I had run the `npm install` out of the folder understrap!...i'm sorry.

Another question, for update all dependence by bower i run command `bower install` , appear folder "bower_components" with all dependence package .
I have to do some other action to update undestrap the latest version?
thanks for your patience

**Comment by holger1411** [comment]
UnderStrap 0.4.7 is the latest version using Bower. I remove it because npm is also a dependency manager. That means:
With 0.4.8 you have to run just:
`npm install`
`gulp copy-assets`

to download all dependencies and place all needed stuff in the /src folder in the correct order.
With 0.4.7 or older you have to run:
`npm install`
`bower install`
`gulp copy-assets`

to do the same

**Comment by emanuelepinna** [comment]
ok now all clear!:-)
you already know when it is released the version 0.4.8?

best regards

**Comment by holger1411** [comment]
Was released yesterday,-)

**Comment by pscott-au** [comment]
I am still seeing the same error after trying the suggestions.

```
understrap peter$ gulp watch
[11:00:30] Using gulpfile ~/CCP-DEVOPS/playbooks/www/wp-content/themes/understrap/gulpfile.js
[11:00:30] Starting 'watch'...
[11:00:30] Finished 'watch' after 27 ms
[11:00:37] Starting 'sass'...
[11:00:37] Finished 'sass' after 14 ms
[11:00:37] Plumber found unhandled error:
 Error in plugin 'gulp-sass'
Message:
    sass/assets/bootstrap4.scss
Error: File to import not found or unreadable: ../../src/sass/bootstrap4/animation.
       Parent style sheet: /Users/peter/CCP-DEVOPS/playbooks/www/wp-content/themes/understrap/sass/assets/bootstrap4.scss
        on line 28 of sass/assets/bootstrap4.scss
>> @import "../../src/sass/bootstrap4/animation";
```

any other suggestions?

**Comment by holger1411** [comment]
Is this file:
/src/sass/bootstrap4/animation
in your UnderStrap folder?
If not run:

`npm install`
followed by:
`gulp copy-assets`

**Comment by pscott-au** [comment]
yes - tried that and various permutations including from the parent
directory.I was able to copy the file from somewhere else but it causes
other issues. Is it possible that the latest bootstrap package doesn't have
these scss files .. i thought I saw somewhere that they were removed.

**Comment by pscott-au** [comment]
![image](https://cloud.githubusercontent.com/assets/5900187/21739778/f48883f6-d4f0-11e6-939f-0a06daa9810e.png)

**Comment by holger1411** [comment]
Hm, which UnderStrap version do you use in combination with which Bootstrap version?

And yes: The latest Bootstrap 4 Alpha 6 package comes with some different named scss files.
For example there is no _animations.scss file anymore in this version.
Make sure you download the latest version of this UnderStrap file:
https://github.com/holger1411/understrap/blob/master/sass/assets/bootstrap4.scss

It should start with:
```
/*!
 * Bootstrap v4.0.0-alpha.6 (https://getbootstrap.com)
 * Copyright 2011-2017 The Bootstrap Authors
 * Copyright 2011-2017 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
```

**Comment by pscott-au** [comment]
ok - yes - Bootstrap v4.0.0-alpha.5
Was getting the same from the zipped download and from the latest github .. maybe I was pulling the wrong version .. thanks for the assist

**Comment by pscott-au** [comment]
i am bumbling a little - not really played with SAAS and although I'm pretty comfortable with bootstrap I've not used WP for a few years .. if there's anything I can do to help this project let me know .. I'm trying to fumble through but if any assistance then am happy to write up some help files or do whatever else I can.

**Comment by holger1411** [comment]
Hm, no. Alpha 6 was released yesterday evening.
The latest stable UnderStrap release (0.5.1) still uses Alpha 5.

I´am currently working on the next version which ist already available here on GitHub (if you hit the green "clone or  download button"), and will be releases as 0.5.2 soon. This version uses Alpha 6.

So if you run 0.5.1 but changes the BS version number in your package.json to Alpha 6 manually you should  receive this type of error.

Or another reason could be that your download UnderStrap from Github yesterday. During my alpha 6 commits...and before I´am done with it. ;-)
That would be very bad luck...

So where and when do you download which UnderStrap version?

That would help to find out if there is something missing and a bug in it or if it was just bad luck.

**Comment by pscott-au** [comment]
yeah - prolly cloned yesterday :)

**Comment by holger1411** [comment]
Puh, okay. That it was bad luck.
Just re-clone it and it *shoud* work.

And by the way: Any help is appreciated!
