### ISSUE TITLE
Navwalker showing menu in reverse?

### ISSUE THREAD

**Issue by odorsey** [holger1411/understrap#80]
I seem to be running into an issue with my menu on my understrap themed site. I am developing on WordPress 4.6.1.

Whenever I set the menu on the WordPress dashboard in the correct order-- ie. `home, about us, blog, articles, contact us`-- on larger screens, the nav appears as `contact us, articles, blog, about us, home`. On smaller screens (where the menu is toggled), the nav appears correctly as `home, about us, blog, articles, contact us`. 

If I set the menu to `contact us, articles, blog, about us, home` on the WordPress dashboard, the nav menu appears correctly on larger screens, but appears as the reverse-- `contact us, articles, blog, about us, home` on smaller screens.

Maybe I'm missing something... is there something that I can change to make sure that the menu is ordered correctly regardless of the screen size?

Thanks in advance for the help!

**Comment by typeplus** [comment]
Are you floating the <ul> and <li> by any chance?

**Comment by odorsey** [comment]
I'm floating their classes and ids:
In my _theme.scss;
`.navbar #main-menu, .navbar-nav .nav-item  {
    float: left; // need to change to float: left for mobile
    margin-top: 3%;
    padding: 0px 2px;
    font-size: 0.96rem;
    text-transform: lowercase;
}`

In my media queries scss file:
` @include media-breakpoint-up(sm) {
      .navbar #main-menu, .navbar-nav .nav-item  {
          float: right;
       }
   }`

**Comment by typeplus** [comment]
It's only necessary to float the parent element and not the child elements if you want to achieve what I think you do. One solution is to add a class to the `<div class="collapse navbar-toggleable-xs exCollapsingNavbar">` such as `.right {float:right;}` 

or just simply add 

` .collapse.navbar-toggleable-xs.exCollapsingNavbar {
float:right;
}` to your media query.

**Comment by odorsey** [comment]
@typeplus, that worked perfectly. Thanks for your help! I can't believe it was that simple... 😕

**Comment by typeplus** [comment]
No probs mate! If sorted close this one off so Holger doesnt have to 👍

**Comment by odorsey** [comment]
No worries! Will do

**Comment by holger1411** [comment]
:thumbsup:
