### ISSUE TITLE
Browser sync

### ISSUE THREAD

**Issue by jacobtarr** [holger1411/understrap#81]
Hi, Just wanted to say I'm very much enjoying the theme, however, one thing I cant seem to figure out is the Browser Sync set up. So if I'm running a Wordpress site on mamp on Apache and the port is 8888 and my site runs locally at http://localhost:8888/site_name/, how would I make that work in the proxy configuration for the Gulp file? I tried setting the proxy to "localhost:8888/site_name/" but BS seems to run on the 3000 port unfortunately. Am I missing something here? Thanks!

**Comment by diegoversiani** [comment]
Hi @jacobtarr,

I haven't tried running Apache on port other than 80 but that shouldn't be a problem. Browser-sync can directly serve html pages or proxy a server already running on any port on your computer.

While in proxy mode, browser-sync needs to run a server (on port 3000 or any other available) only to inject its necessary javascript libraries into your pages. Your website pages will still be generated in your Apache server running on port 8888.

So the requests runs like this:

1. Chrome makes a request to yoursite:3000
2. Browser-sync server makes the same request to yoursite:8888
3. Apache server process your request, generate the page and returns it to Browser-sync
4. Browser-sync server injects javascript code into the pages returned by Apache and returns it to Chrome
5. Chrome renders the page

In your gulpfile you should change the proxy setting to `localhost:8888/site_name/`. Try changing a .php file while browser-sync is up and see if the page reloads automatically.

If you have further questions let us know :)

**Comment by andrewcas** [comment]
This issue is solved by editing the proxy value in the browserSyncOptions object located in gulpconfig.json


```
  "browserSyncOptions" : {
    "proxy": "localhost:8888/your-local-domain-here/",
    "notify": false
  },
```

**Comment by wphjaelpen** [comment]
In what line in gulpconfig.json shall i add :

  "browserSyncOptions" : {
    "proxy": "localhost/wordpress/",
    "notify": false
  }

**Comment by axlright** [comment]
It's the first lines of `gulpconfig.json`

If you're using https, you'll need to provide a path to your SSL certs like so:

```
  "browserSyncOptions" : {
    "proxy": "https://local-alexwright.net",
    "notify": true,
    "https": {
      "key": "/private/etc/apache2/extra/localhost.key.pem",
      "cert": "/private/etc/apache2/extra/localhost.crt.pem"
    } 
  },
```
