### ISSUE TITLE
data attribute for collapse menu after clicking

### ISSUE THREAD

**Issue by emanuelepinna** [holger1411/understrap#85]
Hi,
I'm developing onepage website with plugin scroll to id.
i have add  `$atts['data-toggle']   = 'collapse';` 
and  `$atts['data-target'] = '.in';`  in  `bootstrap-wp-navwalker.php` for hide the toggle menu after click the link.
It is working properly, except for the external links of the menu.
When i click the external link in menu, it collapse without change page.
Do you have a suggestion to solve this problem?

thank you
best regards
Emanuele

**Comment by holger1411** [comment]
Changed the toggle markup from the old BS3 version to BS4 recently.
Use the latest 0.4.9 pre-relase version of header.php:
https://github.com/holger1411/understrap/blob/master/header.php
Maybe that helps...

**Comment by emanuelepinna** [comment]
Hi,
Thanks, I tried your solution but not work!

for now I solved by adding this script
```
$('.navbar-toggleable-md').click(function () {
    var navbar_toggle = $('.navbar-toggle');
    if (navbar_toggle.is(':visible')) {
        navbar_toggle.trigger('click');
    }
});
```
