### ISSUE TITLE
Owl Javascript not found (including fix)

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [holger1411/understrap#9]
Hi Holger,
just wanted to let you know, that the owl-script cannot be found, which makes the slider non-working.

> Failed to load resource: the server responded with a status of 404 (Not Found) http://<domainname>/wp-content/themes/<themename>/js/owl.carousel.min.js 

It doesnt seem to get compiled by the gulp-task. The owl css however is getting compiled.

The fix is easy. Add the following code before the closing }); in the gulpfile.js

```php
// owl JS files
    gulp.src(basePaths.bower + 'OwlCarousel2/dist/*.js')
        .pipe(gulp.dest('./js'));
```

**Comment by Thomas-A-Reinert** [comment]
Correction: the css won´t get compiled. It seems that it was copied by hand.

Following code resolves that problem:
```php
// Copy all Owl2 SCSS files
    gulp.src(basePaths.bower + 'OwlCarousel2/dist/assets/*.css')
       .pipe(gulp.dest('./css'));
```

Cannot explain

**Comment by holger1411** [comment]
Ha! Thx again!

**Comment by Thomas-A-Reinert** [comment]
No problem :)

**Comment by Ionut-Milas** [comment]
is this merged as I still get the error ?

**Comment by holger1411** [comment]
Hi!
the latest version of UnderStrap loads just one minified and uglyfied JS file (theme.min.js).
If you get an error message about a missing /owl.carousel.min.js  file you might use an older version
