### ISSUE TITLE
Where do I set custom RTL styles?

### ISSUE THREAD

**Issue by ibanner** [holger1411/understrap#91]
The readme file says something about a "simple RTL file", but I couldn't find any. Originally "Underscores" has an `rtl.css` file right next to `style.css`... 

~~Should I just go ahead and create one?~~
**Edit:** I just went ahead and added an `rtl.css` file right next to `style.css`, but still I'd like to know if this is what I should've done...

Please advise.

**Comment by holger1411** [comment]
Yeap. At this point there is no special rtl.css dev process. Just creat an rtl-css file and drop it into your theme root directory.

**Comment by ibanner** [comment]
OK. Please consider correcting your README text, to prevent more RTL-confusion :-)

**Comment by holger1411** [comment]
+1
https://github.com/holger1411/understrap/commit/52da703bb325325baef85961ce5d9319b02ea1e2

**Comment by ibanner** [comment]
@holger1411 Sorry for being such a pain in the b**t, but Instead of just removing the line, I do recommend adding a specific remark for people to add their own `rtl.css` file if they need one.

**Comment by holger1411** [comment]
Hi!
You are totaly right, adding some basic infos to readme.md
