### ISSUE TITLE
Undefined variable error when running gulp sass

### ISSUE THREAD

**Issue by olivierdelomez** [holger1411/understrap#92]
Hi,
I run into the following error when I run `gulp sass`

> Error in plugin 'gulp-sass'
>   src/sass/understrap/understrap/understrap.scss
>Error: Undefined variable: "$grid-gutter-width".
>        on line 3 of src/sass/understrap/understrap/understrap.scss

Seems like a false positive and I'm missing the bigger picture.

I'm working inside the child theme, I ran the `npm install` and `gulp copy-assets`.

What is the proper workflow to update css/js with the child theme ? 

thanks !

**Comment by VesterDe** [comment]
The bootstrap source changed a bit  as far as I can tell, and that variable doesn't seem to exists anymore. You can change it to $grid-gutter-width-base to get rid of the error.

**Comment by maxdmyers** [comment]
This is already fixed in 7414bb0. Update to the latest and run `gulp sass` again.

**Comment by holger1411** [comment]
Yep, $grid-gutter-width was changed to $grid-gutter-width-base in BS4 Alpha 5
