### ISSUE TITLE
Localhost/browsersync not working on 0.4.9

### ISSUE THREAD

**Issue by VesterDe** [holger1411/understrap#93]
Hey, I made a project from understrap recently (v0.4.7) and everything worked (works) fine with it. Today I started a new site for a new client and after copying assets and running watch-bs localhost doesn't work. It loads till infinity. The BS UI still works though.

I'd love to give more data, just point me in a direction for where to look.

The things that are constant for both projects are:
- Node version (6.2.2)
- NPM version (3.10.5)

Thanks.

**Comment by holger1411** [comment]
Hm, was added by @diegoversiani 
Can you look into this?

**Comment by VesterDe** [comment]
I suspect this may have been my fault, I use understrap with Wocker, so I just needed to set
`proxy: "wocker.dev",`
and now it's fine.

Closing for now, hope it doesn't come up again.
