### ISSUE TITLE
Should browserSyncWatchFiles have a wildcard for *.php?

### ISSUE THREAD

**Issue by VesterDe** [holger1411/understrap#94]
I noticed in the gulpfile that BrowserSync is set to watch only root level php file changes. I've changed it for all of my projects so far to have './*_/_.php' wildcard, because I like to make directories for better comprehension a lot, and then it bugs me that it reloads for some php files and not for others...

Is there a specific reason it's set to root or would wildcard perhaps serve better? I can make a pull request if the change makes sense.

**Comment by holger1411** [comment]
Hi @VesterDe!
no there is no real reason. Watching all .php files should not be a performance issue on average machines...
Fell free to create a pull request!

**Comment by holger1411** [comment]
Was added
